### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod
  id: SettingsBundleConverterMethod
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  children:
  - Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.#ctor(System.Object,System.IntPtr)
  - Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.BeginInvoke(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String,System.AsyncCallback,System.Object)
  - Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.EndInvoke(System.IAsyncResult)
  - Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.Invoke(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String)
  langs:
  - csharp
  - vb
  name: SettingsBundleConverterMethod
  nameWithType: SettingsBundleConverterMethod
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod
  type: Delegate
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  syntax:
    content: public delegate void SettingsBundleConverterMethod(ISettingsBundle sourceSettingsBundle, ISettingsBundle targetSettingsBundle, string fileTypeId);
    parameters:
    - id: sourceSettingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
    - id: targetSettingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
    - id: fileTypeId
      type: System.String
    content.vb: Public Delegate Sub SettingsBundleConverterMethod(sourceSettingsBundle As ISettingsBundle, targetSettingsBundle As ISettingsBundle, fileTypeId As String)
  modifiers.csharp:
  - public
  - delegate
  modifiers.vb:
  - Public
  - Delegate
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.#ctor(System.Object,System.IntPtr)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.#ctor(System.Object,System.IntPtr)
  id: '#ctor(System.Object,System.IntPtr)'
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod
  langs:
  - csharp
  - vb
  name: SettingsBundleConverterMethod(Object, IntPtr)
  nameWithType: SettingsBundleConverterMethod.SettingsBundleConverterMethod(Object, IntPtr)
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.SettingsBundleConverterMethod(System.Object, System.IntPtr)
  type: Constructor
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  syntax:
    content: public SettingsBundleConverterMethod(object object, IntPtr method)
    parameters:
    - id: object
      type: System.Object
    - id: method
      type: System.IntPtr
    content.vb: Public Sub New(object As Object, method As IntPtr)
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.Invoke(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.Invoke(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String)
  id: Invoke(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String)
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod
  langs:
  - csharp
  - vb
  name: Invoke(ISettingsBundle, ISettingsBundle, String)
  nameWithType: SettingsBundleConverterMethod.Invoke(ISettingsBundle, ISettingsBundle, String)
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.Invoke(Sdl.Core.Settings.ISettingsBundle, Sdl.Core.Settings.ISettingsBundle, System.String)
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  syntax:
    content: public virtual void Invoke(ISettingsBundle sourceSettingsBundle, ISettingsBundle targetSettingsBundle, string fileTypeId)
    parameters:
    - id: sourceSettingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
    - id: targetSettingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
    - id: fileTypeId
      type: System.String
    content.vb: Public Overridable Sub Invoke(sourceSettingsBundle As ISettingsBundle, targetSettingsBundle As ISettingsBundle, fileTypeId As String)
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.Invoke*
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.BeginInvoke(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String,System.AsyncCallback,System.Object)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.BeginInvoke(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String,System.AsyncCallback,System.Object)
  id: BeginInvoke(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String,System.AsyncCallback,System.Object)
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod
  langs:
  - csharp
  - vb
  name: BeginInvoke(ISettingsBundle, ISettingsBundle, String, AsyncCallback, Object)
  nameWithType: SettingsBundleConverterMethod.BeginInvoke(ISettingsBundle, ISettingsBundle, String, AsyncCallback, Object)
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.BeginInvoke(Sdl.Core.Settings.ISettingsBundle, Sdl.Core.Settings.ISettingsBundle, System.String, System.AsyncCallback, System.Object)
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  syntax:
    content: public virtual IAsyncResult BeginInvoke(ISettingsBundle sourceSettingsBundle, ISettingsBundle targetSettingsBundle, string fileTypeId, AsyncCallback callback, object object)
    parameters:
    - id: sourceSettingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
    - id: targetSettingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
    - id: fileTypeId
      type: System.String
    - id: callback
      type: System.AsyncCallback
    - id: object
      type: System.Object
    return:
      type: System.IAsyncResult
    content.vb: Public Overridable Function BeginInvoke(sourceSettingsBundle As ISettingsBundle, targetSettingsBundle As ISettingsBundle, fileTypeId As String, callback As AsyncCallback, object As Object) As IAsyncResult
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.BeginInvoke*
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.EndInvoke(System.IAsyncResult)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.EndInvoke(System.IAsyncResult)
  id: EndInvoke(System.IAsyncResult)
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod
  langs:
  - csharp
  - vb
  name: EndInvoke(IAsyncResult)
  nameWithType: SettingsBundleConverterMethod.EndInvoke(IAsyncResult)
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.EndInvoke(System.IAsyncResult)
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  syntax:
    content: public virtual void EndInvoke(IAsyncResult result)
    parameters:
    - id: result
      type: System.IAsyncResult
    content.vb: Public Overridable Sub EndInvoke(result As IAsyncResult)
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.EndInvoke*
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  isExternal: true
  name: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
- uid: Sdl.Core.Settings.ISettingsBundle
  isExternal: true
  name: ISettingsBundle
  nameWithType: ISettingsBundle
  fullName: Sdl.Core.Settings.ISettingsBundle
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.#ctor*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.#ctor
  isExternal: true
  name: SettingsBundleConverterMethod
  nameWithType: SettingsBundleConverterMethod.SettingsBundleConverterMethod
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.SettingsBundleConverterMethod
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.IntPtr
  commentId: T:System.IntPtr
  parent: System
  isExternal: true
  name: IntPtr
  nameWithType: IntPtr
  fullName: System.IntPtr
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.Invoke*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.Invoke
  isExternal: true
  name: Invoke
  nameWithType: SettingsBundleConverterMethod.Invoke
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.Invoke
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.BeginInvoke*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.BeginInvoke
  isExternal: true
  name: BeginInvoke
  nameWithType: SettingsBundleConverterMethod.BeginInvoke
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.BeginInvoke
- uid: System.AsyncCallback
  commentId: T:System.AsyncCallback
  parent: System
  isExternal: true
  name: AsyncCallback
  nameWithType: AsyncCallback
  fullName: System.AsyncCallback
- uid: System.IAsyncResult
  commentId: T:System.IAsyncResult
  parent: System
  isExternal: true
  name: IAsyncResult
  nameWithType: IAsyncResult
  fullName: System.IAsyncResult
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.EndInvoke*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.EndInvoke
  isExternal: true
  name: EndInvoke
  nameWithType: SettingsBundleConverterMethod.EndInvoke
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.EndInvoke
