### YamlMime:ManagedReference
items:
- uid: Sdl.Core.Globalization.UnitMetadata.LabelValueSet
  commentId: T:Sdl.Core.Globalization.UnitMetadata.LabelValueSet
  id: LabelValueSet
  parent: Sdl.Core.Globalization.UnitMetadata
  children:
  - Sdl.Core.Globalization.UnitMetadata.LabelValueSet.#ctor
  - Sdl.Core.Globalization.UnitMetadata.LabelValueSet.ContainsLabel(System.String)
  - Sdl.Core.Globalization.UnitMetadata.LabelValueSet.GetLabel(System.Double)
  - Sdl.Core.Globalization.UnitMetadata.LabelValueSet.GetLabel(System.Int32)
  - Sdl.Core.Globalization.UnitMetadata.LabelValueSet.LabelValueConditions
  - Sdl.Core.Globalization.UnitMetadata.LabelValueSet.Preferred
  langs:
  - csharp
  - vb
  name: LabelValueSet
  nameWithType: LabelValueSet
  fullName: Sdl.Core.Globalization.UnitMetadata.LabelValueSet
  type: Class
  source:
    path: Sdl.Core.Globalization
    isExternal: true
  assemblies:
  - Sdl.Core.Globalization
  namespace: Sdl.Core.Globalization.UnitMetadata
  syntax:
    content: public class LabelValueSet
    content.vb: Public Class LabelValueSet
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.ContainsLabel(System.String)
  commentId: M:Sdl.Core.Globalization.UnitMetadata.LabelValueSet.ContainsLabel(System.String)
  id: ContainsLabel(System.String)
  parent: Sdl.Core.Globalization.UnitMetadata.LabelValueSet
  langs:
  - csharp
  - vb
  name: ContainsLabel(String)
  nameWithType: LabelValueSet.ContainsLabel(String)
  fullName: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.ContainsLabel(System.String)
  type: Method
  source:
    path: Sdl.Core.Globalization
    isExternal: true
  assemblies:
  - Sdl.Core.Globalization
  namespace: Sdl.Core.Globalization.UnitMetadata
  syntax:
    content: public bool ContainsLabel(string label)
    parameters:
    - id: label
      type: System.String
    return:
      type: System.Boolean
    content.vb: Public Function ContainsLabel(label As String) As Boolean
  overload: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.ContainsLabel*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.GetLabel(System.Int32)
  commentId: M:Sdl.Core.Globalization.UnitMetadata.LabelValueSet.GetLabel(System.Int32)
  id: GetLabel(System.Int32)
  parent: Sdl.Core.Globalization.UnitMetadata.LabelValueSet
  langs:
  - csharp
  - vb
  name: GetLabel(Int32)
  nameWithType: LabelValueSet.GetLabel(Int32)
  fullName: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.GetLabel(System.Int32)
  type: Method
  source:
    path: Sdl.Core.Globalization
    isExternal: true
  assemblies:
  - Sdl.Core.Globalization
  namespace: Sdl.Core.Globalization.UnitMetadata
  syntax:
    content: public string GetLabel(int value)
    parameters:
    - id: value
      type: System.Int32
    return:
      type: System.String
    content.vb: Public Function GetLabel(value As Integer) As String
  overload: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.GetLabel*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.GetLabel(System.Double)
  commentId: M:Sdl.Core.Globalization.UnitMetadata.LabelValueSet.GetLabel(System.Double)
  id: GetLabel(System.Double)
  parent: Sdl.Core.Globalization.UnitMetadata.LabelValueSet
  langs:
  - csharp
  - vb
  name: GetLabel(Double)
  nameWithType: LabelValueSet.GetLabel(Double)
  fullName: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.GetLabel(System.Double)
  type: Method
  source:
    path: Sdl.Core.Globalization
    isExternal: true
  assemblies:
  - Sdl.Core.Globalization
  namespace: Sdl.Core.Globalization.UnitMetadata
  syntax:
    content: public string GetLabel(double value)
    parameters:
    - id: value
      type: System.Double
    return:
      type: System.String
    content.vb: Public Function GetLabel(value As Double) As String
  overload: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.GetLabel*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.#ctor
  commentId: M:Sdl.Core.Globalization.UnitMetadata.LabelValueSet.#ctor
  id: '#ctor'
  parent: Sdl.Core.Globalization.UnitMetadata.LabelValueSet
  langs:
  - csharp
  - vb
  name: LabelValueSet()
  nameWithType: LabelValueSet.LabelValueSet()
  fullName: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.LabelValueSet()
  type: Constructor
  source:
    path: Sdl.Core.Globalization
    isExternal: true
  assemblies:
  - Sdl.Core.Globalization
  namespace: Sdl.Core.Globalization.UnitMetadata
  syntax:
    content: public LabelValueSet()
    content.vb: Public Sub New
  overload: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.Preferred
  commentId: P:Sdl.Core.Globalization.UnitMetadata.LabelValueSet.Preferred
  id: Preferred
  parent: Sdl.Core.Globalization.UnitMetadata.LabelValueSet
  langs:
  - csharp
  - vb
  name: Preferred
  nameWithType: LabelValueSet.Preferred
  fullName: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.Preferred
  type: Property
  source:
    path: Sdl.Core.Globalization
    isExternal: true
  assemblies:
  - Sdl.Core.Globalization
  namespace: Sdl.Core.Globalization.UnitMetadata
  syntax:
    content: public bool Preferred { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property Preferred As Boolean
  overload: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.Preferred*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.LabelValueConditions
  commentId: P:Sdl.Core.Globalization.UnitMetadata.LabelValueSet.LabelValueConditions
  id: LabelValueConditions
  parent: Sdl.Core.Globalization.UnitMetadata.LabelValueSet
  langs:
  - csharp
  - vb
  name: LabelValueConditions
  nameWithType: LabelValueSet.LabelValueConditions
  fullName: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.LabelValueConditions
  type: Property
  source:
    path: Sdl.Core.Globalization
    isExternal: true
  assemblies:
  - Sdl.Core.Globalization
  namespace: Sdl.Core.Globalization.UnitMetadata
  syntax:
    content: public List<LabelValueCondition> LabelValueConditions { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.List{Sdl.Core.Globalization.UnitMetadata.LabelValueCondition}
    content.vb: Public Property LabelValueConditions As List(Of LabelValueCondition)
  overload: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.LabelValueConditions*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Sdl.Core.Globalization.UnitMetadata
  commentId: N:Sdl.Core.Globalization.UnitMetadata
  isExternal: true
  name: Sdl.Core.Globalization.UnitMetadata
  nameWithType: Sdl.Core.Globalization.UnitMetadata
  fullName: Sdl.Core.Globalization.UnitMetadata
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.ContainsLabel*
  commentId: Overload:Sdl.Core.Globalization.UnitMetadata.LabelValueSet.ContainsLabel
  isExternal: true
  name: ContainsLabel
  nameWithType: LabelValueSet.ContainsLabel
  fullName: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.ContainsLabel
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.GetLabel*
  commentId: Overload:Sdl.Core.Globalization.UnitMetadata.LabelValueSet.GetLabel
  isExternal: true
  name: GetLabel
  nameWithType: LabelValueSet.GetLabel
  fullName: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.GetLabel
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Double
  commentId: T:System.Double
  parent: System
  isExternal: true
  name: Double
  nameWithType: Double
  fullName: System.Double
- uid: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.#ctor*
  commentId: Overload:Sdl.Core.Globalization.UnitMetadata.LabelValueSet.#ctor
  isExternal: true
  name: LabelValueSet
  nameWithType: LabelValueSet.LabelValueSet
  fullName: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.LabelValueSet
- uid: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.Preferred*
  commentId: Overload:Sdl.Core.Globalization.UnitMetadata.LabelValueSet.Preferred
  isExternal: true
  name: Preferred
  nameWithType: LabelValueSet.Preferred
  fullName: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.Preferred
- uid: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.LabelValueConditions*
  commentId: Overload:Sdl.Core.Globalization.UnitMetadata.LabelValueSet.LabelValueConditions
  isExternal: true
  name: LabelValueConditions
  nameWithType: LabelValueSet.LabelValueConditions
  fullName: Sdl.Core.Globalization.UnitMetadata.LabelValueSet.LabelValueConditions
- uid: System.Collections.Generic.List{Sdl.Core.Globalization.UnitMetadata.LabelValueCondition}
  commentId: T:System.Collections.Generic.List{Sdl.Core.Globalization.UnitMetadata.LabelValueCondition}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  name: List<LabelValueCondition>
  nameWithType: List<LabelValueCondition>
  fullName: System.Collections.Generic.List<Sdl.Core.Globalization.UnitMetadata.LabelValueCondition>
  nameWithType.vb: List(Of LabelValueCondition)
  fullName.vb: System.Collections.Generic.List(Of Sdl.Core.Globalization.UnitMetadata.LabelValueCondition)
  name.vb: List(Of LabelValueCondition)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Sdl.Core.Globalization.UnitMetadata.LabelValueCondition
    name: LabelValueCondition
    nameWithType: LabelValueCondition
    fullName: Sdl.Core.Globalization.UnitMetadata.LabelValueCondition
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Sdl.Core.Globalization.UnitMetadata.LabelValueCondition
    name: LabelValueCondition
    nameWithType: LabelValueCondition
    fullName: Sdl.Core.Globalization.UnitMetadata.LabelValueCondition
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
