### YamlMime:ManagedReference
items:
- uid: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings
  commentId: T:Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings
  id: ITrackChangesSettings
  parent: Sdl.TranslationStudio.Api.Editor
  children:
  - Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnableAutoCorrectWhenTrackChangesOn
  - Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForReview
  - Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForSignOff
  - Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForTranslation
  langs:
  - csharp
  - vb
  name: ITrackChangesSettings
  nameWithType: ITrackChangesSettings
  fullName: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings
  type: Interface
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  summary: "\nUser settings for the track changes functionality\n"
  syntax:
    content: 'public interface ITrackChangesSettings : ISettingsGroup, INotifyPropertyChanged, IEditableObject'
    content.vb: >-
      Public Interface ITrackChangesSettings
          Inherits ISettingsGroup, INotifyPropertyChanged, IEditableObject
  extensionMethods:
  - System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForTranslation
  commentId: P:Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForTranslation
  id: EnabledOpeningDocumentForTranslation
  parent: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings
  langs:
  - csharp
  - vb
  name: EnabledOpeningDocumentForTranslation
  nameWithType: ITrackChangesSettings.EnabledOpeningDocumentForTranslation
  fullName: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForTranslation
  type: Property
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  summary: "\nEnables or disables the Track Changes functionality when opening a document in translation mode\n"
  syntax:
    content: bool EnabledOpeningDocumentForTranslation { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property EnabledOpeningDocumentForTranslation As Boolean
  overload: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForTranslation*
  modifiers.csharp:
  - get
  - set
- uid: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForReview
  commentId: P:Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForReview
  id: EnabledOpeningDocumentForReview
  parent: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings
  langs:
  - csharp
  - vb
  name: EnabledOpeningDocumentForReview
  nameWithType: ITrackChangesSettings.EnabledOpeningDocumentForReview
  fullName: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForReview
  type: Property
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  summary: "\nEnables or disables the Track Changes functionality when opening a document in review mode\n"
  syntax:
    content: bool EnabledOpeningDocumentForReview { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property EnabledOpeningDocumentForReview As Boolean
  overload: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForReview*
  modifiers.csharp:
  - get
  - set
- uid: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForSignOff
  commentId: P:Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForSignOff
  id: EnabledOpeningDocumentForSignOff
  parent: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings
  langs:
  - csharp
  - vb
  name: EnabledOpeningDocumentForSignOff
  nameWithType: ITrackChangesSettings.EnabledOpeningDocumentForSignOff
  fullName: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForSignOff
  type: Property
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  summary: "\nEnables or disables the Track Changes functionality when opening a document in sign-off mode\n"
  syntax:
    content: bool EnabledOpeningDocumentForSignOff { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property EnabledOpeningDocumentForSignOff As Boolean
  overload: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForSignOff*
  modifiers.csharp:
  - get
  - set
- uid: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnableAutoCorrectWhenTrackChangesOn
  commentId: P:Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnableAutoCorrectWhenTrackChangesOn
  id: EnableAutoCorrectWhenTrackChangesOn
  parent: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings
  langs:
  - csharp
  - vb
  name: EnableAutoCorrectWhenTrackChangesOn
  nameWithType: ITrackChangesSettings.EnableAutoCorrectWhenTrackChangesOn
  fullName: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnableAutoCorrectWhenTrackChangesOn
  type: Property
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  summary: "\nEnables or disables AutoCorrect when Track Changes is active\n"
  syntax:
    content: bool EnableAutoCorrectWhenTrackChangesOn { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property EnableAutoCorrectWhenTrackChangesOn As Boolean
  overload: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnableAutoCorrectWhenTrackChangesOn*
  modifiers.csharp:
  - get
  - set
references:
- uid: Sdl.TranslationStudio.Api.Editor
  commentId: N:Sdl.TranslationStudio.Api.Editor
  isExternal: true
  name: Sdl.TranslationStudio.Api.Editor
  nameWithType: Sdl.TranslationStudio.Api.Editor
  fullName: Sdl.TranslationStudio.Api.Editor
- uid: System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  parent: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  definition: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  name: ForWindowFromFrameworkElement(Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  isExternal: true
  name: ForWindowFromFrameworkElement(Object, Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object, System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object, System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Object, Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  commentId: T:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  parent: Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  name: WindowsControlUtils
  nameWithType: WindowsControlUtils
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
- uid: Sdl.Desktop.Platform.Controls.Controls
  commentId: N:Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  name: Sdl.Desktop.Platform.Controls.Controls
  nameWithType: Sdl.Desktop.Platform.Controls.Controls
  fullName: Sdl.Desktop.Platform.Controls.Controls
- uid: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForTranslation*
  commentId: Overload:Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForTranslation
  isExternal: true
  name: EnabledOpeningDocumentForTranslation
  nameWithType: ITrackChangesSettings.EnabledOpeningDocumentForTranslation
  fullName: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForTranslation
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForReview*
  commentId: Overload:Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForReview
  isExternal: true
  name: EnabledOpeningDocumentForReview
  nameWithType: ITrackChangesSettings.EnabledOpeningDocumentForReview
  fullName: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForReview
- uid: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForSignOff*
  commentId: Overload:Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForSignOff
  isExternal: true
  name: EnabledOpeningDocumentForSignOff
  nameWithType: ITrackChangesSettings.EnabledOpeningDocumentForSignOff
  fullName: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnabledOpeningDocumentForSignOff
- uid: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnableAutoCorrectWhenTrackChangesOn*
  commentId: Overload:Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnableAutoCorrectWhenTrackChangesOn
  isExternal: true
  name: EnableAutoCorrectWhenTrackChangesOn
  nameWithType: ITrackChangesSettings.EnableAutoCorrectWhenTrackChangesOn
  fullName: Sdl.TranslationStudio.Api.Editor.ITrackChangesSettings.EnableAutoCorrectWhenTrackChangesOn
