### YamlMime:ManagedReference
items:
- uid: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings
  commentId: T:Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings
  id: ITranslationMemoryWindowSettings
  parent: Sdl.TranslationStudio.Api.Editor
  children:
  - Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.DisplayMode
  - Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowDocumentSourceSegment
  - Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowDocumentSourceSegmentEditDistance
  - Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowTranslationMemorySourceSegmentEditDistance
  langs:
  - csharp
  - vb
  name: ITranslationMemoryWindowSettings
  nameWithType: ITranslationMemoryWindowSettings
  fullName: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings
  type: Interface
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  syntax:
    content: 'public interface ITranslationMemoryWindowSettings : ITranslationMemorySearchResultsPreferences, ISettingsGroup, INotifyPropertyChanged, IEditableObject'
    content.vb: >-
      Public Interface ITranslationMemoryWindowSettings
          Inherits ITranslationMemorySearchResultsPreferences, ISettingsGroup, INotifyPropertyChanged, IEditableObject
  inheritedMembers:
  - Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences.ShowFieldValues
  - Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences.NumberOfFieldValuesToDisplay
  - Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences.TagDisplayMode
  - Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences.ShowWhitespaceCharacters
  extensionMethods:
  - System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowDocumentSourceSegment
  commentId: P:Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowDocumentSourceSegment
  id: ShowDocumentSourceSegment
  parent: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings
  langs:
  - csharp
  - vb
  name: ShowDocumentSourceSegment
  nameWithType: ITranslationMemoryWindowSettings.ShowDocumentSourceSegment
  fullName: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowDocumentSourceSegment
  type: Property
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  syntax:
    content: bool ShowDocumentSourceSegment { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property ShowDocumentSourceSegment As Boolean
  overload: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowDocumentSourceSegment*
  modifiers.csharp:
  - get
  - set
- uid: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowDocumentSourceSegmentEditDistance
  commentId: P:Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowDocumentSourceSegmentEditDistance
  id: ShowDocumentSourceSegmentEditDistance
  parent: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings
  langs:
  - csharp
  - vb
  name: ShowDocumentSourceSegmentEditDistance
  nameWithType: ITranslationMemoryWindowSettings.ShowDocumentSourceSegmentEditDistance
  fullName: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowDocumentSourceSegmentEditDistance
  type: Property
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  syntax:
    content: bool ShowDocumentSourceSegmentEditDistance { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property ShowDocumentSourceSegmentEditDistance As Boolean
  overload: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowDocumentSourceSegmentEditDistance*
  modifiers.csharp:
  - get
  - set
- uid: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowTranslationMemorySourceSegmentEditDistance
  commentId: P:Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowTranslationMemorySourceSegmentEditDistance
  id: ShowTranslationMemorySourceSegmentEditDistance
  parent: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings
  langs:
  - csharp
  - vb
  name: ShowTranslationMemorySourceSegmentEditDistance
  nameWithType: ITranslationMemoryWindowSettings.ShowTranslationMemorySourceSegmentEditDistance
  fullName: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowTranslationMemorySourceSegmentEditDistance
  type: Property
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  syntax:
    content: bool ShowTranslationMemorySourceSegmentEditDistance { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property ShowTranslationMemorySourceSegmentEditDistance As Boolean
  overload: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowTranslationMemorySourceSegmentEditDistance*
  modifiers.csharp:
  - get
  - set
- uid: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.DisplayMode
  commentId: P:Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.DisplayMode
  id: DisplayMode
  parent: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings
  langs:
  - csharp
  - vb
  name: DisplayMode
  nameWithType: ITranslationMemoryWindowSettings.DisplayMode
  fullName: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.DisplayMode
  type: Property
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  syntax:
    content: TranslationMemorySearchResultDisplayMode DisplayMode { get; set; }
    parameters: []
    return:
      type: Sdl.TranslationStudio.Api.Common.TranslationMemorySearchResultDisplayMode
    content.vb: Property DisplayMode As TranslationMemorySearchResultDisplayMode
  overload: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.DisplayMode*
  modifiers.csharp:
  - get
  - set
references:
- uid: Sdl.TranslationStudio.Api.Editor
  commentId: N:Sdl.TranslationStudio.Api.Editor
  isExternal: true
  name: Sdl.TranslationStudio.Api.Editor
  nameWithType: Sdl.TranslationStudio.Api.Editor
  fullName: Sdl.TranslationStudio.Api.Editor
- uid: Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences.ShowFieldValues
  commentId: P:Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences.ShowFieldValues
  parent: Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences
  isExternal: true
  name: ShowFieldValues
  nameWithType: ITranslationMemorySearchResultsPreferences.ShowFieldValues
  fullName: Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences.ShowFieldValues
- uid: Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences.NumberOfFieldValuesToDisplay
  commentId: P:Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences.NumberOfFieldValuesToDisplay
  parent: Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences
  isExternal: true
  name: NumberOfFieldValuesToDisplay
  nameWithType: ITranslationMemorySearchResultsPreferences.NumberOfFieldValuesToDisplay
  fullName: Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences.NumberOfFieldValuesToDisplay
- uid: Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences.TagDisplayMode
  commentId: P:Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences.TagDisplayMode
  parent: Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences
  isExternal: true
  name: TagDisplayMode
  nameWithType: ITranslationMemorySearchResultsPreferences.TagDisplayMode
  fullName: Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences.TagDisplayMode
- uid: Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences.ShowWhitespaceCharacters
  commentId: P:Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences.ShowWhitespaceCharacters
  parent: Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences
  isExternal: true
  name: ShowWhitespaceCharacters
  nameWithType: ITranslationMemorySearchResultsPreferences.ShowWhitespaceCharacters
  fullName: Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences.ShowWhitespaceCharacters
- uid: System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  parent: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  definition: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  name: ForWindowFromFrameworkElement(Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences
  commentId: T:Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences
  parent: Sdl.TranslationStudio.Api.Editor
  isExternal: true
  name: ITranslationMemorySearchResultsPreferences
  nameWithType: ITranslationMemorySearchResultsPreferences
  fullName: Sdl.TranslationStudio.Api.Editor.ITranslationMemorySearchResultsPreferences
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  isExternal: true
  name: ForWindowFromFrameworkElement(Object, Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object, System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object, System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Object, Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  commentId: T:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  parent: Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  name: WindowsControlUtils
  nameWithType: WindowsControlUtils
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
- uid: Sdl.Desktop.Platform.Controls.Controls
  commentId: N:Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  name: Sdl.Desktop.Platform.Controls.Controls
  nameWithType: Sdl.Desktop.Platform.Controls.Controls
  fullName: Sdl.Desktop.Platform.Controls.Controls
- uid: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowDocumentSourceSegment*
  commentId: Overload:Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowDocumentSourceSegment
  isExternal: true
  name: ShowDocumentSourceSegment
  nameWithType: ITranslationMemoryWindowSettings.ShowDocumentSourceSegment
  fullName: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowDocumentSourceSegment
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowDocumentSourceSegmentEditDistance*
  commentId: Overload:Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowDocumentSourceSegmentEditDistance
  isExternal: true
  name: ShowDocumentSourceSegmentEditDistance
  nameWithType: ITranslationMemoryWindowSettings.ShowDocumentSourceSegmentEditDistance
  fullName: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowDocumentSourceSegmentEditDistance
- uid: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowTranslationMemorySourceSegmentEditDistance*
  commentId: Overload:Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowTranslationMemorySourceSegmentEditDistance
  isExternal: true
  name: ShowTranslationMemorySourceSegmentEditDistance
  nameWithType: ITranslationMemoryWindowSettings.ShowTranslationMemorySourceSegmentEditDistance
  fullName: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.ShowTranslationMemorySourceSegmentEditDistance
- uid: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.DisplayMode*
  commentId: Overload:Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.DisplayMode
  isExternal: true
  name: DisplayMode
  nameWithType: ITranslationMemoryWindowSettings.DisplayMode
  fullName: Sdl.TranslationStudio.Api.Editor.ITranslationMemoryWindowSettings.DisplayMode
- uid: Sdl.TranslationStudio.Api.Common.TranslationMemorySearchResultDisplayMode
  commentId: T:Sdl.TranslationStudio.Api.Common.TranslationMemorySearchResultDisplayMode
  parent: Sdl.TranslationStudio.Api.Common
  isExternal: true
  name: TranslationMemorySearchResultDisplayMode
  nameWithType: TranslationMemorySearchResultDisplayMode
  fullName: Sdl.TranslationStudio.Api.Common.TranslationMemorySearchResultDisplayMode
- uid: Sdl.TranslationStudio.Api.Common
  commentId: N:Sdl.TranslationStudio.Api.Common
  isExternal: true
  name: Sdl.TranslationStudio.Api.Common
  nameWithType: Sdl.TranslationStudio.Api.Common
  fullName: Sdl.TranslationStudio.Api.Common
