### YamlMime:ManagedReference
items:
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
  id: ImportSettings.FieldUpdateMode
  parent: Sdl.LanguagePlatform.TranslationMemory
  children:
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.LeaveUnchanged
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.Merge
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.Overwrite
  langs:
  - csharp
  - vb
  name: ImportSettings.FieldUpdateMode
  nameWithType: ImportSettings.FieldUpdateMode
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
  type: Enum
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: public enum FieldUpdateMode
    content.vb: Public Enum FieldUpdateMode
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.Merge
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.Merge
  id: Merge
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
  langs:
  - csharp
  - vb
  name: Merge
  nameWithType: ImportSettings.FieldUpdateMode.Merge
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.Merge
  type: Field
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: Merge = 0
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.Overwrite
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.Overwrite
  id: Overwrite
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
  langs:
  - csharp
  - vb
  name: Overwrite
  nameWithType: ImportSettings.FieldUpdateMode.Overwrite
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.Overwrite
  type: Field
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: Overwrite = 1
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.LeaveUnchanged
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.LeaveUnchanged
  id: LeaveUnchanged
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
  langs:
  - csharp
  - vb
  name: LeaveUnchanged
  nameWithType: ImportSettings.FieldUpdateMode.LeaveUnchanged
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.LeaveUnchanged
  type: Field
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: LeaveUnchanged = 2
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Sdl.LanguagePlatform.TranslationMemory
  commentId: N:Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  name: Sdl.LanguagePlatform.TranslationMemory
  nameWithType: Sdl.LanguagePlatform.TranslationMemory
  fullName: Sdl.LanguagePlatform.TranslationMemory
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
  parent: Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  name: ImportSettings.FieldUpdateMode
  nameWithType: ImportSettings.FieldUpdateMode
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
