### YamlMime:ManagedReference
items:
- uid: Sdl.Desktop.IntegrationApi.IApplicationInitializer
  commentId: T:Sdl.Desktop.IntegrationApi.IApplicationInitializer
  id: IApplicationInitializer
  parent: Sdl.Desktop.IntegrationApi
  children:
  - Sdl.Desktop.IntegrationApi.IApplicationInitializer.Execute
  langs:
  - csharp
  - vb
  name: IApplicationInitializer
  nameWithType: IApplicationInitializer
  fullName: Sdl.Desktop.IntegrationApi.IApplicationInitializer
  type: Interface
  source:
    path: Sdl.Desktop.IntegrationApi
    isExternal: true
  assemblies:
  - Sdl.Desktop.IntegrationApi
  namespace: Sdl.Desktop.IntegrationApi
  summary: "\nContract defining the application initializer which is executed at the application startup. \nApplication initializers which implement this interface must be decorated with the <xref href=\"Sdl.Desktop.IntegrationApi.Extensions.ApplicationInitializerAttribute\" data-throw-if-not-resolved=\"false\"></xref> attribute.\n"
  example:
  - <a href="6bbfdddf-235e-411b-b097-adefe629ff71.htm">Application Initializer Sample</a>
  syntax:
    content: public interface IApplicationInitializer
    content.vb: Public Interface IApplicationInitializer
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.Desktop.IntegrationApi.IApplicationInitializer.Execute
  commentId: M:Sdl.Desktop.IntegrationApi.IApplicationInitializer.Execute
  id: Execute
  parent: Sdl.Desktop.IntegrationApi.IApplicationInitializer
  langs:
  - csharp
  - vb
  name: Execute()
  nameWithType: IApplicationInitializer.Execute()
  fullName: Sdl.Desktop.IntegrationApi.IApplicationInitializer.Execute()
  type: Method
  source:
    path: Sdl.Desktop.IntegrationApi
    isExternal: true
  assemblies:
  - Sdl.Desktop.IntegrationApi
  namespace: Sdl.Desktop.IntegrationApi
  summary: "\nIt is executed at the application startup and implements the initializer logic\n"
  example:
  - <a href="6bbfdddf-235e-411b-b097-adefe629ff71.htm">Application Initializer Sample</a>
  syntax:
    content: void Execute()
    content.vb: Sub Execute
  overload: Sdl.Desktop.IntegrationApi.IApplicationInitializer.Execute*
references:
- uid: Sdl.Desktop.IntegrationApi
  commentId: N:Sdl.Desktop.IntegrationApi
  isExternal: true
  name: Sdl.Desktop.IntegrationApi
  nameWithType: Sdl.Desktop.IntegrationApi
  fullName: Sdl.Desktop.IntegrationApi
- uid: Sdl.Desktop.IntegrationApi.IApplicationInitializer.Execute*
  commentId: Overload:Sdl.Desktop.IntegrationApi.IApplicationInitializer.Execute
  isExternal: true
  name: Execute
  nameWithType: IApplicationInitializer.Execute
  fullName: Sdl.Desktop.IntegrationApi.IApplicationInitializer.Execute
