### YamlMime:ManagedReference
items:
- uid: Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl
  commentId: T:Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl
  id: IUISettingsControl
  parent: Sdl.Desktop.IntegrationApi.Interfaces
  children:
  - Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl.ValidateChildren
  langs:
  - csharp
  - vb
  name: IUISettingsControl
  nameWithType: IUISettingsControl
  fullName: Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl
  type: Interface
  source:
    path: Sdl.Desktop.IntegrationApi
    isExternal: true
  assemblies:
  - Sdl.Desktop.IntegrationApi
  namespace: Sdl.Desktop.IntegrationApi.Interfaces
  syntax:
    content: 'public interface IUISettingsControl : IUIControl, IDisposable'
    content.vb: >-
      Public Interface IUISettingsControl
          Inherits IUIControl, IDisposable
  inheritedMembers:
  - System.IDisposable.Dispose
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl.ValidateChildren
  commentId: M:Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl.ValidateChildren
  id: ValidateChildren
  parent: Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl
  langs:
  - csharp
  - vb
  name: ValidateChildren()
  nameWithType: IUISettingsControl.ValidateChildren()
  fullName: Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl.ValidateChildren()
  type: Method
  source:
    path: Sdl.Desktop.IntegrationApi
    isExternal: true
  assemblies:
  - Sdl.Desktop.IntegrationApi
  namespace: Sdl.Desktop.IntegrationApi.Interfaces
  syntax:
    content: bool ValidateChildren()
    return:
      type: System.Boolean
    content.vb: Function ValidateChildren As Boolean
  overload: Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl.ValidateChildren*
references:
- uid: Sdl.Desktop.IntegrationApi.Interfaces
  commentId: N:Sdl.Desktop.IntegrationApi.Interfaces
  isExternal: true
  name: Sdl.Desktop.IntegrationApi.Interfaces
  nameWithType: Sdl.Desktop.IntegrationApi.Interfaces
  fullName: Sdl.Desktop.IntegrationApi.Interfaces
- uid: System.IDisposable.Dispose
  commentId: M:System.IDisposable.Dispose
  parent: System.IDisposable
  isExternal: true
  name: Dispose()
  nameWithType: IDisposable.Dispose()
  fullName: System.IDisposable.Dispose()
  spec.csharp:
  - uid: System.IDisposable.Dispose
    name: Dispose
    nameWithType: IDisposable.Dispose
    fullName: System.IDisposable.Dispose
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.IDisposable.Dispose
    name: Dispose
    nameWithType: IDisposable.Dispose
    fullName: System.IDisposable.Dispose
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.IDisposable
  commentId: T:System.IDisposable
  parent: System
  isExternal: true
  name: IDisposable
  nameWithType: IDisposable
  fullName: System.IDisposable
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl.ValidateChildren*
  commentId: Overload:Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl.ValidateChildren
  isExternal: true
  name: ValidateChildren
  nameWithType: IUISettingsControl.ValidateChildren
  fullName: Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl.ValidateChildren
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
