### YamlMime:ManagedReference
items:
- uid: Sdl.Desktop.IntegrationApi.IApplicationInitializer
  commentId: T:Sdl.Desktop.IntegrationApi.IApplicationInitializer
  id: IApplicationInitializer
  parent: Sdl.Desktop.IntegrationApi
  children:
  - Sdl.Desktop.IntegrationApi.IApplicationInitializer.Execute
  langs:
  - csharp
  - vb
  name: IApplicationInitializer
  nameWithType: IApplicationInitializer
  fullName: Sdl.Desktop.IntegrationApi.IApplicationInitializer
  type: Interface
  assemblies:
  - Sdl.Desktop.IntegrationApi
  namespace: Sdl.Desktop.IntegrationApi
  summary: >-
    Contract defining the application initializer which is executed at the application startup. 

    Application initializers which implement this interface must be decorated with the <xref href="Sdl.Desktop.IntegrationApi.Extensions.ApplicationInitializerAttribute" data-throw-if-not-resolved="false"></xref> attribute.
  example:
  - <a href="6bbfdddf-235e-411b-b097-adefe629ff71.htm">Application Initializer Sample</a>
  syntax:
    content: public interface IApplicationInitializer
    content.vb: Public Interface IApplicationInitializer
  extensionMethods:
  - System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
- uid: Sdl.Desktop.IntegrationApi.IApplicationInitializer.Execute
  commentId: M:Sdl.Desktop.IntegrationApi.IApplicationInitializer.Execute
  id: Execute
  parent: Sdl.Desktop.IntegrationApi.IApplicationInitializer
  langs:
  - csharp
  - vb
  name: Execute()
  nameWithType: IApplicationInitializer.Execute()
  fullName: Sdl.Desktop.IntegrationApi.IApplicationInitializer.Execute()
  type: Method
  assemblies:
  - Sdl.Desktop.IntegrationApi
  namespace: Sdl.Desktop.IntegrationApi
  summary: It is executed at the application startup and implements the initializer logic
  example:
  - <a href="6bbfdddf-235e-411b-b097-adefe629ff71.htm">Application Initializer Sample</a>
  syntax:
    content: void Execute()
    content.vb: Sub Execute()
  overload: Sdl.Desktop.IntegrationApi.IApplicationInitializer.Execute*
references:
- uid: Sdl.Desktop.IntegrationApi.Extensions.ApplicationInitializerAttribute
  commentId: T:Sdl.Desktop.IntegrationApi.Extensions.ApplicationInitializerAttribute
  isExternal: true
  href: Sdl.Desktop.IntegrationApi.Extensions.ApplicationInitializerAttribute.html
  name: ApplicationInitializerAttribute
  nameWithType: ApplicationInitializerAttribute
  fullName: Sdl.Desktop.IntegrationApi.Extensions.ApplicationInitializerAttribute
- uid: Sdl.Desktop.IntegrationApi
  commentId: N:Sdl.Desktop.IntegrationApi
  isExternal: true
  href: Sdl.html
  name: Sdl.Desktop.IntegrationApi
  nameWithType: Sdl.Desktop.IntegrationApi
  fullName: Sdl.Desktop.IntegrationApi
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Desktop
    name: Desktop
    isExternal: true
    href: Sdl.Desktop.html
  - name: .
  - uid: Sdl.Desktop.IntegrationApi
    name: IntegrationApi
    isExternal: true
    href: Sdl.Desktop.IntegrationApi.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Desktop
    name: Desktop
    isExternal: true
    href: Sdl.Desktop.html
  - name: .
  - uid: Sdl.Desktop.IntegrationApi
    name: IntegrationApi
    isExternal: true
    href: Sdl.Desktop.IntegrationApi.html
- uid: System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  parent: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  definition: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  href: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.html#Sdl_Desktop_Platform_Controls_Controls_WindowsControlUtils_ForWindowFromFrameworkElement_System_Object_System_Action_System_Windows_Window__
  name: ForWindowFromFrameworkElement(object, Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(object, Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(object, System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(Object, System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Object, Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    isExternal: true
    href: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.html#Sdl_Desktop_Platform_Controls_Controls_WindowsControlUtils_ForWindowFromFrameworkElement_System_Object_System_Action_System_Windows_Window__
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: <
  - uid: System.Windows.Window
    name: Window
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows.window
  - name: '>'
  - name: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    isExternal: true
    href: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.html#Sdl_Desktop_Platform_Controls_Controls_WindowsControlUtils_ForWindowFromFrameworkElement_System_Object_System_Action_System_Windows_Window__
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.Windows.Window
    name: Window
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows.window
  - name: )
  - name: )
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  isExternal: true
  href: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.html#Sdl_Desktop_Platform_Controls_Controls_WindowsControlUtils_ForWindowFromFrameworkElement_System_Object_System_Action_System_Windows_Window__
  name: ForWindowFromFrameworkElement(object, Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(object, Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(object, System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(Object, System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Object, Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    isExternal: true
    href: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.html#Sdl_Desktop_Platform_Controls_Controls_WindowsControlUtils_ForWindowFromFrameworkElement_System_Object_System_Action_System_Windows_Window__
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: <
  - uid: System.Windows.Window
    name: Window
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows.window
  - name: '>'
  - name: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    isExternal: true
    href: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.html#Sdl_Desktop_Platform_Controls_Controls_WindowsControlUtils_ForWindowFromFrameworkElement_System_Object_System_Action_System_Windows_Window__
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.Windows.Window
    name: Window
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows.window
  - name: )
  - name: )
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  commentId: T:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  parent: Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  href: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.html
  name: WindowsControlUtils
  nameWithType: WindowsControlUtils
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
- uid: Sdl.Desktop.Platform.Controls.Controls
  commentId: N:Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  href: Sdl.html
  name: Sdl.Desktop.Platform.Controls.Controls
  nameWithType: Sdl.Desktop.Platform.Controls.Controls
  fullName: Sdl.Desktop.Platform.Controls.Controls
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Desktop
    name: Desktop
    isExternal: true
    href: Sdl.Desktop.html
  - name: .
  - uid: Sdl.Desktop.Platform
    name: Platform
    isExternal: true
    href: Sdl.Desktop.Platform.html
  - name: .
  - uid: Sdl.Desktop.Platform.Controls
    name: Controls
    isExternal: true
    href: Sdl.Desktop.Platform.Controls.html
  - name: .
  - uid: Sdl.Desktop.Platform.Controls.Controls
    name: Controls
    isExternal: true
    href: Sdl.Desktop.Platform.Controls.Controls.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Desktop
    name: Desktop
    isExternal: true
    href: Sdl.Desktop.html
  - name: .
  - uid: Sdl.Desktop.Platform
    name: Platform
    isExternal: true
    href: Sdl.Desktop.Platform.html
  - name: .
  - uid: Sdl.Desktop.Platform.Controls
    name: Controls
    isExternal: true
    href: Sdl.Desktop.Platform.Controls.html
  - name: .
  - uid: Sdl.Desktop.Platform.Controls.Controls
    name: Controls
    isExternal: true
    href: Sdl.Desktop.Platform.Controls.Controls.html
- uid: Sdl.Desktop.IntegrationApi.IApplicationInitializer.Execute*
  commentId: Overload:Sdl.Desktop.IntegrationApi.IApplicationInitializer.Execute
  isExternal: true
  href: Sdl.Desktop.IntegrationApi.IApplicationInitializer.html#Sdl_Desktop_IntegrationApi_IApplicationInitializer_Execute
  name: Execute
  nameWithType: IApplicationInitializer.Execute
  fullName: Sdl.Desktop.IntegrationApi.IApplicationInitializer.Execute
