### YamlMime:ManagedReference
items:
- uid: Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl
  commentId: T:Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl
  id: IUISettingsControl
  parent: Sdl.Desktop.IntegrationApi.Interfaces
  children:
  - Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl.ValidateChildren
  langs:
  - csharp
  - vb
  name: IUISettingsControl
  nameWithType: IUISettingsControl
  fullName: Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl
  type: Interface
  assemblies:
  - Sdl.Desktop.IntegrationApi
  namespace: Sdl.Desktop.IntegrationApi.Interfaces
  syntax:
    content: 'public interface IUISettingsControl : IUIControl, IDisposable'
    content.vb: Public Interface IUISettingsControl Inherits IUIControl, IDisposable
  inheritedMembers:
  - System.IDisposable.Dispose
  extensionMethods:
  - System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
- uid: Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl.ValidateChildren
  commentId: M:Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl.ValidateChildren
  id: ValidateChildren
  parent: Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl
  langs:
  - csharp
  - vb
  name: ValidateChildren()
  nameWithType: IUISettingsControl.ValidateChildren()
  fullName: Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl.ValidateChildren()
  type: Method
  assemblies:
  - Sdl.Desktop.IntegrationApi
  namespace: Sdl.Desktop.IntegrationApi.Interfaces
  syntax:
    content: bool ValidateChildren()
    return:
      type: System.Boolean
    content.vb: Function ValidateChildren() As Boolean
  overload: Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl.ValidateChildren*
references:
- uid: Sdl.Desktop.IntegrationApi.Interfaces
  commentId: N:Sdl.Desktop.IntegrationApi.Interfaces
  isExternal: true
  href: Sdl.html
  name: Sdl.Desktop.IntegrationApi.Interfaces
  nameWithType: Sdl.Desktop.IntegrationApi.Interfaces
  fullName: Sdl.Desktop.IntegrationApi.Interfaces
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Desktop
    name: Desktop
    isExternal: true
    href: Sdl.Desktop.html
  - name: .
  - uid: Sdl.Desktop.IntegrationApi
    name: IntegrationApi
    isExternal: true
    href: Sdl.Desktop.IntegrationApi.html
  - name: .
  - uid: Sdl.Desktop.IntegrationApi.Interfaces
    name: Interfaces
    isExternal: true
    href: Sdl.Desktop.IntegrationApi.Interfaces.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Desktop
    name: Desktop
    isExternal: true
    href: Sdl.Desktop.html
  - name: .
  - uid: Sdl.Desktop.IntegrationApi
    name: IntegrationApi
    isExternal: true
    href: Sdl.Desktop.IntegrationApi.html
  - name: .
  - uid: Sdl.Desktop.IntegrationApi.Interfaces
    name: Interfaces
    isExternal: true
    href: Sdl.Desktop.IntegrationApi.Interfaces.html
- uid: System.IDisposable.Dispose
  commentId: M:System.IDisposable.Dispose
  parent: System.IDisposable
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  name: Dispose()
  nameWithType: IDisposable.Dispose()
  fullName: System.IDisposable.Dispose()
  spec.csharp:
  - uid: System.IDisposable.Dispose
    name: Dispose
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  - name: (
  - name: )
  spec.vb:
  - uid: System.IDisposable.Dispose
    name: Dispose
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  - name: (
  - name: )
- uid: System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  parent: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  definition: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  href: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.html#Sdl_Desktop_Platform_Controls_Controls_WindowsControlUtils_ForWindowFromFrameworkElement_System_Object_System_Action_System_Windows_Window__
  name: ForWindowFromFrameworkElement(object, Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(object, Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(object, System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(Object, System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Object, Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    isExternal: true
    href: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.html#Sdl_Desktop_Platform_Controls_Controls_WindowsControlUtils_ForWindowFromFrameworkElement_System_Object_System_Action_System_Windows_Window__
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: <
  - uid: System.Windows.Window
    name: Window
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows.window
  - name: '>'
  - name: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    isExternal: true
    href: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.html#Sdl_Desktop_Platform_Controls_Controls_WindowsControlUtils_ForWindowFromFrameworkElement_System_Object_System_Action_System_Windows_Window__
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.Windows.Window
    name: Window
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows.window
  - name: )
  - name: )
- uid: System.IDisposable
  commentId: T:System.IDisposable
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.idisposable
  name: IDisposable
  nameWithType: IDisposable
  fullName: System.IDisposable
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  isExternal: true
  href: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.html#Sdl_Desktop_Platform_Controls_Controls_WindowsControlUtils_ForWindowFromFrameworkElement_System_Object_System_Action_System_Windows_Window__
  name: ForWindowFromFrameworkElement(object, Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(object, Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(object, System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(Object, System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Object, Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    isExternal: true
    href: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.html#Sdl_Desktop_Platform_Controls_Controls_WindowsControlUtils_ForWindowFromFrameworkElement_System_Object_System_Action_System_Windows_Window__
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: <
  - uid: System.Windows.Window
    name: Window
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows.window
  - name: '>'
  - name: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    isExternal: true
    href: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.html#Sdl_Desktop_Platform_Controls_Controls_WindowsControlUtils_ForWindowFromFrameworkElement_System_Object_System_Action_System_Windows_Window__
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.Windows.Window
    name: Window
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows.window
  - name: )
  - name: )
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  commentId: T:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  parent: Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  href: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.html
  name: WindowsControlUtils
  nameWithType: WindowsControlUtils
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.Desktop.Platform.Controls.Controls
  commentId: N:Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  href: Sdl.html
  name: Sdl.Desktop.Platform.Controls.Controls
  nameWithType: Sdl.Desktop.Platform.Controls.Controls
  fullName: Sdl.Desktop.Platform.Controls.Controls
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Desktop
    name: Desktop
    isExternal: true
    href: Sdl.Desktop.html
  - name: .
  - uid: Sdl.Desktop.Platform
    name: Platform
    isExternal: true
    href: Sdl.Desktop.Platform.html
  - name: .
  - uid: Sdl.Desktop.Platform.Controls
    name: Controls
    isExternal: true
    href: Sdl.Desktop.Platform.Controls.html
  - name: .
  - uid: Sdl.Desktop.Platform.Controls.Controls
    name: Controls
    isExternal: true
    href: Sdl.Desktop.Platform.Controls.Controls.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Desktop
    name: Desktop
    isExternal: true
    href: Sdl.Desktop.html
  - name: .
  - uid: Sdl.Desktop.Platform
    name: Platform
    isExternal: true
    href: Sdl.Desktop.Platform.html
  - name: .
  - uid: Sdl.Desktop.Platform.Controls
    name: Controls
    isExternal: true
    href: Sdl.Desktop.Platform.Controls.html
  - name: .
  - uid: Sdl.Desktop.Platform.Controls.Controls
    name: Controls
    isExternal: true
    href: Sdl.Desktop.Platform.Controls.Controls.html
- uid: Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl.ValidateChildren*
  commentId: Overload:Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl.ValidateChildren
  isExternal: true
  href: Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl.html#Sdl_Desktop_IntegrationApi_Interfaces_IUISettingsControl_ValidateChildren
  name: ValidateChildren
  nameWithType: IUISettingsControl.ValidateChildren
  fullName: Sdl.Desktop.IntegrationApi.Interfaces.IUISettingsControl.ValidateChildren
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
