### YamlMime:ManagedReference
items:
- uid: Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration
  commentId: T:Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration
  id: IImeIntellisenseBehaviorConfiguration
  parent: Sdl.TranslationStudio.Api.Editor
  children:
  - Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration.IntellisenseBehavior
  - Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration.OnPropertyChanged(System.EventArgs)
  - Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration.PropertiesChanged
  langs:
  - csharp
  - vb
  name: IImeIntellisenseBehaviorConfiguration
  nameWithType: IImeIntellisenseBehaviorConfiguration
  fullName: Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration
  type: Interface
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  syntax:
    content: public interface IImeIntellisenseBehaviorConfiguration
    content.vb: Public Interface IImeIntellisenseBehaviorConfiguration
  extensionMethods:
  - System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration.OnPropertyChanged(System.EventArgs)
  commentId: M:Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration.OnPropertyChanged(System.EventArgs)
  id: OnPropertyChanged(System.EventArgs)
  parent: Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration
  langs:
  - csharp
  - vb
  name: OnPropertyChanged(EventArgs)
  nameWithType: IImeIntellisenseBehaviorConfiguration.OnPropertyChanged(EventArgs)
  fullName: Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration.OnPropertyChanged(System.EventArgs)
  type: Method
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  syntax:
    content: void OnPropertyChanged(EventArgs e)
    parameters:
    - id: e
      type: System.EventArgs
    content.vb: Sub OnPropertyChanged(e As EventArgs)
  overload: Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration.OnPropertyChanged*
- uid: Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration.IntellisenseBehavior
  commentId: P:Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration.IntellisenseBehavior
  id: IntellisenseBehavior
  parent: Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration
  langs:
  - csharp
  - vb
  name: IntellisenseBehavior
  nameWithType: IImeIntellisenseBehaviorConfiguration.IntellisenseBehavior
  fullName: Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration.IntellisenseBehavior
  type: Property
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  syntax:
    content: int IntellisenseBehavior { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Property IntellisenseBehavior As Integer
  overload: Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration.IntellisenseBehavior*
  modifiers.csharp:
  - get
  - set
- uid: Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration.PropertiesChanged
  commentId: E:Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration.PropertiesChanged
  id: PropertiesChanged
  parent: Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration
  langs:
  - csharp
  - vb
  name: PropertiesChanged
  nameWithType: IImeIntellisenseBehaviorConfiguration.PropertiesChanged
  fullName: Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration.PropertiesChanged
  type: Event
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.Editor
  syntax:
    content: event EventHandler PropertiesChanged
    return:
      type: System.EventHandler
    content.vb: Event PropertiesChanged As EventHandler
references:
- uid: Sdl.TranslationStudio.Api.Editor
  commentId: N:Sdl.TranslationStudio.Api.Editor
  isExternal: true
  name: Sdl.TranslationStudio.Api.Editor
  nameWithType: Sdl.TranslationStudio.Api.Editor
  fullName: Sdl.TranslationStudio.Api.Editor
- uid: System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  parent: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  definition: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  name: ForWindowFromFrameworkElement(Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  isExternal: true
  name: ForWindowFromFrameworkElement(Object, Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object, System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object, System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Object, Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  commentId: T:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  parent: Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  name: WindowsControlUtils
  nameWithType: WindowsControlUtils
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
- uid: Sdl.Desktop.Platform.Controls.Controls
  commentId: N:Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  name: Sdl.Desktop.Platform.Controls.Controls
  nameWithType: Sdl.Desktop.Platform.Controls.Controls
  fullName: Sdl.Desktop.Platform.Controls.Controls
- uid: Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration.OnPropertyChanged*
  commentId: Overload:Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration.OnPropertyChanged
  isExternal: true
  name: OnPropertyChanged
  nameWithType: IImeIntellisenseBehaviorConfiguration.OnPropertyChanged
  fullName: Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration.OnPropertyChanged
- uid: System.EventArgs
  commentId: T:System.EventArgs
  parent: System
  isExternal: true
  name: EventArgs
  nameWithType: EventArgs
  fullName: System.EventArgs
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration.IntellisenseBehavior*
  commentId: Overload:Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration.IntellisenseBehavior
  isExternal: true
  name: IntellisenseBehavior
  nameWithType: IImeIntellisenseBehaviorConfiguration.IntellisenseBehavior
  fullName: Sdl.TranslationStudio.Api.Editor.IImeIntellisenseBehaviorConfiguration.IntellisenseBehavior
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.EventHandler
  commentId: T:System.EventHandler
  parent: System
  isExternal: true
  name: EventHandler
  nameWithType: EventHandler
  fullName: System.EventHandler
