### YamlMime:ManagedReference
items:
- uid: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder
  commentId: T:Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder
  id: IProjectSettingsDialogBuilder
  parent: Sdl.TranslationStudio.Api.ProjectManagement
  children:
  - Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsDialog(Sdl.ProjectApi.IProject)
  - Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsDialog(Sdl.ProjectApi.IProject,Sdl.Desktop.Platform.Settings.ISettingsUIFilter)
  - Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsFileTypesDialog(Sdl.ProjectApi.IProject)
  - Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectTemplateSettingsDialog(Sdl.ProjectApi.IProjectTemplate)
  - Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateTranslatableFileSettingsDialog(Sdl.ProjectApi.ITranslatableFile)
  langs:
  - csharp
  - vb
  name: IProjectSettingsDialogBuilder
  nameWithType: IProjectSettingsDialogBuilder
  fullName: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder
  type: Interface
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.ProjectManagement
  syntax:
    content: public interface IProjectSettingsDialogBuilder
    content.vb: Public Interface IProjectSettingsDialogBuilder
  extensionMethods:
  - System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsDialog(Sdl.ProjectApi.IProject)
  commentId: M:Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsDialog(Sdl.ProjectApi.IProject)
  id: CreateProjectSettingsDialog(Sdl.ProjectApi.IProject)
  parent: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder
  langs:
  - csharp
  - vb
  name: CreateProjectSettingsDialog(IProject)
  nameWithType: IProjectSettingsDialogBuilder.CreateProjectSettingsDialog(IProject)
  fullName: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsDialog(Sdl.ProjectApi.IProject)
  type: Method
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.ProjectManagement
  syntax:
    content: ISettingsDialog CreateProjectSettingsDialog(IProject project)
    parameters:
    - id: project
      type: Sdl.ProjectApi.IProject
    return:
      type: Sdl.Desktop.Platform.Settings.ISettingsDialog
    content.vb: Function CreateProjectSettingsDialog(project As IProject) As ISettingsDialog
  overload: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsDialog*
- uid: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsDialog(Sdl.ProjectApi.IProject,Sdl.Desktop.Platform.Settings.ISettingsUIFilter)
  commentId: M:Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsDialog(Sdl.ProjectApi.IProject,Sdl.Desktop.Platform.Settings.ISettingsUIFilter)
  id: CreateProjectSettingsDialog(Sdl.ProjectApi.IProject,Sdl.Desktop.Platform.Settings.ISettingsUIFilter)
  parent: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder
  langs:
  - csharp
  - vb
  name: CreateProjectSettingsDialog(IProject, ISettingsUIFilter)
  nameWithType: IProjectSettingsDialogBuilder.CreateProjectSettingsDialog(IProject, ISettingsUIFilter)
  fullName: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsDialog(Sdl.ProjectApi.IProject, Sdl.Desktop.Platform.Settings.ISettingsUIFilter)
  type: Method
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.ProjectManagement
  syntax:
    content: ISettingsDialog CreateProjectSettingsDialog(IProject project, ISettingsUIFilter filter)
    parameters:
    - id: project
      type: Sdl.ProjectApi.IProject
    - id: filter
      type: Sdl.Desktop.Platform.Settings.ISettingsUIFilter
    return:
      type: Sdl.Desktop.Platform.Settings.ISettingsDialog
    content.vb: Function CreateProjectSettingsDialog(project As IProject, filter As ISettingsUIFilter) As ISettingsDialog
  overload: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsDialog*
- uid: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsFileTypesDialog(Sdl.ProjectApi.IProject)
  commentId: M:Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsFileTypesDialog(Sdl.ProjectApi.IProject)
  id: CreateProjectSettingsFileTypesDialog(Sdl.ProjectApi.IProject)
  parent: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder
  langs:
  - csharp
  - vb
  name: CreateProjectSettingsFileTypesDialog(IProject)
  nameWithType: IProjectSettingsDialogBuilder.CreateProjectSettingsFileTypesDialog(IProject)
  fullName: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsFileTypesDialog(Sdl.ProjectApi.IProject)
  type: Method
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.ProjectManagement
  syntax:
    content: ISettingsDialog CreateProjectSettingsFileTypesDialog(IProject project)
    parameters:
    - id: project
      type: Sdl.ProjectApi.IProject
    return:
      type: Sdl.Desktop.Platform.Settings.ISettingsDialog
    content.vb: Function CreateProjectSettingsFileTypesDialog(project As IProject) As ISettingsDialog
  overload: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsFileTypesDialog*
- uid: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectTemplateSettingsDialog(Sdl.ProjectApi.IProjectTemplate)
  commentId: M:Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectTemplateSettingsDialog(Sdl.ProjectApi.IProjectTemplate)
  id: CreateProjectTemplateSettingsDialog(Sdl.ProjectApi.IProjectTemplate)
  parent: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder
  langs:
  - csharp
  - vb
  name: CreateProjectTemplateSettingsDialog(IProjectTemplate)
  nameWithType: IProjectSettingsDialogBuilder.CreateProjectTemplateSettingsDialog(IProjectTemplate)
  fullName: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectTemplateSettingsDialog(Sdl.ProjectApi.IProjectTemplate)
  type: Method
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.ProjectManagement
  syntax:
    content: ISettingsDialog CreateProjectTemplateSettingsDialog(IProjectTemplate projectTemplate)
    parameters:
    - id: projectTemplate
      type: Sdl.ProjectApi.IProjectTemplate
    return:
      type: Sdl.Desktop.Platform.Settings.ISettingsDialog
    content.vb: Function CreateProjectTemplateSettingsDialog(projectTemplate As IProjectTemplate) As ISettingsDialog
  overload: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectTemplateSettingsDialog*
- uid: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateTranslatableFileSettingsDialog(Sdl.ProjectApi.ITranslatableFile)
  commentId: M:Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateTranslatableFileSettingsDialog(Sdl.ProjectApi.ITranslatableFile)
  id: CreateTranslatableFileSettingsDialog(Sdl.ProjectApi.ITranslatableFile)
  parent: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder
  langs:
  - csharp
  - vb
  name: CreateTranslatableFileSettingsDialog(ITranslatableFile)
  nameWithType: IProjectSettingsDialogBuilder.CreateTranslatableFileSettingsDialog(ITranslatableFile)
  fullName: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateTranslatableFileSettingsDialog(Sdl.ProjectApi.ITranslatableFile)
  type: Method
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.ProjectManagement
  syntax:
    content: ISettingsDialog CreateTranslatableFileSettingsDialog(ITranslatableFile translatableFile)
    parameters:
    - id: translatableFile
      type: Sdl.ProjectApi.ITranslatableFile
    return:
      type: Sdl.Desktop.Platform.Settings.ISettingsDialog
    content.vb: Function CreateTranslatableFileSettingsDialog(translatableFile As ITranslatableFile) As ISettingsDialog
  overload: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateTranslatableFileSettingsDialog*
references:
- uid: Sdl.TranslationStudio.Api.ProjectManagement
  commentId: N:Sdl.TranslationStudio.Api.ProjectManagement
  isExternal: true
  name: Sdl.TranslationStudio.Api.ProjectManagement
  nameWithType: Sdl.TranslationStudio.Api.ProjectManagement
  fullName: Sdl.TranslationStudio.Api.ProjectManagement
- uid: System.Object.Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  parent: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  definition: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  name: ForWindowFromFrameworkElement(Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  commentId: M:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
  isExternal: true
  name: ForWindowFromFrameworkElement(Object, Action<Window>)
  nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action<Window>)
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object, System.Action<System.Windows.Window>)
  nameWithType.vb: WindowsControlUtils.ForWindowFromFrameworkElement(Object, Action(Of Window))
  fullName.vb: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object, System.Action(Of System.Windows.Window))
  name.vb: ForWindowFromFrameworkElement(Object, Action(Of Window))
  spec.csharp:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement(System.Object,System.Action{System.Windows.Window})
    name: ForWindowFromFrameworkElement
    nameWithType: WindowsControlUtils.ForWindowFromFrameworkElement
    fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils.ForWindowFromFrameworkElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Windows.Window
    name: Window
    nameWithType: Window
    fullName: System.Windows.Window
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  commentId: T:Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
  parent: Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  name: WindowsControlUtils
  nameWithType: WindowsControlUtils
  fullName: Sdl.Desktop.Platform.Controls.Controls.WindowsControlUtils
- uid: Sdl.Desktop.Platform.Controls.Controls
  commentId: N:Sdl.Desktop.Platform.Controls.Controls
  isExternal: true
  name: Sdl.Desktop.Platform.Controls.Controls
  nameWithType: Sdl.Desktop.Platform.Controls.Controls
  fullName: Sdl.Desktop.Platform.Controls.Controls
- uid: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsDialog*
  commentId: Overload:Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsDialog
  isExternal: true
  name: CreateProjectSettingsDialog
  nameWithType: IProjectSettingsDialogBuilder.CreateProjectSettingsDialog
  fullName: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsDialog
- uid: Sdl.ProjectApi.IProject
  isExternal: true
  name: IProject
  nameWithType: IProject
  fullName: Sdl.ProjectApi.IProject
- uid: Sdl.Desktop.Platform.Settings.ISettingsDialog
  isExternal: true
  name: ISettingsDialog
  nameWithType: ISettingsDialog
  fullName: Sdl.Desktop.Platform.Settings.ISettingsDialog
- uid: Sdl.Desktop.Platform.Settings.ISettingsUIFilter
  commentId: '!:Sdl.Desktop.Platform.Settings.ISettingsUIFilter'
  isExternal: true
  name: ISettingsUIFilter
  nameWithType: ISettingsUIFilter
  fullName: Sdl.Desktop.Platform.Settings.ISettingsUIFilter
- uid: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsFileTypesDialog*
  commentId: Overload:Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsFileTypesDialog
  isExternal: true
  name: CreateProjectSettingsFileTypesDialog
  nameWithType: IProjectSettingsDialogBuilder.CreateProjectSettingsFileTypesDialog
  fullName: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectSettingsFileTypesDialog
- uid: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectTemplateSettingsDialog*
  commentId: Overload:Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectTemplateSettingsDialog
  isExternal: true
  name: CreateProjectTemplateSettingsDialog
  nameWithType: IProjectSettingsDialogBuilder.CreateProjectTemplateSettingsDialog
  fullName: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateProjectTemplateSettingsDialog
- uid: Sdl.ProjectApi.IProjectTemplate
  isExternal: true
  name: IProjectTemplate
  nameWithType: IProjectTemplate
  fullName: Sdl.ProjectApi.IProjectTemplate
- uid: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateTranslatableFileSettingsDialog*
  commentId: Overload:Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateTranslatableFileSettingsDialog
  isExternal: true
  name: CreateTranslatableFileSettingsDialog
  nameWithType: IProjectSettingsDialogBuilder.CreateTranslatableFileSettingsDialog
  fullName: Sdl.TranslationStudio.Api.ProjectManagement.IProjectSettingsDialogBuilder.CreateTranslatableFileSettingsDialog
- uid: Sdl.ProjectApi.ITranslatableFile
  isExternal: true
  name: ITranslatableFile
  nameWithType: ITranslatableFile
  fullName: Sdl.ProjectApi.ITranslatableFile
