### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl
  commentId: T:Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl
  id: IFileTypeDefinitionConfiguringControl
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi
  children:
  - Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.FileTypeDefintionId
  - Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.Save
  langs:
  - csharp
  - vb
  name: IFileTypeDefinitionConfiguringControl
  nameWithType: IFileTypeDefinitionConfiguringControl
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl
  type: Interface
  source:
    path: Sdl.FileTypeSupport.Framework.Core
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.IntegrationApi
  summary: "\nUsed by the Configuration Wizard to save the state of a control\n"
  syntax:
    content: public interface IFileTypeDefinitionConfiguringControl
    content.vb: Public Interface IFileTypeDefinitionConfiguringControl
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.Save
  commentId: M:Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.Save
  id: Save
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl
  langs:
  - csharp
  - vb
  name: Save()
  nameWithType: IFileTypeDefinitionConfiguringControl.Save()
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.Save()
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.IntegrationApi
  summary: "\nSaves the control&apos;s state to the underlying settings implementation\n"
  syntax:
    content: bool Save()
    return:
      type: System.Boolean
      description: true if successful, false otherwise
    content.vb: Function Save As Boolean
  overload: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.Save*
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.FileTypeDefintionId
  commentId: P:Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.FileTypeDefintionId
  id: FileTypeDefintionId
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl
  langs:
  - csharp
  - vb
  name: FileTypeDefintionId
  nameWithType: IFileTypeDefinitionConfiguringControl.FileTypeDefintionId
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.FileTypeDefintionId
  type: Property
  source:
    path: Sdl.FileTypeSupport.Framework.Core
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.IntegrationApi
  summary: "\nSets the FileTypeDefinitionId for use with underlying settings implementation\n"
  syntax:
    content: FileTypeDefinitionId FileTypeDefintionId { set; }
    parameters: []
    return:
      type: Sdl.FileTypeSupport.Framework.FileTypeDefinitionId
    content.vb: WriteOnly Property FileTypeDefintionId As FileTypeDefinitionId
  overload: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.FileTypeDefintionId*
  modifiers.csharp:
  - set
  modifiers.vb:
  - WriteOnly
references:
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi
  commentId: N:Sdl.FileTypeSupport.Framework.IntegrationApi
  isExternal: true
  name: Sdl.FileTypeSupport.Framework.IntegrationApi
  nameWithType: Sdl.FileTypeSupport.Framework.IntegrationApi
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.Save*
  commentId: Overload:Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.Save
  isExternal: true
  name: Save
  nameWithType: IFileTypeDefinitionConfiguringControl.Save
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.Save
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.FileTypeDefintionId*
  commentId: Overload:Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.FileTypeDefintionId
  isExternal: true
  name: FileTypeDefintionId
  nameWithType: IFileTypeDefinitionConfiguringControl.FileTypeDefintionId
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.FileTypeDefintionId
- uid: Sdl.FileTypeSupport.Framework.FileTypeDefinitionId
  commentId: T:Sdl.FileTypeSupport.Framework.FileTypeDefinitionId
  parent: Sdl.FileTypeSupport.Framework
  isExternal: true
  name: FileTypeDefinitionId
  nameWithType: FileTypeDefinitionId
  fullName: Sdl.FileTypeSupport.Framework.FileTypeDefinitionId
- uid: Sdl.FileTypeSupport.Framework
  commentId: N:Sdl.FileTypeSupport.Framework
  isExternal: true
  name: Sdl.FileTypeSupport.Framework
  nameWithType: Sdl.FileTypeSupport.Framework
  fullName: Sdl.FileTypeSupport.Framework
