### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder
  commentId: T:Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder
  id: IFileTypeSettingsConverterComponentBuilder
  parent: Sdl.FileTypeSupport.Framework.Core.IntegrationApi
  children:
  - Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter(System.String)
  langs:
  - csharp
  - vb
  name: IFileTypeSettingsConverterComponentBuilder
  nameWithType: IFileTypeSettingsConverterComponentBuilder
  fullName: Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder
  type: Interface
  source:
    path: Sdl.FileTypeSupport.Framework.Core
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.Core.IntegrationApi
  summary: "\nInterface for implementing FileTypeSettingsConverterComponentBuilder\n"
  syntax:
    content: public interface IFileTypeSettingsConverterComponentBuilder
    content.vb: Public Interface IFileTypeSettingsConverterComponentBuilder
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter(System.String)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter(System.String)
  id: BuildFileTypeSettingsConverter(System.String)
  parent: Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder
  langs:
  - csharp
  - vb
  name: BuildFileTypeSettingsConverter(String)
  nameWithType: IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter(String)
  fullName: Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter(System.String)
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.Core.IntegrationApi
  summary: "\nMethod for building FileTypeSettingsConverter component\n"
  syntax:
    content: IFileTypeSettingsConverter BuildFileTypeSettingsConverter(string name)
    parameters:
    - id: name
      type: System.String
      description: name of component
    return:
      type: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter
      description: IFileTypeSettingsConverter instance
    content.vb: Function BuildFileTypeSettingsConverter(name As String) As IFileTypeSettingsConverter
  overload: Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter*
references:
- uid: Sdl.FileTypeSupport.Framework.Core.IntegrationApi
  commentId: N:Sdl.FileTypeSupport.Framework.Core.IntegrationApi
  isExternal: true
  name: Sdl.FileTypeSupport.Framework.Core.IntegrationApi
  nameWithType: Sdl.FileTypeSupport.Framework.Core.IntegrationApi
  fullName: Sdl.FileTypeSupport.Framework.Core.IntegrationApi
- uid: Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter
  isExternal: true
  name: BuildFileTypeSettingsConverter
  nameWithType: IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter
  fullName: Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter
  parent: Sdl.FileTypeSupport.Framework.Core.Settings
  isExternal: true
  name: IFileTypeSettingsConverter
  nameWithType: IFileTypeSettingsConverter
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.FileTypeSupport.Framework.Core.Settings
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings
  isExternal: true
  name: Sdl.FileTypeSupport.Framework.Core.Settings
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings
