### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  id: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  children:
  - Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings.FileTypeSettingsJson
  - Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings.FileTypeSettingsUtil
  langs:
  - csharp
  - vb
  name: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  type: Namespace
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
references:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings.FileTypeSettingsJson
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings.FileTypeSettingsJson
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  isExternal: true
  name: FileTypeSettingsJson
  nameWithType: FileTypeSettingsJson
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings.FileTypeSettingsJson
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings.FileTypeSettingsUtil
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings.FileTypeSettingsUtil
  isExternal: true
  name: FileTypeSettingsUtil
  nameWithType: FileTypeSettingsUtil
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings.FileTypeSettingsUtil
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  isExternal: true
  name: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
