### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute
  commentId: T:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute
  id: CustomAttribute
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes
  children:
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.#ctor
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.DisplayName
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.DisplayOrder
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Name
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Type
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Values
  langs:
  - csharp
  - vb
  name: CustomAttribute
  nameWithType: CustomAttribute
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute
  type: Class
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: public class CustomAttribute
    content.vb: Public Class CustomAttribute
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.#ctor
  commentId: M:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.#ctor
  id: '#ctor'
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute
  langs:
  - csharp
  - vb
  name: CustomAttribute()
  nameWithType: CustomAttribute.CustomAttribute()
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.CustomAttribute()
  type: Constructor
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: public CustomAttribute()
    content.vb: Public Sub New
  overload: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Name
  commentId: P:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Name
  id: Name
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: CustomAttribute.Name
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Name
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: public string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Name As String
  overload: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Name*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.DisplayName
  commentId: P:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.DisplayName
  id: DisplayName
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute
  langs:
  - csharp
  - vb
  name: DisplayName
  nameWithType: CustomAttribute.DisplayName
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.DisplayName
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: public string DisplayName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property DisplayName As String
  overload: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.DisplayName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Type
  commentId: P:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Type
  id: Type
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute
  langs:
  - csharp
  - vb
  name: Type
  nameWithType: CustomAttribute.Type
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Type
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: public CustomAttributeTypeEnum Type { get; set; }
    parameters: []
    return:
      type: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
    content.vb: Public Property Type As CustomAttributeTypeEnum
  overload: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Type*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.DisplayOrder
  commentId: P:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.DisplayOrder
  id: DisplayOrder
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute
  langs:
  - csharp
  - vb
  name: DisplayOrder
  nameWithType: CustomAttribute.DisplayOrder
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.DisplayOrder
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: public int DisplayOrder { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property DisplayOrder As Integer
  overload: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.DisplayOrder*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Values
  commentId: P:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Values
  id: Values
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute
  langs:
  - csharp
  - vb
  name: Values
  nameWithType: CustomAttribute.Values
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Values
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: public List<string> Values { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.List{System.String}
    content.vb: Public Property Values As List(Of String)
  overload: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Values*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes
  commentId: N:Sdl.ProjectAutomation.Settings.CustomAttributes
  isExternal: true
  name: Sdl.ProjectAutomation.Settings.CustomAttributes
  nameWithType: Sdl.ProjectAutomation.Settings.CustomAttributes
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.#ctor*
  commentId: Overload:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.#ctor
  isExternal: true
  name: CustomAttribute
  nameWithType: CustomAttribute.CustomAttribute
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.CustomAttribute
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Name*
  commentId: Overload:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Name
  isExternal: true
  name: Name
  nameWithType: CustomAttribute.Name
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.DisplayName*
  commentId: Overload:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.DisplayName
  isExternal: true
  name: DisplayName
  nameWithType: CustomAttribute.DisplayName
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.DisplayName
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Type*
  commentId: Overload:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Type
  isExternal: true
  name: Type
  nameWithType: CustomAttribute.Type
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Type
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
  commentId: T:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes
  isExternal: true
  name: CustomAttributeTypeEnum
  nameWithType: CustomAttributeTypeEnum
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.DisplayOrder*
  commentId: Overload:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.DisplayOrder
  isExternal: true
  name: DisplayOrder
  nameWithType: CustomAttribute.DisplayOrder
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.DisplayOrder
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Values*
  commentId: Overload:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Values
  isExternal: true
  name: Values
  nameWithType: CustomAttribute.Values
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.Values
- uid: System.Collections.Generic.List{System.String}
  commentId: T:System.Collections.Generic.List{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  name: List<String>
  nameWithType: List<String>
  fullName: System.Collections.Generic.List<System.String>
  nameWithType.vb: List(Of String)
  fullName.vb: System.Collections.Generic.List(Of System.String)
  name.vb: List(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
