### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration
  commentId: T:Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration
  id: ProjectFileTypeConfiguration
  parent: Sdl.ProjectAutomation.Core
  children:
  - Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FileTypeManagerConfiguration
  - Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FilterManager
  - Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.StandardFilterManager
  - Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.SubContentFileTypeManagerConfiguration
  langs:
  - csharp
  - vb
  name: ProjectFileTypeConfiguration
  nameWithType: ProjectFileTypeConfiguration
  fullName: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration
  type: Class
  assemblies:
  - Sdl.ProjectAutomation.Core
  namespace: Sdl.ProjectAutomation.Core
  syntax:
    content: public class ProjectFileTypeConfiguration
    content.vb: Public Class ProjectFileTypeConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
- uid: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FilterManager
  commentId: P:Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FilterManager
  id: FilterManager
  parent: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration
  langs:
  - csharp
  - vb
  name: FilterManager
  nameWithType: ProjectFileTypeConfiguration.FilterManager
  fullName: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FilterManager
  type: Property
  assemblies:
  - Sdl.ProjectAutomation.Core
  namespace: Sdl.ProjectAutomation.Core
  syntax:
    content: public IFileTypeManager FilterManager { get; }
    parameters: []
    return:
      type: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeManager
    content.vb: Public ReadOnly Property FilterManager As IFileTypeManager
  overload: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FilterManager*
- uid: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.StandardFilterManager
  commentId: P:Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.StandardFilterManager
  id: StandardFilterManager
  parent: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration
  langs:
  - csharp
  - vb
  name: StandardFilterManager
  nameWithType: ProjectFileTypeConfiguration.StandardFilterManager
  fullName: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.StandardFilterManager
  type: Property
  assemblies:
  - Sdl.ProjectAutomation.Core
  namespace: Sdl.ProjectAutomation.Core
  syntax:
    content: public IFileTypeManager StandardFilterManager { get; }
    parameters: []
    return:
      type: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeManager
    content.vb: Public ReadOnly Property StandardFilterManager As IFileTypeManager
  overload: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.StandardFilterManager*
- uid: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FileTypeManagerConfiguration
  commentId: P:Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FileTypeManagerConfiguration
  id: FileTypeManagerConfiguration
  parent: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration
  langs:
  - csharp
  - vb
  name: FileTypeManagerConfiguration
  nameWithType: ProjectFileTypeConfiguration.FileTypeManagerConfiguration
  fullName: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FileTypeManagerConfiguration
  type: Property
  assemblies:
  - Sdl.ProjectAutomation.Core
  namespace: Sdl.ProjectAutomation.Core
  syntax:
    content: public IFileTypeManagerConfiguration FileTypeManagerConfiguration { get; }
    parameters: []
    return:
      type: Sdl.ProjectApi.IFileTypeManagerConfiguration
    content.vb: Public ReadOnly Property FileTypeManagerConfiguration As IFileTypeManagerConfiguration
  overload: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FileTypeManagerConfiguration*
- uid: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.SubContentFileTypeManagerConfiguration
  commentId: P:Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.SubContentFileTypeManagerConfiguration
  id: SubContentFileTypeManagerConfiguration
  parent: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration
  langs:
  - csharp
  - vb
  name: SubContentFileTypeManagerConfiguration
  nameWithType: ProjectFileTypeConfiguration.SubContentFileTypeManagerConfiguration
  fullName: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.SubContentFileTypeManagerConfiguration
  type: Property
  assemblies:
  - Sdl.ProjectAutomation.Core
  namespace: Sdl.ProjectAutomation.Core
  syntax:
    content: public IFileTypeManagerConfiguration SubContentFileTypeManagerConfiguration { get; }
    parameters: []
    return:
      type: Sdl.ProjectApi.IFileTypeManagerConfiguration
    content.vb: Public ReadOnly Property SubContentFileTypeManagerConfiguration As IFileTypeManagerConfiguration
  overload: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.SubContentFileTypeManagerConfiguration*
references:
- uid: Sdl.ProjectAutomation.Core
  commentId: N:Sdl.ProjectAutomation.Core
  isExternal: true
  href: Sdl.html
  name: Sdl.ProjectAutomation.Core
  nameWithType: Sdl.ProjectAutomation.Core
  fullName: Sdl.ProjectAutomation.Core
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.ProjectAutomation
    name: ProjectAutomation
    isExternal: true
    href: Sdl.ProjectAutomation.html
  - name: .
  - uid: Sdl.ProjectAutomation.Core
    name: Core
    isExternal: true
    href: Sdl.ProjectAutomation.Core.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.ProjectAutomation
    name: ProjectAutomation
    isExternal: true
    href: Sdl.ProjectAutomation.html
  - name: .
  - uid: Sdl.ProjectAutomation.Core
    name: Core
    isExternal: true
    href: Sdl.ProjectAutomation.Core.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FilterManager*
  commentId: Overload:Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FilterManager
  isExternal: true
  href: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.html#Sdl_ProjectAutomation_Core_ProjectFileTypeConfiguration_FilterManager
  name: FilterManager
  nameWithType: ProjectFileTypeConfiguration.FilterManager
  fullName: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FilterManager
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeManager
  commentId: T:Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeManager
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi
  isExternal: true
  name: IFileTypeManager
  nameWithType: IFileTypeManager
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeManager
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi
  commentId: N:Sdl.FileTypeSupport.Framework.IntegrationApi
  isExternal: true
  name: Sdl.FileTypeSupport.Framework.IntegrationApi
  nameWithType: Sdl.FileTypeSupport.Framework.IntegrationApi
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi
    name: IntegrationApi
    isExternal: true
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi
    name: IntegrationApi
    isExternal: true
- uid: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.StandardFilterManager*
  commentId: Overload:Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.StandardFilterManager
  isExternal: true
  href: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.html#Sdl_ProjectAutomation_Core_ProjectFileTypeConfiguration_StandardFilterManager
  name: StandardFilterManager
  nameWithType: ProjectFileTypeConfiguration.StandardFilterManager
  fullName: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.StandardFilterManager
- uid: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FileTypeManagerConfiguration*
  commentId: Overload:Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FileTypeManagerConfiguration
  isExternal: true
  href: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.html#Sdl_ProjectAutomation_Core_ProjectFileTypeConfiguration_FileTypeManagerConfiguration
  name: FileTypeManagerConfiguration
  nameWithType: ProjectFileTypeConfiguration.FileTypeManagerConfiguration
  fullName: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FileTypeManagerConfiguration
- uid: Sdl.ProjectApi.IFileTypeManagerConfiguration
  commentId: T:Sdl.ProjectApi.IFileTypeManagerConfiguration
  parent: Sdl.ProjectApi
  isExternal: true
  name: IFileTypeManagerConfiguration
  nameWithType: IFileTypeManagerConfiguration
  fullName: Sdl.ProjectApi.IFileTypeManagerConfiguration
- uid: Sdl.ProjectApi
  commentId: N:Sdl.ProjectApi
  isExternal: true
  name: Sdl.ProjectApi
  nameWithType: Sdl.ProjectApi
  fullName: Sdl.ProjectApi
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
  - name: .
  - uid: Sdl.ProjectApi
    name: ProjectApi
    isExternal: true
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
  - name: .
  - uid: Sdl.ProjectApi
    name: ProjectApi
    isExternal: true
- uid: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.SubContentFileTypeManagerConfiguration*
  commentId: Overload:Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.SubContentFileTypeManagerConfiguration
  isExternal: true
  href: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.html#Sdl_ProjectAutomation_Core_ProjectFileTypeConfiguration_SubContentFileTypeManagerConfiguration
  name: SubContentFileTypeManagerConfiguration
  nameWithType: ProjectFileTypeConfiguration.SubContentFileTypeManagerConfiguration
  fullName: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.SubContentFileTypeManagerConfiguration
