### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings
  commentId: T:Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings
  id: BatchProcessingGeneralSettings
  parent: Sdl.ProjectAutomation.Settings
  children:
  - Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.#ctor
  - Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.DefaultOptimizeBatchProcessing
  - Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.GetDefaultValue(System.String)
  - Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.OptimizeBatchProcessing
  langs:
  - csharp
  - vb
  name: BatchProcessingGeneralSettings
  nameWithType: BatchProcessingGeneralSettings
  fullName: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings
  type: Class
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  syntax:
    content: 'public class BatchProcessingGeneralSettings : SettingsGroup'
    content.vb: >-
      Public Class BatchProcessingGeneralSettings
          Inherits SettingsGroup
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.DefaultOptimizeBatchProcessing
  commentId: F:Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.DefaultOptimizeBatchProcessing
  id: DefaultOptimizeBatchProcessing
  parent: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings
  langs:
  - csharp
  - vb
  name: DefaultOptimizeBatchProcessing
  nameWithType: BatchProcessingGeneralSettings.DefaultOptimizeBatchProcessing
  fullName: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.DefaultOptimizeBatchProcessing
  type: Field
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  syntax:
    content: public const bool DefaultOptimizeBatchProcessing = false
    return:
      type: System.Boolean
    content.vb: Public Const DefaultOptimizeBatchProcessing As Boolean = False
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.#ctor
  commentId: M:Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.#ctor
  id: '#ctor'
  parent: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings
  langs:
  - csharp
  - vb
  name: BatchProcessingGeneralSettings()
  nameWithType: BatchProcessingGeneralSettings.BatchProcessingGeneralSettings()
  fullName: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.BatchProcessingGeneralSettings()
  type: Constructor
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nDefault constructor. You should never create this object manually. Use <xref href=\"Sdl.Core.Settings.ISettingsBundle.GetSettingsGroup(System.String)\" data-throw-if-not-resolved=\"false\"></xref> instead.\n"
  syntax:
    content: public BatchProcessingGeneralSettings()
    content.vb: Public Sub New
  overload: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.GetDefaultValue(System.String)
  commentId: M:Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.GetDefaultValue(System.String)
  id: GetDefaultValue(System.String)
  parent: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings
  langs:
  - csharp
  - vb
  name: GetDefaultValue(String)
  nameWithType: BatchProcessingGeneralSettings.GetDefaultValue(String)
  fullName: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.GetDefaultValue(System.String)
  type: Method
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nGets the default value.\n"
  syntax:
    content: protected override object GetDefaultValue(string settingId)
    parameters:
    - id: settingId
      type: System.String
      description: The setting id.
    return:
      type: System.Object
    content.vb: Protected Overrides Function GetDefaultValue(settingId As String) As Object
  overload: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.GetDefaultValue*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.OptimizeBatchProcessing
  commentId: P:Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.OptimizeBatchProcessing
  id: OptimizeBatchProcessing
  parent: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings
  langs:
  - csharp
  - vb
  name: OptimizeBatchProcessing
  nameWithType: BatchProcessingGeneralSettings.OptimizeBatchProcessing
  fullName: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.OptimizeBatchProcessing
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nGets the setting that flags whether a . Default: false.\n"
  syntax:
    content: public Setting<bool> OptimizeBatchProcessing { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.Setting{System.Boolean}
    content.vb: Public ReadOnly Property OptimizeBatchProcessing As Setting(Of Boolean)
  overload: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.OptimizeBatchProcessing*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Sdl.ProjectAutomation.Settings
  commentId: N:Sdl.ProjectAutomation.Settings
  isExternal: true
  name: Sdl.ProjectAutomation.Settings
  nameWithType: Sdl.ProjectAutomation.Settings
  fullName: Sdl.ProjectAutomation.Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.#ctor*
  commentId: Overload:Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.#ctor
  isExternal: true
  name: BatchProcessingGeneralSettings
  nameWithType: BatchProcessingGeneralSettings.BatchProcessingGeneralSettings
  fullName: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.BatchProcessingGeneralSettings
- uid: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.GetDefaultValue*
  commentId: Overload:Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.GetDefaultValue
  isExternal: true
  name: GetDefaultValue
  nameWithType: BatchProcessingGeneralSettings.GetDefaultValue
  fullName: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.GetDefaultValue
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.OptimizeBatchProcessing*
  commentId: Overload:Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.OptimizeBatchProcessing
  isExternal: true
  name: OptimizeBatchProcessing
  nameWithType: BatchProcessingGeneralSettings.OptimizeBatchProcessing
  fullName: Sdl.ProjectAutomation.Settings.BatchProcessingGeneralSettings.OptimizeBatchProcessing
- uid: Sdl.Core.Settings.Setting{System.Boolean}
  commentId: '!:Sdl.Core.Settings.Setting{System.Boolean}'
  definition: Sdl.Core.Settings.Setting`1
  name: Setting<Boolean>
  nameWithType: Setting<Boolean>
  fullName: Sdl.Core.Settings.Setting<System.Boolean>
  nameWithType.vb: Setting(Of Boolean)
  fullName.vb: Sdl.Core.Settings.Setting(Of System.Boolean)
  name.vb: Setting(Of Boolean)
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Core.Settings.Setting`1
  isExternal: true
  name: Setting<>
  nameWithType: Setting<>
  fullName: Sdl.Core.Settings.Setting<>
  nameWithType.vb: Setting(Of )
  fullName.vb: Sdl.Core.Settings.Setting(Of )
  name.vb: Setting(Of )
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
