### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.ExportFilesSettings
  commentId: T:Sdl.ProjectAutomation.Settings.ExportFilesSettings
  id: ExportFilesSettings
  parent: Sdl.ProjectAutomation.Settings
  children:
  - Sdl.ProjectAutomation.Settings.ExportFilesSettings.#ctor
  - Sdl.ProjectAutomation.Settings.ExportFilesSettings.ExportFileVersion
  - Sdl.ProjectAutomation.Settings.ExportFilesSettings.ExportLocation
  - Sdl.ProjectAutomation.Settings.ExportFilesSettings.GetDefaultValue(System.String)
  langs:
  - csharp
  - vb
  name: ExportFilesSettings
  nameWithType: ExportFilesSettings
  fullName: Sdl.ProjectAutomation.Settings.ExportFilesSettings
  type: Class
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nSettings group class for the Export Files automatic task settings.\n"
  syntax:
    content: 'public class ExportFilesSettings : SettingsGroup'
    content.vb: >-
      Public Class ExportFilesSettings
          Inherits SettingsGroup
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.ProjectAutomation.Settings.ExportFilesSettings.#ctor
  commentId: M:Sdl.ProjectAutomation.Settings.ExportFilesSettings.#ctor
  id: '#ctor'
  parent: Sdl.ProjectAutomation.Settings.ExportFilesSettings
  langs:
  - csharp
  - vb
  name: ExportFilesSettings()
  nameWithType: ExportFilesSettings.ExportFilesSettings()
  fullName: Sdl.ProjectAutomation.Settings.ExportFilesSettings.ExportFilesSettings()
  type: Constructor
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nDefault constructor. You should never create this object manually. Use <xref href=\"Sdl.Core.Settings.ISettingsBundle.GetSettingsGroup(System.String)\" data-throw-if-not-resolved=\"false\"></xref> instead.\n"
  syntax:
    content: public ExportFilesSettings()
    content.vb: Public Sub New
  overload: Sdl.ProjectAutomation.Settings.ExportFilesSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.ProjectAutomation.Settings.ExportFilesSettings.GetDefaultValue(System.String)
  commentId: M:Sdl.ProjectAutomation.Settings.ExportFilesSettings.GetDefaultValue(System.String)
  id: GetDefaultValue(System.String)
  parent: Sdl.ProjectAutomation.Settings.ExportFilesSettings
  langs:
  - csharp
  - vb
  name: GetDefaultValue(String)
  nameWithType: ExportFilesSettings.GetDefaultValue(String)
  fullName: Sdl.ProjectAutomation.Settings.ExportFilesSettings.GetDefaultValue(System.String)
  type: Method
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nGets the default value.\n"
  syntax:
    content: protected override object GetDefaultValue(string settingId)
    parameters:
    - id: settingId
      type: System.String
      description: The setting id.
    return:
      type: System.Object
      description: The default value.
    content.vb: Protected Overrides Function GetDefaultValue(settingId As String) As Object
  overload: Sdl.ProjectAutomation.Settings.ExportFilesSettings.GetDefaultValue*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: Sdl.ProjectAutomation.Settings.ExportFilesSettings.ExportFileVersion
  commentId: P:Sdl.ProjectAutomation.Settings.ExportFilesSettings.ExportFileVersion
  id: ExportFileVersion
  parent: Sdl.ProjectAutomation.Settings.ExportFilesSettings
  langs:
  - csharp
  - vb
  name: ExportFileVersion
  nameWithType: ExportFilesSettings.ExportFileVersion
  fullName: Sdl.ProjectAutomation.Settings.ExportFilesSettings.ExportFileVersion
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nGets the setting that flags whether native files should be created and exported. By default, this is set to\n<xref href=\"Sdl.ProjectAutomation.Settings.ExportFileVersion.Native\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  syntax:
    content: public Setting<ExportFileVersion> ExportFileVersion { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.Setting{Sdl.ProjectAutomation.Settings.ExportFileVersion}
    content.vb: Public ReadOnly Property ExportFileVersion As Setting(Of ExportFileVersion)
  overload: Sdl.ProjectAutomation.Settings.ExportFilesSettings.ExportFileVersion*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Sdl.ProjectAutomation.Settings.ExportFilesSettings.ExportLocation
  commentId: P:Sdl.ProjectAutomation.Settings.ExportFilesSettings.ExportLocation
  id: ExportLocation
  parent: Sdl.ProjectAutomation.Settings.ExportFilesSettings
  langs:
  - csharp
  - vb
  name: ExportLocation
  nameWithType: ExportFilesSettings.ExportLocation
  fullName: Sdl.ProjectAutomation.Settings.ExportFilesSettings.ExportLocation
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nGets the directory to which the files will be exported. Note that the project directory structure will be \ncreated under this directory. By default, this is set to &quot;[My Documents]\\Export Files&quot;.\n"
  syntax:
    content: public Setting<string> ExportLocation { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.Setting{System.String}
    content.vb: Public ReadOnly Property ExportLocation As Setting(Of String)
  overload: Sdl.ProjectAutomation.Settings.ExportFilesSettings.ExportLocation*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Sdl.ProjectAutomation.Settings
  commentId: N:Sdl.ProjectAutomation.Settings
  isExternal: true
  name: Sdl.ProjectAutomation.Settings
  nameWithType: Sdl.ProjectAutomation.Settings
  fullName: Sdl.ProjectAutomation.Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.ProjectAutomation.Settings.ExportFilesSettings.#ctor*
  commentId: Overload:Sdl.ProjectAutomation.Settings.ExportFilesSettings.#ctor
  isExternal: true
  name: ExportFilesSettings
  nameWithType: ExportFilesSettings.ExportFilesSettings
  fullName: Sdl.ProjectAutomation.Settings.ExportFilesSettings.ExportFilesSettings
- uid: Sdl.ProjectAutomation.Settings.ExportFilesSettings.GetDefaultValue*
  commentId: Overload:Sdl.ProjectAutomation.Settings.ExportFilesSettings.GetDefaultValue
  isExternal: true
  name: GetDefaultValue
  nameWithType: ExportFilesSettings.GetDefaultValue
  fullName: Sdl.ProjectAutomation.Settings.ExportFilesSettings.GetDefaultValue
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Sdl.ProjectAutomation.Settings.ExportFilesSettings.ExportFileVersion*
  commentId: Overload:Sdl.ProjectAutomation.Settings.ExportFilesSettings.ExportFileVersion
  isExternal: true
  name: ExportFileVersion
  nameWithType: ExportFilesSettings.ExportFileVersion
  fullName: Sdl.ProjectAutomation.Settings.ExportFilesSettings.ExportFileVersion
- uid: Sdl.Core.Settings.Setting{Sdl.ProjectAutomation.Settings.ExportFileVersion}
  commentId: '!:Sdl.Core.Settings.Setting{Sdl.ProjectAutomation.Settings.ExportFileVersion}'
  definition: Sdl.Core.Settings.Setting`1
  name: Setting<ExportFileVersion>
  nameWithType: Setting<ExportFileVersion>
  fullName: Sdl.Core.Settings.Setting<Sdl.ProjectAutomation.Settings.ExportFileVersion>
  nameWithType.vb: Setting(Of ExportFileVersion)
  fullName.vb: Sdl.Core.Settings.Setting(Of Sdl.ProjectAutomation.Settings.ExportFileVersion)
  name.vb: Setting(Of ExportFileVersion)
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Sdl.ProjectAutomation.Settings.ExportFileVersion
    name: ExportFileVersion
    nameWithType: ExportFileVersion
    fullName: Sdl.ProjectAutomation.Settings.ExportFileVersion
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Sdl.ProjectAutomation.Settings.ExportFileVersion
    name: ExportFileVersion
    nameWithType: ExportFileVersion
    fullName: Sdl.ProjectAutomation.Settings.ExportFileVersion
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Core.Settings.Setting`1
  isExternal: true
  name: Setting<>
  nameWithType: Setting<>
  fullName: Sdl.Core.Settings.Setting<>
  nameWithType.vb: Setting(Of )
  fullName.vb: Sdl.Core.Settings.Setting(Of )
  name.vb: Setting(Of )
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.ProjectAutomation.Settings.ExportFilesSettings.ExportLocation*
  commentId: Overload:Sdl.ProjectAutomation.Settings.ExportFilesSettings.ExportLocation
  isExternal: true
  name: ExportLocation
  nameWithType: ExportFilesSettings.ExportLocation
  fullName: Sdl.ProjectAutomation.Settings.ExportFilesSettings.ExportLocation
- uid: Sdl.Core.Settings.Setting{System.String}
  commentId: '!:Sdl.Core.Settings.Setting{System.String}'
  definition: Sdl.Core.Settings.Setting`1
  name: Setting<String>
  nameWithType: Setting<String>
  fullName: Sdl.Core.Settings.Setting<System.String>
  nameWithType.vb: Setting(Of String)
  fullName.vb: Sdl.Core.Settings.Setting(Of System.String)
  name.vb: Setting(Of String)
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
