### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
  commentId: T:Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
  id: MeasurementsFormattingMode
  parent: Sdl.ProjectAutomation.Settings
  children:
  - Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.Auto_FromDocument
  - Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.Auto_FromMemory
  - Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.DeleteWhitespace
  - Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.InsertNonbreakingSpace
  - Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.InsertSpace
  - Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.InsertSpecifiedSeparator
  langs:
  - csharp
  - vb
  name: MeasurementsFormattingMode
  nameWithType: MeasurementsFormattingMode
  fullName: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
  type: Enum
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: >-
    Controls which tokens are used to obtain detailed localization parameters, such as

    the numeric group separator override, or whitespace handling between a number and the unit in measurements.
  example: []
  syntax:
    content: public enum MeasurementsFormattingMode
    content.vb: Public Enum MeasurementsFormattingMode
- uid: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.Auto_FromDocument
  commentId: F:Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.Auto_FromDocument
  id: Auto_FromDocument
  parent: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
  langs:
  - csharp
  - vb
  name: Auto_FromDocument
  nameWithType: MeasurementsFormattingMode.Auto_FromDocument
  fullName: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.Auto_FromDocument
  type: Field
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: >-
    Use information from the document (source) token to auto-localize the tokens in the 

    translation proposal. Use the whitespace handling as it is obtained from the document or memory token.
  example: []
  syntax:
    content: Auto_FromDocument = 0
    return:
      type: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
- uid: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.Auto_FromMemory
  commentId: F:Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.Auto_FromMemory
  id: Auto_FromMemory
  parent: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
  langs:
  - csharp
  - vb
  name: Auto_FromMemory
  nameWithType: MeasurementsFormattingMode.Auto_FromMemory
  fullName: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.Auto_FromMemory
  type: Field
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: >-
    Use information from the memory source and target tokens to auto-localize the tokens in the

    translation proposal. Use the whitespace handling as it is obtained from the document or memory token.
  example: []
  syntax:
    content: Auto_FromMemory = 1
    return:
      type: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
- uid: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.DeleteWhitespace
  commentId: F:Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.DeleteWhitespace
  id: DeleteWhitespace
  parent: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
  langs:
  - csharp
  - vb
  name: DeleteWhitespace
  nameWithType: MeasurementsFormattingMode.DeleteWhitespace
  fullName: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.DeleteWhitespace
  type: Field
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: >-
    Use information from the document (source) token to auto-localize the tokens in the 

    translation proposal. Delete any whitespace between the number and the unit.
  example: []
  syntax:
    content: DeleteWhitespace = 2
    return:
      type: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
- uid: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.InsertSpace
  commentId: F:Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.InsertSpace
  id: InsertSpace
  parent: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
  langs:
  - csharp
  - vb
  name: InsertSpace
  nameWithType: MeasurementsFormattingMode.InsertSpace
  fullName: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.InsertSpace
  type: Field
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: >-
    Use information from the document (source) token to auto-localize the tokens in the 

    translation proposal. Always insert a single standard space between the number and the unit.
  example: []
  syntax:
    content: InsertSpace = 3
    return:
      type: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
- uid: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.InsertNonbreakingSpace
  commentId: F:Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.InsertNonbreakingSpace
  id: InsertNonbreakingSpace
  parent: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
  langs:
  - csharp
  - vb
  name: InsertNonbreakingSpace
  nameWithType: MeasurementsFormattingMode.InsertNonbreakingSpace
  fullName: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.InsertNonbreakingSpace
  type: Field
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: >-
    Use information from the document (source) token to auto-localize the tokens in the 

    translation proposal. Always insert a single non-breaking space between the number and the unit.
  example: []
  syntax:
    content: InsertNonbreakingSpace = 4
    return:
      type: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
- uid: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.InsertSpecifiedSeparator
  commentId: F:Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.InsertSpecifiedSeparator
  id: InsertSpecifiedSeparator
  parent: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
  langs:
  - csharp
  - vb
  name: InsertSpecifiedSeparator
  nameWithType: MeasurementsFormattingMode.InsertSpecifiedSeparator
  fullName: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.InsertSpecifiedSeparator
  type: Field
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: >-
    Use information from the document (source) token to auto-localize the tokens in the 

    translation proposal. Always insert the separator specified in the autolocalization settings
  example: []
  syntax:
    content: InsertSpecifiedSeparator = 5
    return:
      type: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
references:
- uid: Sdl.ProjectAutomation.Settings
  commentId: N:Sdl.ProjectAutomation.Settings
  isExternal: true
  href: Sdl.html
  name: Sdl.ProjectAutomation.Settings
  nameWithType: Sdl.ProjectAutomation.Settings
  fullName: Sdl.ProjectAutomation.Settings
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.ProjectAutomation
    name: ProjectAutomation
    isExternal: true
    href: Sdl.ProjectAutomation.html
  - name: .
  - uid: Sdl.ProjectAutomation.Settings
    name: Settings
    isExternal: true
    href: Sdl.ProjectAutomation.Settings.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.ProjectAutomation
    name: ProjectAutomation
    isExternal: true
    href: Sdl.ProjectAutomation.html
  - name: .
  - uid: Sdl.ProjectAutomation.Settings
    name: Settings
    isExternal: true
    href: Sdl.ProjectAutomation.Settings.html
- uid: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
  commentId: T:Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
  parent: Sdl.ProjectAutomation.Settings
  isExternal: true
  href: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode.html
  name: MeasurementsFormattingMode
  nameWithType: MeasurementsFormattingMode
  fullName: Sdl.ProjectAutomation.Settings.MeasurementsFormattingMode
