### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.Events
  commentId: N:Sdl.ProjectAutomation.Settings.Events
  id: Sdl.ProjectAutomation.Settings.Events
  children:
  - Sdl.ProjectAutomation.Settings.Events.TranslationProviderStatusChanged
  langs:
  - csharp
  - vb
  name: Sdl.ProjectAutomation.Settings.Events
  nameWithType: Sdl.ProjectAutomation.Settings.Events
  fullName: Sdl.ProjectAutomation.Settings.Events
  type: Namespace
  assemblies:
  - Sdl.ProjectAutomation.Settings
references:
- uid: Sdl.ProjectAutomation.Settings.Events.TranslationProviderStatusChanged
  commentId: T:Sdl.ProjectAutomation.Settings.Events.TranslationProviderStatusChanged
  isExternal: true
  href: Sdl.ProjectAutomation.Settings.Events.TranslationProviderStatusChanged.html
  name: TranslationProviderStatusChanged
  nameWithType: TranslationProviderStatusChanged
  fullName: Sdl.ProjectAutomation.Settings.Events.TranslationProviderStatusChanged
