### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings
  commentId: T:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings
  id: CustomAttributeSettings
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes
  children:
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.#ctor
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.Attributes
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.CustomAttributes_Setting
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.File_CustomAttributes_SettingGroup
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.Project_CustomAttributes_SettingGroup
  langs:
  - csharp
  - vb
  name: CustomAttributeSettings
  nameWithType: CustomAttributeSettings
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings
  type: Class
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: 'public class CustomAttributeSettings : SettingsGroup'
    content.vb: >-
      Public Class CustomAttributeSettings
          Inherits SettingsGroup
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.CustomAttributes_Setting
  commentId: F:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.CustomAttributes_Setting
  id: CustomAttributes_Setting
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings
  langs:
  - csharp
  - vb
  name: CustomAttributes_Setting
  nameWithType: CustomAttributeSettings.CustomAttributes_Setting
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.CustomAttributes_Setting
  type: Field
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: public const string CustomAttributes_Setting = "CustomAttributes"
    return:
      type: System.String
    content.vb: Public Const CustomAttributes_Setting As String = "CustomAttributes"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.Project_CustomAttributes_SettingGroup
  commentId: F:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.Project_CustomAttributes_SettingGroup
  id: Project_CustomAttributes_SettingGroup
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings
  langs:
  - csharp
  - vb
  name: Project_CustomAttributes_SettingGroup
  nameWithType: CustomAttributeSettings.Project_CustomAttributes_SettingGroup
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.Project_CustomAttributes_SettingGroup
  type: Field
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: public const string Project_CustomAttributes_SettingGroup = "ProjectCustomAttributeSettings"
    return:
      type: System.String
    content.vb: Public Const Project_CustomAttributes_SettingGroup As String = "ProjectCustomAttributeSettings"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.File_CustomAttributes_SettingGroup
  commentId: F:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.File_CustomAttributes_SettingGroup
  id: File_CustomAttributes_SettingGroup
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings
  langs:
  - csharp
  - vb
  name: File_CustomAttributes_SettingGroup
  nameWithType: CustomAttributeSettings.File_CustomAttributes_SettingGroup
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.File_CustomAttributes_SettingGroup
  type: Field
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: public const string File_CustomAttributes_SettingGroup = "FileCustomAttributeSettings"
    return:
      type: System.String
    content.vb: Public Const File_CustomAttributes_SettingGroup As String = "FileCustomAttributeSettings"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.#ctor
  commentId: M:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.#ctor
  id: '#ctor'
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings
  langs:
  - csharp
  - vb
  name: CustomAttributeSettings()
  nameWithType: CustomAttributeSettings.CustomAttributeSettings()
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.CustomAttributeSettings()
  type: Constructor
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: public CustomAttributeSettings()
    content.vb: Public Sub New
  overload: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.Attributes
  commentId: P:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.Attributes
  id: Attributes
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings
  langs:
  - csharp
  - vb
  name: Attributes
  nameWithType: CustomAttributeSettings.Attributes
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.Attributes
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: public CustomAttributeList Attributes { get; set; }
    parameters: []
    return:
      type: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeList
    content.vb: Public Property Attributes As CustomAttributeList
  overload: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.Attributes*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes
  commentId: N:Sdl.ProjectAutomation.Settings.CustomAttributes
  isExternal: true
  name: Sdl.ProjectAutomation.Settings.CustomAttributes
  nameWithType: Sdl.ProjectAutomation.Settings.CustomAttributes
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.#ctor*
  commentId: Overload:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.#ctor
  isExternal: true
  name: CustomAttributeSettings
  nameWithType: CustomAttributeSettings.CustomAttributeSettings
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.CustomAttributeSettings
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.Attributes*
  commentId: Overload:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.Attributes
  isExternal: true
  name: Attributes
  nameWithType: CustomAttributeSettings.Attributes
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.Attributes
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeList
  commentId: T:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeList
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes
  isExternal: true
  name: CustomAttributeList
  nameWithType: CustomAttributeList
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeList
