### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.AppendToUnitType
  commentId: T:Sdl.ProjectAutomation.Settings.AppendToUnitType
  id: AppendToUnitType
  parent: Sdl.ProjectAutomation.Settings
  children:
  - Sdl.ProjectAutomation.Settings.AppendToUnitType.Paragraph
  - Sdl.ProjectAutomation.Settings.AppendToUnitType.Segment
  langs:
  - csharp
  - vb
  name: AppendToUnitType
  nameWithType: AppendToUnitType
  fullName: Sdl.ProjectAutomation.Settings.AppendToUnitType
  type: Enum
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: >-
    To specify whether <xref href="Sdl.ProjectAutomation.Settings.PseudoTranslateSettings.AppendStartString" data-throw-if-not-resolved="false"></xref> and

    <xref href="Sdl.ProjectAutomation.Settings.PseudoTranslateSettings.AppendEndString" data-throw-if-not-resolved="false"></xref> are applied at the segment or paragraph level.
  example: []
  syntax:
    content: public enum AppendToUnitType
    content.vb: Public Enum AppendToUnitType
- uid: Sdl.ProjectAutomation.Settings.AppendToUnitType.Segment
  commentId: F:Sdl.ProjectAutomation.Settings.AppendToUnitType.Segment
  id: Segment
  parent: Sdl.ProjectAutomation.Settings.AppendToUnitType
  langs:
  - csharp
  - vb
  name: Segment
  nameWithType: AppendToUnitType.Segment
  fullName: Sdl.ProjectAutomation.Settings.AppendToUnitType.Segment
  type: Field
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: >-
    Apply <xref href="Sdl.ProjectAutomation.Settings.PseudoTranslateSettings.AppendStartString" data-throw-if-not-resolved="false"></xref> and <xref href="Sdl.ProjectAutomation.Settings.PseudoTranslateSettings.AppendEndString" data-throw-if-not-resolved="false"></xref>

    to each segment
  example: []
  syntax:
    content: Segment = 0
    return:
      type: Sdl.ProjectAutomation.Settings.AppendToUnitType
- uid: Sdl.ProjectAutomation.Settings.AppendToUnitType.Paragraph
  commentId: F:Sdl.ProjectAutomation.Settings.AppendToUnitType.Paragraph
  id: Paragraph
  parent: Sdl.ProjectAutomation.Settings.AppendToUnitType
  langs:
  - csharp
  - vb
  name: Paragraph
  nameWithType: AppendToUnitType.Paragraph
  fullName: Sdl.ProjectAutomation.Settings.AppendToUnitType.Paragraph
  type: Field
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: >-
    Apply <xref href="Sdl.ProjectAutomation.Settings.PseudoTranslateSettings.AppendStartString" data-throw-if-not-resolved="false"></xref> and <xref href="Sdl.ProjectAutomation.Settings.PseudoTranslateSettings.AppendEndString" data-throw-if-not-resolved="false"></xref>

    to each paragraph (not each segment)
  example: []
  syntax:
    content: Paragraph = 1
    return:
      type: Sdl.ProjectAutomation.Settings.AppendToUnitType
references:
- uid: Sdl.ProjectAutomation.Settings.PseudoTranslateSettings.AppendStartString
  commentId: P:Sdl.ProjectAutomation.Settings.PseudoTranslateSettings.AppendStartString
  isExternal: true
  href: Sdl.ProjectAutomation.Settings.PseudoTranslateSettings.html#Sdl_ProjectAutomation_Settings_PseudoTranslateSettings_AppendStartString
  name: AppendStartString
  nameWithType: PseudoTranslateSettings.AppendStartString
  fullName: Sdl.ProjectAutomation.Settings.PseudoTranslateSettings.AppendStartString
- uid: Sdl.ProjectAutomation.Settings.PseudoTranslateSettings.AppendEndString
  commentId: P:Sdl.ProjectAutomation.Settings.PseudoTranslateSettings.AppendEndString
  isExternal: true
  href: Sdl.ProjectAutomation.Settings.PseudoTranslateSettings.html#Sdl_ProjectAutomation_Settings_PseudoTranslateSettings_AppendEndString
  name: AppendEndString
  nameWithType: PseudoTranslateSettings.AppendEndString
  fullName: Sdl.ProjectAutomation.Settings.PseudoTranslateSettings.AppendEndString
- uid: Sdl.ProjectAutomation.Settings
  commentId: N:Sdl.ProjectAutomation.Settings
  isExternal: true
  href: Sdl.html
  name: Sdl.ProjectAutomation.Settings
  nameWithType: Sdl.ProjectAutomation.Settings
  fullName: Sdl.ProjectAutomation.Settings
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.ProjectAutomation
    name: ProjectAutomation
    isExternal: true
    href: Sdl.ProjectAutomation.html
  - name: .
  - uid: Sdl.ProjectAutomation.Settings
    name: Settings
    isExternal: true
    href: Sdl.ProjectAutomation.Settings.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.ProjectAutomation
    name: ProjectAutomation
    isExternal: true
    href: Sdl.ProjectAutomation.html
  - name: .
  - uid: Sdl.ProjectAutomation.Settings
    name: Settings
    isExternal: true
    href: Sdl.ProjectAutomation.Settings.html
- uid: Sdl.ProjectAutomation.Settings.AppendToUnitType
  commentId: T:Sdl.ProjectAutomation.Settings.AppendToUnitType
  parent: Sdl.ProjectAutomation.Settings
  isExternal: true
  href: Sdl.ProjectAutomation.Settings.AppendToUnitType.html
  name: AppendToUnitType
  nameWithType: AppendToUnitType
  fullName: Sdl.ProjectAutomation.Settings.AppendToUnitType
