### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes
  commentId: N:Sdl.ProjectAutomation.Settings.CustomAttributes
  id: Sdl.ProjectAutomation.Settings.CustomAttributes
  children:
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CDataWrapper
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeList
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
  langs:
  - csharp
  - vb
  name: Sdl.ProjectAutomation.Settings.CustomAttributes
  nameWithType: Sdl.ProjectAutomation.Settings.CustomAttributes
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes
  type: Namespace
  assemblies:
  - Sdl.ProjectAutomation.Settings
references:
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CDataWrapper
  commentId: T:Sdl.ProjectAutomation.Settings.CustomAttributes.CDataWrapper
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes
  isExternal: true
  href: Sdl.ProjectAutomation.Settings.CustomAttributes.CDataWrapper.html
  name: CDataWrapper
  nameWithType: CDataWrapper
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CDataWrapper
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute
  commentId: T:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute
  isExternal: true
  href: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute.html
  name: CustomAttribute
  nameWithType: CustomAttribute
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttribute
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeList
  commentId: T:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeList
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes
  isExternal: true
  href: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeList.html
  name: CustomAttributeList
  nameWithType: CustomAttributeList
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeList
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings
  commentId: T:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings
  isExternal: true
  href: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings.html
  name: CustomAttributeSettings
  nameWithType: CustomAttributeSettings
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeSettings
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
  commentId: T:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes
  isExternal: true
  href: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.html
  name: CustomAttributeTypeEnum
  nameWithType: CustomAttributeTypeEnum
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes
  commentId: N:Sdl.ProjectAutomation.Settings.CustomAttributes
  isExternal: true
  href: Sdl.html
  name: Sdl.ProjectAutomation.Settings.CustomAttributes
  nameWithType: Sdl.ProjectAutomation.Settings.CustomAttributes
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.ProjectAutomation
    name: ProjectAutomation
    isExternal: true
    href: Sdl.ProjectAutomation.html
  - name: .
  - uid: Sdl.ProjectAutomation.Settings
    name: Settings
    isExternal: true
    href: Sdl.ProjectAutomation.Settings.html
  - name: .
  - uid: Sdl.ProjectAutomation.Settings.CustomAttributes
    name: CustomAttributes
    isExternal: true
    href: Sdl.ProjectAutomation.Settings.CustomAttributes.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.ProjectAutomation
    name: ProjectAutomation
    isExternal: true
    href: Sdl.ProjectAutomation.html
  - name: .
  - uid: Sdl.ProjectAutomation.Settings
    name: Settings
    isExternal: true
    href: Sdl.ProjectAutomation.Settings.html
  - name: .
  - uid: Sdl.ProjectAutomation.Settings.CustomAttributes
    name: CustomAttributes
    isExternal: true
    href: Sdl.ProjectAutomation.Settings.CustomAttributes.html
