### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration
  commentId: T:Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration
  id: ProjectFileTypeConfiguration
  parent: Sdl.ProjectAutomation.Core
  children:
  - Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FileTypeManagerConfiguration
  - Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FilterManager
  - Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.StandardFilterManager
  - Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.SubContentFileTypeManagerConfiguration
  langs:
  - csharp
  - vb
  name: ProjectFileTypeConfiguration
  nameWithType: ProjectFileTypeConfiguration
  fullName: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration
  type: Class
  source:
    path: Sdl.ProjectAutomation.Core
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Core
  namespace: Sdl.ProjectAutomation.Core
  syntax:
    content: public class ProjectFileTypeConfiguration
    content.vb: Public Class ProjectFileTypeConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FilterManager
  commentId: P:Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FilterManager
  id: FilterManager
  parent: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration
  langs:
  - csharp
  - vb
  name: FilterManager
  nameWithType: ProjectFileTypeConfiguration.FilterManager
  fullName: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FilterManager
  type: Property
  source:
    path: Sdl.ProjectAutomation.Core
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Core
  namespace: Sdl.ProjectAutomation.Core
  syntax:
    content: public IFileTypeManager FilterManager { get; }
    parameters: []
    return:
      type: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeManager
    content.vb: Public ReadOnly Property FilterManager As IFileTypeManager
  overload: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FilterManager*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.StandardFilterManager
  commentId: P:Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.StandardFilterManager
  id: StandardFilterManager
  parent: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration
  langs:
  - csharp
  - vb
  name: StandardFilterManager
  nameWithType: ProjectFileTypeConfiguration.StandardFilterManager
  fullName: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.StandardFilterManager
  type: Property
  source:
    path: Sdl.ProjectAutomation.Core
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Core
  namespace: Sdl.ProjectAutomation.Core
  syntax:
    content: public IFileTypeManager StandardFilterManager { get; }
    parameters: []
    return:
      type: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeManager
    content.vb: Public ReadOnly Property StandardFilterManager As IFileTypeManager
  overload: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.StandardFilterManager*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FileTypeManagerConfiguration
  commentId: P:Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FileTypeManagerConfiguration
  id: FileTypeManagerConfiguration
  parent: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration
  langs:
  - csharp
  - vb
  name: FileTypeManagerConfiguration
  nameWithType: ProjectFileTypeConfiguration.FileTypeManagerConfiguration
  fullName: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FileTypeManagerConfiguration
  type: Property
  source:
    path: Sdl.ProjectAutomation.Core
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Core
  namespace: Sdl.ProjectAutomation.Core
  syntax:
    content: public IFileTypeManagerConfiguration FileTypeManagerConfiguration { get; }
    parameters: []
    return:
      type: Sdl.ProjectApi.IFileTypeManagerConfiguration
    content.vb: Public ReadOnly Property FileTypeManagerConfiguration As IFileTypeManagerConfiguration
  overload: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FileTypeManagerConfiguration*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.SubContentFileTypeManagerConfiguration
  commentId: P:Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.SubContentFileTypeManagerConfiguration
  id: SubContentFileTypeManagerConfiguration
  parent: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration
  langs:
  - csharp
  - vb
  name: SubContentFileTypeManagerConfiguration
  nameWithType: ProjectFileTypeConfiguration.SubContentFileTypeManagerConfiguration
  fullName: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.SubContentFileTypeManagerConfiguration
  type: Property
  source:
    path: Sdl.ProjectAutomation.Core
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Core
  namespace: Sdl.ProjectAutomation.Core
  syntax:
    content: public IFileTypeManagerConfiguration SubContentFileTypeManagerConfiguration { get; }
    parameters: []
    return:
      type: Sdl.ProjectApi.IFileTypeManagerConfiguration
    content.vb: Public ReadOnly Property SubContentFileTypeManagerConfiguration As IFileTypeManagerConfiguration
  overload: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.SubContentFileTypeManagerConfiguration*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Sdl.ProjectAutomation.Core
  commentId: N:Sdl.ProjectAutomation.Core
  isExternal: true
  name: Sdl.ProjectAutomation.Core
  nameWithType: Sdl.ProjectAutomation.Core
  fullName: Sdl.ProjectAutomation.Core
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FilterManager*
  commentId: Overload:Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FilterManager
  isExternal: true
  name: FilterManager
  nameWithType: ProjectFileTypeConfiguration.FilterManager
  fullName: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FilterManager
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeManager
  isExternal: true
  name: IFileTypeManager
  nameWithType: IFileTypeManager
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeManager
- uid: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.StandardFilterManager*
  commentId: Overload:Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.StandardFilterManager
  isExternal: true
  name: StandardFilterManager
  nameWithType: ProjectFileTypeConfiguration.StandardFilterManager
  fullName: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.StandardFilterManager
- uid: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FileTypeManagerConfiguration*
  commentId: Overload:Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FileTypeManagerConfiguration
  isExternal: true
  name: FileTypeManagerConfiguration
  nameWithType: ProjectFileTypeConfiguration.FileTypeManagerConfiguration
  fullName: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.FileTypeManagerConfiguration
- uid: Sdl.ProjectApi.IFileTypeManagerConfiguration
  isExternal: true
  name: IFileTypeManagerConfiguration
  nameWithType: IFileTypeManagerConfiguration
  fullName: Sdl.ProjectApi.IFileTypeManagerConfiguration
- uid: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.SubContentFileTypeManagerConfiguration*
  commentId: Overload:Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.SubContentFileTypeManagerConfiguration
  isExternal: true
  name: SubContentFileTypeManagerConfiguration
  nameWithType: ProjectFileTypeConfiguration.SubContentFileTypeManagerConfiguration
  fullName: Sdl.ProjectAutomation.Core.ProjectFileTypeConfiguration.SubContentFileTypeManagerConfiguration
