### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
  commentId: T:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
  id: CustomAttributeTypeEnum
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes
  children:
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Attachment
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Bool
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Date
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Html
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Int
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.List
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.String
  - Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Url
  langs:
  - csharp
  - vb
  name: CustomAttributeTypeEnum
  nameWithType: CustomAttributeTypeEnum
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
  type: Enum
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: public enum CustomAttributeTypeEnum
    content.vb: Public Enum CustomAttributeTypeEnum
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Int
  commentId: F:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Int
  id: Int
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
  langs:
  - csharp
  - vb
  name: Int
  nameWithType: CustomAttributeTypeEnum.Int
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Int
  type: Field
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: Int = 0
    return:
      type: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.String
  commentId: F:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.String
  id: String
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
  langs:
  - csharp
  - vb
  name: String
  nameWithType: CustomAttributeTypeEnum.String
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.String
  type: Field
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: String = 1
    return:
      type: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Bool
  commentId: F:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Bool
  id: Bool
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
  langs:
  - csharp
  - vb
  name: Bool
  nameWithType: CustomAttributeTypeEnum.Bool
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Bool
  type: Field
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: Bool = 2
    return:
      type: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Date
  commentId: F:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Date
  id: Date
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
  langs:
  - csharp
  - vb
  name: Date
  nameWithType: CustomAttributeTypeEnum.Date
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Date
  type: Field
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: Date = 3
    return:
      type: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Attachment
  commentId: F:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Attachment
  id: Attachment
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
  langs:
  - csharp
  - vb
  name: Attachment
  nameWithType: CustomAttributeTypeEnum.Attachment
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Attachment
  type: Field
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: Attachment = 4
    return:
      type: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Html
  commentId: F:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Html
  id: Html
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
  langs:
  - csharp
  - vb
  name: Html
  nameWithType: CustomAttributeTypeEnum.Html
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Html
  type: Field
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: Html = 5
    return:
      type: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Url
  commentId: F:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Url
  id: Url
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
  langs:
  - csharp
  - vb
  name: Url
  nameWithType: CustomAttributeTypeEnum.Url
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.Url
  type: Field
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: Url = 6
    return:
      type: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.List
  commentId: F:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.List
  id: List
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
  langs:
  - csharp
  - vb
  name: List
  nameWithType: CustomAttributeTypeEnum.List
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.List
  type: Field
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings.CustomAttributes
  syntax:
    content: List = 7
    return:
      type: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
references:
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes
  commentId: N:Sdl.ProjectAutomation.Settings.CustomAttributes
  isExternal: true
  href: Sdl.html
  name: Sdl.ProjectAutomation.Settings.CustomAttributes
  nameWithType: Sdl.ProjectAutomation.Settings.CustomAttributes
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.ProjectAutomation
    name: ProjectAutomation
    isExternal: true
    href: Sdl.ProjectAutomation.html
  - name: .
  - uid: Sdl.ProjectAutomation.Settings
    name: Settings
    isExternal: true
    href: Sdl.ProjectAutomation.Settings.html
  - name: .
  - uid: Sdl.ProjectAutomation.Settings.CustomAttributes
    name: CustomAttributes
    isExternal: true
    href: Sdl.ProjectAutomation.Settings.CustomAttributes.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.ProjectAutomation
    name: ProjectAutomation
    isExternal: true
    href: Sdl.ProjectAutomation.html
  - name: .
  - uid: Sdl.ProjectAutomation.Settings
    name: Settings
    isExternal: true
    href: Sdl.ProjectAutomation.Settings.html
  - name: .
  - uid: Sdl.ProjectAutomation.Settings.CustomAttributes
    name: CustomAttributes
    isExternal: true
    href: Sdl.ProjectAutomation.Settings.CustomAttributes.html
- uid: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
  commentId: T:Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
  parent: Sdl.ProjectAutomation.Settings.CustomAttributes
  isExternal: true
  href: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum.html
  name: CustomAttributeTypeEnum
  nameWithType: CustomAttributeTypeEnum
  fullName: Sdl.ProjectAutomation.Settings.CustomAttributes.CustomAttributeTypeEnum
