### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl
  commentId: T:Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl
  id: IFileTypeDefinitionConfiguringControl
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi
  children:
  - Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.FileTypeDefintionId
  - Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.Save
  langs:
  - csharp
  - vb
  name: IFileTypeDefinitionConfiguringControl
  nameWithType: IFileTypeDefinitionConfiguringControl
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl
  type: Interface
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.IntegrationApi
  summary: Used by the Configuration Wizard to save the state of a control
  example: []
  syntax:
    content: public interface IFileTypeDefinitionConfiguringControl
    content.vb: Public Interface IFileTypeDefinitionConfiguringControl
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.Save
  commentId: M:Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.Save
  id: Save
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl
  langs:
  - csharp
  - vb
  name: Save()
  nameWithType: IFileTypeDefinitionConfiguringControl.Save()
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.Save()
  type: Method
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.IntegrationApi
  summary: Saves the control's state to the underlying settings implementation
  example: []
  syntax:
    content: bool Save()
    return:
      type: System.Boolean
      description: true if successful, false otherwise
    content.vb: Function Save() As Boolean
  overload: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.Save*
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.FileTypeDefintionId
  commentId: P:Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.FileTypeDefintionId
  id: FileTypeDefintionId
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl
  langs:
  - csharp
  - vb
  name: FileTypeDefintionId
  nameWithType: IFileTypeDefinitionConfiguringControl.FileTypeDefintionId
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.FileTypeDefintionId
  type: Property
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.IntegrationApi
  summary: Sets the FileTypeDefinitionId for use with underlying settings implementation
  example: []
  syntax:
    content: FileTypeDefinitionId FileTypeDefintionId { set; }
    parameters: []
    return:
      type: Sdl.FileTypeSupport.Framework.FileTypeDefinitionId
    content.vb: WriteOnly Property FileTypeDefintionId As FileTypeDefinitionId
  overload: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.FileTypeDefintionId*
references:
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi
  commentId: N:Sdl.FileTypeSupport.Framework.IntegrationApi
  isExternal: true
  href: Sdl.html
  name: Sdl.FileTypeSupport.Framework.IntegrationApi
  nameWithType: Sdl.FileTypeSupport.Framework.IntegrationApi
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi
    name: IntegrationApi
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi
    name: IntegrationApi
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.html
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.Save*
  commentId: Overload:Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.Save
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IFileTypeDefinitionConfiguringControl_Save
  name: Save
  nameWithType: IFileTypeDefinitionConfiguringControl.Save
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.Save
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.FileTypeDefintionId*
  commentId: Overload:Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.FileTypeDefintionId
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IFileTypeDefinitionConfiguringControl_FileTypeDefintionId
  name: FileTypeDefintionId
  nameWithType: IFileTypeDefinitionConfiguringControl.FileTypeDefintionId
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinitionConfiguringControl.FileTypeDefintionId
- uid: Sdl.FileTypeSupport.Framework.FileTypeDefinitionId
  commentId: T:Sdl.FileTypeSupport.Framework.FileTypeDefinitionId
  parent: Sdl.FileTypeSupport.Framework
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.FileTypeDefinitionId.html
  name: FileTypeDefinitionId
  nameWithType: FileTypeDefinitionId
  fullName: Sdl.FileTypeSupport.Framework.FileTypeDefinitionId
- uid: Sdl.FileTypeSupport.Framework
  commentId: N:Sdl.FileTypeSupport.Framework
  isExternal: true
  href: Sdl.html
  name: Sdl.FileTypeSupport.Framework
  nameWithType: Sdl.FileTypeSupport.Framework
  fullName: Sdl.FileTypeSupport.Framework
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
