### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo
  id: DeserializeFileInfo
  parent: Sdl.FileTypeSupport.Framework.Core.Settings
  children:
  - Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.#ctor(System.Boolean,System.Boolean,System.String)
  - Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.FullPath
  - Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.IsDirectoryCreated
  - Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.IsFileCreated
  langs:
  - csharp
  - vb
  name: DeserializeFileInfo
  nameWithType: DeserializeFileInfo
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo
  type: Class
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: Provides information on the file that was deserialized
  example: []
  syntax:
    content: public class DeserializeFileInfo
    content.vb: Public Class DeserializeFileInfo
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.#ctor(System.Boolean,System.Boolean,System.String)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.#ctor(System.Boolean,System.Boolean,System.String)
  id: '#ctor(System.Boolean,System.Boolean,System.String)'
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo
  langs:
  - csharp
  - vb
  name: DeserializeFileInfo(bool, bool, string)
  nameWithType: DeserializeFileInfo.DeserializeFileInfo(bool, bool, string)
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.DeserializeFileInfo(bool, bool, string)
  type: Constructor
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: Constructor
  example: []
  syntax:
    content: public DeserializeFileInfo(bool isFileCreated, bool isDirectoryCreated, string fullPath)
    parameters:
    - id: isFileCreated
      type: System.Boolean
      description: ''
    - id: isDirectoryCreated
      type: System.Boolean
      description: ''
    - id: fullPath
      type: System.String
      description: ''
    content.vb: Public Sub New(isFileCreated As Boolean, isDirectoryCreated As Boolean, fullPath As String)
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.#ctor*
  nameWithType.vb: DeserializeFileInfo.New(Boolean, Boolean, String)
  fullName.vb: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.New(Boolean, Boolean, String)
  name.vb: New(Boolean, Boolean, String)
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.IsFileCreated
  commentId: P:Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.IsFileCreated
  id: IsFileCreated
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo
  langs:
  - csharp
  - vb
  name: IsFileCreated
  nameWithType: DeserializeFileInfo.IsFileCreated
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.IsFileCreated
  type: Property
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: Indicates whether the file was created successfully
  example: []
  syntax:
    content: public bool IsFileCreated { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public ReadOnly Property IsFileCreated As Boolean
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.IsFileCreated*
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.IsDirectoryCreated
  commentId: P:Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.IsDirectoryCreated
  id: IsDirectoryCreated
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo
  langs:
  - csharp
  - vb
  name: IsDirectoryCreated
  nameWithType: DeserializeFileInfo.IsDirectoryCreated
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.IsDirectoryCreated
  type: Property
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: Indicates whether the current directory had to be created especially for this file
  example: []
  syntax:
    content: public bool IsDirectoryCreated { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public ReadOnly Property IsDirectoryCreated As Boolean
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.IsDirectoryCreated*
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.FullPath
  commentId: P:Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.FullPath
  id: FullPath
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo
  langs:
  - csharp
  - vb
  name: FullPath
  nameWithType: DeserializeFileInfo.FullPath
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.FullPath
  type: Property
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings
  summary: The full path to the file that was created
  example: []
  syntax:
    content: public string FullPath { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property FullPath As String
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.FullPath*
references:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings
  isExternal: true
  href: Sdl.html
  name: Sdl.FileTypeSupport.Framework.Core.Settings
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core
    name: Core
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings
    name: Settings
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.Settings.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core
    name: Core
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings
    name: Settings
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.#ctor*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.#ctor
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.html#Sdl_FileTypeSupport_Framework_Core_Settings_DeserializeFileInfo__ctor_System_Boolean_System_Boolean_System_String_
  name: DeserializeFileInfo
  nameWithType: DeserializeFileInfo.DeserializeFileInfo
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.DeserializeFileInfo
  nameWithType.vb: DeserializeFileInfo.New
  fullName.vb: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.New
  name.vb: New
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.IsFileCreated*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.IsFileCreated
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.html#Sdl_FileTypeSupport_Framework_Core_Settings_DeserializeFileInfo_IsFileCreated
  name: IsFileCreated
  nameWithType: DeserializeFileInfo.IsFileCreated
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.IsFileCreated
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.IsDirectoryCreated*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.IsDirectoryCreated
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.html#Sdl_FileTypeSupport_Framework_Core_Settings_DeserializeFileInfo_IsDirectoryCreated
  name: IsDirectoryCreated
  nameWithType: DeserializeFileInfo.IsDirectoryCreated
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.IsDirectoryCreated
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.FullPath*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.FullPath
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.html#Sdl_FileTypeSupport_Framework_Core_Settings_DeserializeFileInfo_FullPath
  name: FullPath
  nameWithType: DeserializeFileInfo.FullPath
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.DeserializeFileInfo.FullPath
