### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.ISettingsAware
  commentId: T:Sdl.FileTypeSupport.Framework.IntegrationApi.ISettingsAware
  id: ISettingsAware
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi
  children:
  - Sdl.FileTypeSupport.Framework.IntegrationApi.ISettingsAware.InitializeSettings(Sdl.Core.Settings.ISettingsBundle,System.String)
  langs:
  - csharp
  - vb
  name: ISettingsAware
  nameWithType: ISettingsAware
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.ISettingsAware
  type: Interface
  source:
    path: Sdl.FileTypeSupport.Framework.Core
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.IntegrationApi
  summary: "\nThis interface should be implemented by components which need to be aware of a\nparticular settings group in order to read their settings from this group\n(during extraction or generation).\n"
  syntax:
    content: public interface ISettingsAware
    content.vb: Public Interface ISettingsAware
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.ISettingsAware.InitializeSettings(Sdl.Core.Settings.ISettingsBundle,System.String)
  commentId: M:Sdl.FileTypeSupport.Framework.IntegrationApi.ISettingsAware.InitializeSettings(Sdl.Core.Settings.ISettingsBundle,System.String)
  id: InitializeSettings(Sdl.Core.Settings.ISettingsBundle,System.String)
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.ISettingsAware
  langs:
  - csharp
  - vb
  name: InitializeSettings(ISettingsBundle, String)
  nameWithType: ISettingsAware.InitializeSettings(ISettingsBundle, String)
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.ISettingsAware.InitializeSettings(Sdl.Core.Settings.ISettingsBundle, System.String)
  type: Method
  source:
    path: Sdl.FileTypeSupport.Framework.Core
    isExternal: true
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.IntegrationApi
  summary: "\nProvides the component with the settings information it needs to initialize its settings.\n"
  syntax:
    content: void InitializeSettings(ISettingsBundle settingsBundle, string configurationId)
    parameters:
    - id: settingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
      description: Used for setting the settings bundle on the component.
    - id: configurationId
      type: System.String
      description: "The suggested configuration ID to use when retrieving the\nsettings group from the <xref href=\"Sdl.Core.Settings.ISettingsBundle\" data-throw-if-not-resolved=\"false\"></xref> and directly relates to the settings group ID.\nThis does not have to be used if a component needs to self-manage its configuration ID and may be \n<code>null</code> if the component does not belong in the processing chain of a specific filter."
    content.vb: Sub InitializeSettings(settingsBundle As ISettingsBundle, configurationId As String)
  overload: Sdl.FileTypeSupport.Framework.IntegrationApi.ISettingsAware.InitializeSettings*
references:
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi
  commentId: N:Sdl.FileTypeSupport.Framework.IntegrationApi
  isExternal: true
  name: Sdl.FileTypeSupport.Framework.IntegrationApi
  nameWithType: Sdl.FileTypeSupport.Framework.IntegrationApi
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.ISettingsAware.InitializeSettings*
  commentId: Overload:Sdl.FileTypeSupport.Framework.IntegrationApi.ISettingsAware.InitializeSettings
  isExternal: true
  name: InitializeSettings
  nameWithType: ISettingsAware.InitializeSettings
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.ISettingsAware.InitializeSettings
- uid: Sdl.Core.Settings.ISettingsBundle
  isExternal: true
  name: ISettingsBundle
  nameWithType: ISettingsBundle
  fullName: Sdl.Core.Settings.ISettingsBundle
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
