### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  id: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  children:
  - Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.AbstractSettingsClass
  - Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.GenericFileTypeSettingsConverter
  - Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass
  - Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueGetter
  - Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueProcessor
  - Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod
  - Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsFormatConverter
  langs:
  - csharp
  - vb
  name: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  type: Namespace
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
references:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.AbstractSettingsClass
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.AbstractSettingsClass
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.AbstractSettingsClass.html
  name: AbstractSettingsClass
  nameWithType: AbstractSettingsClass
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.AbstractSettingsClass
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.html
  name: SettingsBundleConverterMethod
  nameWithType: SettingsBundleConverterMethod
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.GenericFileTypeSettingsConverter
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.GenericFileTypeSettingsConverter
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.GenericFileTypeSettingsConverter.html
  name: GenericFileTypeSettingsConverter
  nameWithType: GenericFileTypeSettingsConverter
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.GenericFileTypeSettingsConverter
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass.html
  name: ISettingsClass
  nameWithType: ISettingsClass
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.ISettingsClass
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueGetter
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueGetter
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueGetter.html
  name: IValueGetter
  nameWithType: IValueGetter
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueGetter
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueProcessor
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueProcessor
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueProcessor.html
  name: IValueProcessor
  nameWithType: IValueProcessor
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.IValueProcessor
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsFormatConverter
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsFormatConverter
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsFormatConverter.html
  name: SettingsFormatConverter
  nameWithType: SettingsFormatConverter
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsFormatConverter
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  isExternal: true
  href: Sdl.html
  name: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core
    name: Core
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings
    name: Settings
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.Settings.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
    name: Serialization
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core
    name: Core
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings
    name: Settings
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.Settings.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
    name: Serialization
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.html
