### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  id: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  children:
  - Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings.FileTypeSettingsJson
  - Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings.FileTypeSettingsUtil
  langs:
  - csharp
  - vb
  name: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  type: Namespace
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
references:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings.FileTypeSettingsJson
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings.FileTypeSettingsJson
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings.FileTypeSettingsJson.html
  name: FileTypeSettingsJson
  nameWithType: FileTypeSettingsJson
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings.FileTypeSettingsJson
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings.FileTypeSettingsUtil
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings.FileTypeSettingsUtil
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings.FileTypeSettingsUtil.html
  name: FileTypeSettingsUtil
  nameWithType: FileTypeSettingsUtil
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings.FileTypeSettingsUtil
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  isExternal: true
  href: Sdl.html
  name: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core
    name: Core
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings
    name: Settings
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.Settings.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
    name: JsonSettings
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core
    name: Core
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings
    name: Settings
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.Settings.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings
    name: JsonSettings
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.Settings.JsonSettings.html
