### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod
  id: SettingsBundleConverterMethod
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  children:
  - Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.#ctor(System.Object,System.IntPtr)
  - Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.BeginInvoke(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String,System.AsyncCallback,System.Object)
  - Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.EndInvoke(System.IAsyncResult)
  - Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.Invoke(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String)
  langs:
  - csharp
  - vb
  name: SettingsBundleConverterMethod
  nameWithType: SettingsBundleConverterMethod
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod
  type: Delegate
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  syntax:
    content: public delegate void SettingsBundleConverterMethod(ISettingsBundle sourceSettingsBundle, ISettingsBundle targetSettingsBundle, string fileTypeId)
    parameters:
    - id: sourceSettingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
    - id: targetSettingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
    - id: fileTypeId
      type: System.String
    content.vb: Public Delegate Sub SettingsBundleConverterMethod(sourceSettingsBundle As ISettingsBundle, targetSettingsBundle As ISettingsBundle, fileTypeId As String)
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.#ctor(System.Object,System.IntPtr)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.#ctor(System.Object,System.IntPtr)
  id: '#ctor(System.Object,System.IntPtr)'
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod
  langs:
  - csharp
  - vb
  name: SettingsBundleConverterMethod(object, IntPtr)
  nameWithType: SettingsBundleConverterMethod.SettingsBundleConverterMethod(object, IntPtr)
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.SettingsBundleConverterMethod(object, System.IntPtr)
  type: Constructor
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  syntax:
    content: public SettingsBundleConverterMethod(object @object, IntPtr method)
    parameters:
    - id: object
      type: System.Object
    - id: method
      type: System.IntPtr
    content.vb: Public Sub New([object] As Object, method As IntPtr)
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.#ctor*
  nameWithType.vb: SettingsBundleConverterMethod.New(Object, IntPtr)
  fullName.vb: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.New(Object, System.IntPtr)
  name.vb: New(Object, IntPtr)
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.Invoke(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.Invoke(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String)
  id: Invoke(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String)
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod
  langs:
  - csharp
  - vb
  name: Invoke(ISettingsBundle, ISettingsBundle, string)
  nameWithType: SettingsBundleConverterMethod.Invoke(ISettingsBundle, ISettingsBundle, string)
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.Invoke(Sdl.Core.Settings.ISettingsBundle, Sdl.Core.Settings.ISettingsBundle, string)
  type: Method
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  syntax:
    content: public virtual void Invoke(ISettingsBundle sourceSettingsBundle, ISettingsBundle targetSettingsBundle, string fileTypeId)
    parameters:
    - id: sourceSettingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
    - id: targetSettingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
    - id: fileTypeId
      type: System.String
    content.vb: Public Overridable Sub Invoke(sourceSettingsBundle As ISettingsBundle, targetSettingsBundle As ISettingsBundle, fileTypeId As String)
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.Invoke*
  nameWithType.vb: SettingsBundleConverterMethod.Invoke(ISettingsBundle, ISettingsBundle, String)
  fullName.vb: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.Invoke(Sdl.Core.Settings.ISettingsBundle, Sdl.Core.Settings.ISettingsBundle, String)
  name.vb: Invoke(ISettingsBundle, ISettingsBundle, String)
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.BeginInvoke(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String,System.AsyncCallback,System.Object)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.BeginInvoke(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String,System.AsyncCallback,System.Object)
  id: BeginInvoke(Sdl.Core.Settings.ISettingsBundle,Sdl.Core.Settings.ISettingsBundle,System.String,System.AsyncCallback,System.Object)
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod
  langs:
  - csharp
  - vb
  name: BeginInvoke(ISettingsBundle, ISettingsBundle, string, AsyncCallback, object)
  nameWithType: SettingsBundleConverterMethod.BeginInvoke(ISettingsBundle, ISettingsBundle, string, AsyncCallback, object)
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.BeginInvoke(Sdl.Core.Settings.ISettingsBundle, Sdl.Core.Settings.ISettingsBundle, string, System.AsyncCallback, object)
  type: Method
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  syntax:
    content: public virtual IAsyncResult BeginInvoke(ISettingsBundle sourceSettingsBundle, ISettingsBundle targetSettingsBundle, string fileTypeId, AsyncCallback callback, object @object)
    parameters:
    - id: sourceSettingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
    - id: targetSettingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
    - id: fileTypeId
      type: System.String
    - id: callback
      type: System.AsyncCallback
    - id: object
      type: System.Object
    return:
      type: System.IAsyncResult
    content.vb: Public Overridable Function BeginInvoke(sourceSettingsBundle As ISettingsBundle, targetSettingsBundle As ISettingsBundle, fileTypeId As String, callback As AsyncCallback, [object] As Object) As IAsyncResult
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.BeginInvoke*
  nameWithType.vb: SettingsBundleConverterMethod.BeginInvoke(ISettingsBundle, ISettingsBundle, String, AsyncCallback, Object)
  fullName.vb: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.BeginInvoke(Sdl.Core.Settings.ISettingsBundle, Sdl.Core.Settings.ISettingsBundle, String, System.AsyncCallback, Object)
  name.vb: BeginInvoke(ISettingsBundle, ISettingsBundle, String, AsyncCallback, Object)
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.EndInvoke(System.IAsyncResult)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.EndInvoke(System.IAsyncResult)
  id: EndInvoke(System.IAsyncResult)
  parent: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod
  langs:
  - csharp
  - vb
  name: EndInvoke(IAsyncResult)
  nameWithType: SettingsBundleConverterMethod.EndInvoke(IAsyncResult)
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.EndInvoke(System.IAsyncResult)
  type: Method
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core.Settings
  namespace: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  syntax:
    content: public virtual void EndInvoke(IAsyncResult result)
    parameters:
    - id: result
      type: System.IAsyncResult
    content.vb: Public Overridable Sub EndInvoke(result As IAsyncResult)
  overload: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.EndInvoke*
references:
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  isExternal: true
  href: Sdl.html
  name: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core
    name: Core
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings
    name: Settings
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.Settings.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
    name: Serialization
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core
    name: Core
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings
    name: Settings
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.Settings.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization
    name: Serialization
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.html
- uid: Sdl.Core.Settings.ISettingsBundle
  commentId: T:Sdl.Core.Settings.ISettingsBundle
  parent: Sdl.Core.Settings
  isExternal: true
  name: ISettingsBundle
  nameWithType: ISettingsBundle
  fullName: Sdl.Core.Settings.ISettingsBundle
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Sdl.Core.Settings
  commentId: N:Sdl.Core.Settings
  isExternal: true
  name: Sdl.Core.Settings
  nameWithType: Sdl.Core.Settings
  fullName: Sdl.Core.Settings
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
  - name: .
  - uid: Sdl.Core
    name: Core
    isExternal: true
  - name: .
  - uid: Sdl.Core.Settings
    name: Settings
    isExternal: true
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
  - name: .
  - uid: Sdl.Core
    name: Core
    isExternal: true
  - name: .
  - uid: Sdl.Core.Settings
    name: Settings
    isExternal: true
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.#ctor*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.#ctor
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.html#Sdl_FileTypeSupport_Framework_Core_Settings_Serialization_SettingsBundleConverterMethod__ctor_System_Object_System_IntPtr_
  name: SettingsBundleConverterMethod
  nameWithType: SettingsBundleConverterMethod.SettingsBundleConverterMethod
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.SettingsBundleConverterMethod
  nameWithType.vb: SettingsBundleConverterMethod.New
  fullName.vb: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.New
  name.vb: New
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.IntPtr
  commentId: T:System.IntPtr
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.intptr
  name: IntPtr
  nameWithType: IntPtr
  fullName: System.IntPtr
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.Invoke*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.Invoke
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.html#Sdl_FileTypeSupport_Framework_Core_Settings_Serialization_SettingsBundleConverterMethod_Invoke_Sdl_Core_Settings_ISettingsBundle_Sdl_Core_Settings_ISettingsBundle_System_String_
  name: Invoke
  nameWithType: SettingsBundleConverterMethod.Invoke
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.Invoke
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.BeginInvoke*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.BeginInvoke
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.html#Sdl_FileTypeSupport_Framework_Core_Settings_Serialization_SettingsBundleConverterMethod_BeginInvoke_Sdl_Core_Settings_ISettingsBundle_Sdl_Core_Settings_ISettingsBundle_System_String_System_AsyncCallback_System_Object_
  name: BeginInvoke
  nameWithType: SettingsBundleConverterMethod.BeginInvoke
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.BeginInvoke
- uid: System.AsyncCallback
  commentId: T:System.AsyncCallback
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.asynccallback
  name: AsyncCallback
  nameWithType: AsyncCallback
  fullName: System.AsyncCallback
- uid: System.IAsyncResult
  commentId: T:System.IAsyncResult
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iasyncresult
  name: IAsyncResult
  nameWithType: IAsyncResult
  fullName: System.IAsyncResult
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.EndInvoke*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.EndInvoke
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.html#Sdl_FileTypeSupport_Framework_Core_Settings_Serialization_SettingsBundleConverterMethod_EndInvoke_System_IAsyncResult_
  name: EndInvoke
  nameWithType: SettingsBundleConverterMethod.EndInvoke
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.Serialization.SettingsBundleConverterMethod.EndInvoke
