### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType
  commentId: T:Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType
  id: IApplicationPreviewType
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi
  children:
  - Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SingleFilePreviewApplicationId
  - Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SourceAndTargetPreviewApplicationId
  langs:
  - csharp
  - vb
  name: IApplicationPreviewType
  nameWithType: IApplicationPreviewType
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType
  type: Interface
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.IntegrationApi
  summary: >-
    Interface implemented by preview types that provide a mechanism

    to launch an external application to view the content.
  remarks: >-
    <p>

    Two types of preview applications can be provided: single file and "source and

    target" (typically side-by-side). The implementation can provide either

    or both of these.

    </p>

    <p>

    Host applications can check these ids to determine which launch

    buttons/tabs should be available in the UI for a specific preview type.

    </p>
  example: []
  syntax:
    content: 'public interface IApplicationPreviewType : IPreviewType'
    content.vb: Public Interface IApplicationPreviewType Inherits IPreviewType
  inheritedMembers:
  - Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType.SourceGeneratorId
  - Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType.TargetGeneratorId
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SingleFilePreviewApplicationId
  commentId: P:Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SingleFilePreviewApplicationId
  id: SingleFilePreviewApplicationId
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType
  langs:
  - csharp
  - vb
  name: SingleFilePreviewApplicationId
  nameWithType: IApplicationPreviewType.SingleFilePreviewApplicationId
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SingleFilePreviewApplicationId
  type: Property
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.IntegrationApi
  summary: >-
    Id for preview application implementation that can be used

    to launch a preview for a single (source or target language) file.
  remarks: >-
    This id can be passed to <xref href="Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinition.BuildPreviewApplication(Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId)" data-throw-if-not-resolved="false"></xref> to create

    an instance of the application, which should implement <xref href="Sdl.FileTypeSupport.Framework.IntegrationApi.ISingleFilePreviewApplication" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: PreviewApplicationId? SingleFilePreviewApplicationId { get; set; }
    parameters: []
    return:
      type: System.Nullable{Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId}
    content.vb: Property SingleFilePreviewApplicationId As PreviewApplicationId?
  overload: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SingleFilePreviewApplicationId*
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SourceAndTargetPreviewApplicationId
  commentId: P:Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SourceAndTargetPreviewApplicationId
  id: SourceAndTargetPreviewApplicationId
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType
  langs:
  - csharp
  - vb
  name: SourceAndTargetPreviewApplicationId
  nameWithType: IApplicationPreviewType.SourceAndTargetPreviewApplicationId
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SourceAndTargetPreviewApplicationId
  type: Property
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.IntegrationApi
  summary: >-
    Id of the preview application implementation, which can be used

    to launch a preview for both source and target files.
  remarks: >-
    This id can be passed to <xref href="Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinition.BuildPreviewApplication(Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId)" data-throw-if-not-resolved="false"></xref> in order to create

    an instance of the application, which should implement <xref href="Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewApplication" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: PreviewApplicationId? SourceAndTargetPreviewApplicationId { get; set; }
    parameters: []
    return:
      type: System.Nullable{Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId}
    content.vb: Property SourceAndTargetPreviewApplicationId As PreviewApplicationId?
  overload: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SourceAndTargetPreviewApplicationId*
references:
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi
  commentId: N:Sdl.FileTypeSupport.Framework.IntegrationApi
  isExternal: true
  href: Sdl.html
  name: Sdl.FileTypeSupport.Framework.IntegrationApi
  nameWithType: Sdl.FileTypeSupport.Framework.IntegrationApi
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi
    name: IntegrationApi
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi
    name: IntegrationApi
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.html
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType.SourceGeneratorId
  commentId: P:Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType.SourceGeneratorId
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IPreviewType_SourceGeneratorId
  name: SourceGeneratorId
  nameWithType: IPreviewType.SourceGeneratorId
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType.SourceGeneratorId
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType.TargetGeneratorId
  commentId: P:Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType.TargetGeneratorId
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IPreviewType_TargetGeneratorId
  name: TargetGeneratorId
  nameWithType: IPreviewType.TargetGeneratorId
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType.TargetGeneratorId
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType
  commentId: T:Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType.html
  name: IPreviewType
  nameWithType: IPreviewType
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IPreviewType
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinition.BuildPreviewApplication(Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId)
  commentId: M:Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinition.BuildPreviewApplication(Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId)
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinition.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IFileTypeDefinition_BuildPreviewApplication_Sdl_FileTypeSupport_Framework_IntegrationApi_PreviewApplicationId_
  name: BuildPreviewApplication(PreviewApplicationId)
  nameWithType: IFileTypeDefinition.BuildPreviewApplication(PreviewApplicationId)
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinition.BuildPreviewApplication(Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId)
  spec.csharp:
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinition.BuildPreviewApplication(Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId)
    name: BuildPreviewApplication
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinition.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IFileTypeDefinition_BuildPreviewApplication_Sdl_FileTypeSupport_Framework_IntegrationApi_PreviewApplicationId_
  - name: (
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId
    name: PreviewApplicationId
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId.html
  - name: )
  spec.vb:
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinition.BuildPreviewApplication(Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId)
    name: BuildPreviewApplication
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.IFileTypeDefinition.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IFileTypeDefinition_BuildPreviewApplication_Sdl_FileTypeSupport_Framework_IntegrationApi_PreviewApplicationId_
  - name: (
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId
    name: PreviewApplicationId
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId.html
  - name: )
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.ISingleFilePreviewApplication
  commentId: T:Sdl.FileTypeSupport.Framework.IntegrationApi.ISingleFilePreviewApplication
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.ISingleFilePreviewApplication.html
  name: ISingleFilePreviewApplication
  nameWithType: ISingleFilePreviewApplication
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.ISingleFilePreviewApplication
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SingleFilePreviewApplicationId*
  commentId: Overload:Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SingleFilePreviewApplicationId
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IApplicationPreviewType_SingleFilePreviewApplicationId
  name: SingleFilePreviewApplicationId
  nameWithType: IApplicationPreviewType.SingleFilePreviewApplicationId
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SingleFilePreviewApplicationId
- uid: System.Nullable{Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId}
  commentId: T:System.Nullable{Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId}
  parent: System
  definition: System.Nullable`1
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId.html
  name: PreviewApplicationId?
  nameWithType: PreviewApplicationId?
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId?
  spec.csharp:
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId
    name: PreviewApplicationId
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId.html
  - name: '?'
  spec.vb:
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId
    name: PreviewApplicationId
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.PreviewApplicationId.html
  - name: '?'
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewApplication
  commentId: T:Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewApplication
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewApplication.html
  name: ISourceAndTargetFilePreviewApplication
  nameWithType: ISourceAndTargetFilePreviewApplication
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewApplication
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SourceAndTargetPreviewApplicationId*
  commentId: Overload:Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SourceAndTargetPreviewApplicationId
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IApplicationPreviewType_SourceAndTargetPreviewApplicationId
  name: SourceAndTargetPreviewApplicationId
  nameWithType: IApplicationPreviewType.SourceAndTargetPreviewApplicationId
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IApplicationPreviewType.SourceAndTargetPreviewApplicationId
