### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware
  commentId: T:Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware
  id: INativeOutputSettingsAware
  parent: Sdl.FileTypeSupport.Framework.NativeApi
  children:
  - Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.GetProposedOutputFileInfo(Sdl.FileTypeSupport.Framework.NativeApi.IPersistentFileConversionProperties,Sdl.FileTypeSupport.Framework.NativeApi.IOutputFileInfo)
  - Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.SetOutputProperties(Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties)
  langs:
  - csharp
  - vb
  name: INativeOutputSettingsAware
  nameWithType: INativeOutputSettingsAware
  fullName: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware
  type: Interface
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.NativeApi
  summary: >-
    This interface needs to be implemented by any components that should be  

    'aware' of which settings are used when writing native files.


    The <xref href="Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.SetOutputProperties(Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties)" data-throw-if-not-resolved="false"></xref> method will be invoked

    before the content of each native file is processed.
  example: []
  syntax:
    content: public interface INativeOutputSettingsAware
    content.vb: Public Interface INativeOutputSettingsAware
- uid: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.SetOutputProperties(Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties)
  commentId: M:Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.SetOutputProperties(Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties)
  id: SetOutputProperties(Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties)
  parent: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware
  langs:
  - csharp
  - vb
  name: SetOutputProperties(INativeOutputFileProperties)
  nameWithType: INativeOutputSettingsAware.SetOutputProperties(INativeOutputFileProperties)
  fullName: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.SetOutputProperties(Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties)
  type: Method
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.NativeApi
  summary: >-
    This method is invoked by the framework before processing content

    from each native file. The properties passed to this method

    indicate whether source or target language content will be included in the output.

    It also communicates other important properties such as the

    name of the output file to be created and what encoding should

    be used.
  example: []
  syntax:
    content: void SetOutputProperties(INativeOutputFileProperties properties)
    parameters:
    - id: properties
      type: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties
      description: ''
    content.vb: Sub SetOutputProperties(properties As INativeOutputFileProperties)
  overload: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.SetOutputProperties*
- uid: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.GetProposedOutputFileInfo(Sdl.FileTypeSupport.Framework.NativeApi.IPersistentFileConversionProperties,Sdl.FileTypeSupport.Framework.NativeApi.IOutputFileInfo)
  commentId: M:Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.GetProposedOutputFileInfo(Sdl.FileTypeSupport.Framework.NativeApi.IPersistentFileConversionProperties,Sdl.FileTypeSupport.Framework.NativeApi.IOutputFileInfo)
  id: GetProposedOutputFileInfo(Sdl.FileTypeSupport.Framework.NativeApi.IPersistentFileConversionProperties,Sdl.FileTypeSupport.Framework.NativeApi.IOutputFileInfo)
  parent: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware
  langs:
  - csharp
  - vb
  name: GetProposedOutputFileInfo(IPersistentFileConversionProperties, IOutputFileInfo)
  nameWithType: INativeOutputSettingsAware.GetProposedOutputFileInfo(IPersistentFileConversionProperties, IOutputFileInfo)
  fullName: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.GetProposedOutputFileInfo(Sdl.FileTypeSupport.Framework.NativeApi.IPersistentFileConversionProperties, Sdl.FileTypeSupport.Framework.NativeApi.IOutputFileInfo)
  type: Method
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.NativeApi
  summary: >-
    Allows a file type component to suggest a file name for the output

    file to be created. This is called by the framework during generation to provide a suggested default

    file name (and extension) to the host application's implementation

    of the output properties provider.

    <p>

    The provided information allows an application to show a properly initialized 

    Save As dialog with a proposed file name and a corresponding file type filter.

    </p>
  remarks: >-
    <p>

    The framework will call this method for each file type component in the order in which the components 

    are used during generation. Proposals that occur later are always given precedence.

    </p>

    <p>

    The implementation does not need to supply a full path for the file when suggesting a filename.

    </p>

    <p>

    The actual output file info that will be used is provided by the framework

    through the <xref href="Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.SetOutputProperties(Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties)" data-throw-if-not-resolved="false"></xref> call.

    </p>
  example: []
  syntax:
    content: void GetProposedOutputFileInfo(IPersistentFileConversionProperties fileProperties, IOutputFileInfo proposedFileInfo)
    parameters:
    - id: fileProperties
      type: Sdl.FileTypeSupport.Framework.NativeApi.IPersistentFileConversionProperties
      description: ''
    - id: proposedFileInfo
      type: Sdl.FileTypeSupport.Framework.NativeApi.IOutputFileInfo
      description: >-
        Current proposal for the file name etc. if suggested by a 
                    preceding file processor component. The implementation may
                    change the properties of this object to indicate the proposed information.
    content.vb: Sub GetProposedOutputFileInfo(fileProperties As IPersistentFileConversionProperties, proposedFileInfo As IOutputFileInfo)
  overload: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.GetProposedOutputFileInfo*
references:
- uid: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.SetOutputProperties(Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties)
  commentId: M:Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.SetOutputProperties(Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties)
  parent: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.html#Sdl_FileTypeSupport_Framework_NativeApi_INativeOutputSettingsAware_SetOutputProperties_Sdl_FileTypeSupport_Framework_NativeApi_INativeOutputFileProperties_
  name: SetOutputProperties(INativeOutputFileProperties)
  nameWithType: INativeOutputSettingsAware.SetOutputProperties(INativeOutputFileProperties)
  fullName: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.SetOutputProperties(Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties)
  spec.csharp:
  - uid: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.SetOutputProperties(Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties)
    name: SetOutputProperties
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.html#Sdl_FileTypeSupport_Framework_NativeApi_INativeOutputSettingsAware_SetOutputProperties_Sdl_FileTypeSupport_Framework_NativeApi_INativeOutputFileProperties_
  - name: (
  - uid: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties
    name: INativeOutputFileProperties
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties.html
  - name: )
  spec.vb:
  - uid: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.SetOutputProperties(Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties)
    name: SetOutputProperties
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.html#Sdl_FileTypeSupport_Framework_NativeApi_INativeOutputSettingsAware_SetOutputProperties_Sdl_FileTypeSupport_Framework_NativeApi_INativeOutputFileProperties_
  - name: (
  - uid: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties
    name: INativeOutputFileProperties
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties.html
  - name: )
- uid: Sdl.FileTypeSupport.Framework.NativeApi
  commentId: N:Sdl.FileTypeSupport.Framework.NativeApi
  isExternal: true
  href: Sdl.html
  name: Sdl.FileTypeSupport.Framework.NativeApi
  nameWithType: Sdl.FileTypeSupport.Framework.NativeApi
  fullName: Sdl.FileTypeSupport.Framework.NativeApi
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.NativeApi
    name: NativeApi
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.NativeApi.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.NativeApi
    name: NativeApi
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.NativeApi.html
- uid: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware
  commentId: T:Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware
  parent: Sdl.FileTypeSupport.Framework.NativeApi
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.html
  name: INativeOutputSettingsAware
  nameWithType: INativeOutputSettingsAware
  fullName: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware
- uid: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.SetOutputProperties*
  commentId: Overload:Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.SetOutputProperties
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.html#Sdl_FileTypeSupport_Framework_NativeApi_INativeOutputSettingsAware_SetOutputProperties_Sdl_FileTypeSupport_Framework_NativeApi_INativeOutputFileProperties_
  name: SetOutputProperties
  nameWithType: INativeOutputSettingsAware.SetOutputProperties
  fullName: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.SetOutputProperties
- uid: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties
  commentId: T:Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties
  parent: Sdl.FileTypeSupport.Framework.NativeApi
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties.html
  name: INativeOutputFileProperties
  nameWithType: INativeOutputFileProperties
  fullName: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputFileProperties
- uid: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.GetProposedOutputFileInfo*
  commentId: Overload:Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.GetProposedOutputFileInfo
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.html#Sdl_FileTypeSupport_Framework_NativeApi_INativeOutputSettingsAware_GetProposedOutputFileInfo_Sdl_FileTypeSupport_Framework_NativeApi_IPersistentFileConversionProperties_Sdl_FileTypeSupport_Framework_NativeApi_IOutputFileInfo_
  name: GetProposedOutputFileInfo
  nameWithType: INativeOutputSettingsAware.GetProposedOutputFileInfo
  fullName: Sdl.FileTypeSupport.Framework.NativeApi.INativeOutputSettingsAware.GetProposedOutputFileInfo
- uid: Sdl.FileTypeSupport.Framework.NativeApi.IPersistentFileConversionProperties
  commentId: T:Sdl.FileTypeSupport.Framework.NativeApi.IPersistentFileConversionProperties
  parent: Sdl.FileTypeSupport.Framework.NativeApi
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.NativeApi.IPersistentFileConversionProperties.html
  name: IPersistentFileConversionProperties
  nameWithType: IPersistentFileConversionProperties
  fullName: Sdl.FileTypeSupport.Framework.NativeApi.IPersistentFileConversionProperties
- uid: Sdl.FileTypeSupport.Framework.NativeApi.IOutputFileInfo
  commentId: T:Sdl.FileTypeSupport.Framework.NativeApi.IOutputFileInfo
  parent: Sdl.FileTypeSupport.Framework.NativeApi
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.NativeApi.IOutputFileInfo.html
  name: IOutputFileInfo
  nameWithType: IOutputFileInfo
  fullName: Sdl.FileTypeSupport.Framework.NativeApi.IOutputFileInfo
