### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewApplication
  commentId: T:Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewApplication
  id: ISourceAndTargetFilePreviewApplication
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi
  children: []
  langs:
  - csharp
  - vb
  name: ISourceAndTargetFilePreviewApplication
  nameWithType: ISourceAndTargetFilePreviewApplication
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewApplication
  type: Interface
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.IntegrationApi
  summary: >-
    Implementated by components that can manage simultanous previews

    of source and target language files in standalone applications.
  example: []
  syntax:
    content: 'public interface ISourceAndTargetFilePreviewApplication : IAbstractPreviewApplication, IAbstractPreviewController, ISourceAndTargetFilePreviewController'
    content.vb: Public Interface ISourceAndTargetFilePreviewApplication Inherits IAbstractPreviewApplication, IAbstractPreviewController, ISourceAndTargetFilePreviewController
  inheritedMembers:
  - Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.Launch
  - Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.NotifyCanClose
  - Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.PreviewClosed
  - Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewController.SourcePreviewFile
  - Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewController.TargetPreviewFile
references:
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi
  commentId: N:Sdl.FileTypeSupport.Framework.IntegrationApi
  isExternal: true
  href: Sdl.html
  name: Sdl.FileTypeSupport.Framework.IntegrationApi
  nameWithType: Sdl.FileTypeSupport.Framework.IntegrationApi
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi
    name: IntegrationApi
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi
    name: IntegrationApi
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.html
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.Launch
  commentId: M:Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.Launch
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IAbstractPreviewApplication_Launch
  name: Launch()
  nameWithType: IAbstractPreviewApplication.Launch()
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.Launch()
  spec.csharp:
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.Launch
    name: Launch
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IAbstractPreviewApplication_Launch
  - name: (
  - name: )
  spec.vb:
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.Launch
    name: Launch
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IAbstractPreviewApplication_Launch
  - name: (
  - name: )
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.NotifyCanClose
  commentId: M:Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.NotifyCanClose
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IAbstractPreviewApplication_NotifyCanClose
  name: NotifyCanClose()
  nameWithType: IAbstractPreviewApplication.NotifyCanClose()
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.NotifyCanClose()
  spec.csharp:
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.NotifyCanClose
    name: NotifyCanClose
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IAbstractPreviewApplication_NotifyCanClose
  - name: (
  - name: )
  spec.vb:
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.NotifyCanClose
    name: NotifyCanClose
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IAbstractPreviewApplication_NotifyCanClose
  - name: (
  - name: )
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.PreviewClosed
  commentId: E:Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.PreviewClosed
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IAbstractPreviewApplication_PreviewClosed
  name: PreviewClosed
  nameWithType: IAbstractPreviewApplication.PreviewClosed
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.PreviewClosed
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewController.SourcePreviewFile
  commentId: P:Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewController.SourcePreviewFile
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewController
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewController.html#Sdl_FileTypeSupport_Framework_IntegrationApi_ISourceAndTargetFilePreviewController_SourcePreviewFile
  name: SourcePreviewFile
  nameWithType: ISourceAndTargetFilePreviewController.SourcePreviewFile
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewController.SourcePreviewFile
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewController.TargetPreviewFile
  commentId: P:Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewController.TargetPreviewFile
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewController
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewController.html#Sdl_FileTypeSupport_Framework_IntegrationApi_ISourceAndTargetFilePreviewController_TargetPreviewFile
  name: TargetPreviewFile
  nameWithType: ISourceAndTargetFilePreviewController.TargetPreviewFile
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewController.TargetPreviewFile
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication
  commentId: T:Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.html
  name: IAbstractPreviewApplication
  nameWithType: IAbstractPreviewApplication
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewController
  commentId: T:Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewController
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewController.html
  name: ISourceAndTargetFilePreviewController
  nameWithType: ISourceAndTargetFilePreviewController
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.ISourceAndTargetFilePreviewController
