### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.ISingleFilePreviewApplication
  commentId: T:Sdl.FileTypeSupport.Framework.IntegrationApi.ISingleFilePreviewApplication
  id: ISingleFilePreviewApplication
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi
  children: []
  langs:
  - csharp
  - vb
  name: ISingleFilePreviewApplication
  nameWithType: ISingleFilePreviewApplication
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.ISingleFilePreviewApplication
  type: Interface
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.IntegrationApi
  summary: >-
    Manages a standalone application that can be used to preview

    a single (source or target language) file.
  example: []
  syntax:
    content: 'public interface ISingleFilePreviewApplication : IAbstractPreviewApplication, IAbstractPreviewController, ISingleFilePreviewController'
    content.vb: Public Interface ISingleFilePreviewApplication Inherits IAbstractPreviewApplication, IAbstractPreviewController, ISingleFilePreviewController
  inheritedMembers:
  - Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.Launch
  - Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.NotifyCanClose
  - Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.PreviewClosed
  - Sdl.FileTypeSupport.Framework.IntegrationApi.ISingleFilePreviewController.PreviewFile
references:
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi
  commentId: N:Sdl.FileTypeSupport.Framework.IntegrationApi
  isExternal: true
  href: Sdl.html
  name: Sdl.FileTypeSupport.Framework.IntegrationApi
  nameWithType: Sdl.FileTypeSupport.Framework.IntegrationApi
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi
    name: IntegrationApi
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi
    name: IntegrationApi
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.html
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.Launch
  commentId: M:Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.Launch
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IAbstractPreviewApplication_Launch
  name: Launch()
  nameWithType: IAbstractPreviewApplication.Launch()
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.Launch()
  spec.csharp:
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.Launch
    name: Launch
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IAbstractPreviewApplication_Launch
  - name: (
  - name: )
  spec.vb:
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.Launch
    name: Launch
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IAbstractPreviewApplication_Launch
  - name: (
  - name: )
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.NotifyCanClose
  commentId: M:Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.NotifyCanClose
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IAbstractPreviewApplication_NotifyCanClose
  name: NotifyCanClose()
  nameWithType: IAbstractPreviewApplication.NotifyCanClose()
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.NotifyCanClose()
  spec.csharp:
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.NotifyCanClose
    name: NotifyCanClose
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IAbstractPreviewApplication_NotifyCanClose
  - name: (
  - name: )
  spec.vb:
  - uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.NotifyCanClose
    name: NotifyCanClose
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IAbstractPreviewApplication_NotifyCanClose
  - name: (
  - name: )
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.PreviewClosed
  commentId: E:Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.PreviewClosed
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.html#Sdl_FileTypeSupport_Framework_IntegrationApi_IAbstractPreviewApplication_PreviewClosed
  name: PreviewClosed
  nameWithType: IAbstractPreviewApplication.PreviewClosed
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.PreviewClosed
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.ISingleFilePreviewController.PreviewFile
  commentId: P:Sdl.FileTypeSupport.Framework.IntegrationApi.ISingleFilePreviewController.PreviewFile
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi.ISingleFilePreviewController
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.ISingleFilePreviewController.html#Sdl_FileTypeSupport_Framework_IntegrationApi_ISingleFilePreviewController_PreviewFile
  name: PreviewFile
  nameWithType: ISingleFilePreviewController.PreviewFile
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.ISingleFilePreviewController.PreviewFile
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication
  commentId: T:Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication.html
  name: IAbstractPreviewApplication
  nameWithType: IAbstractPreviewApplication
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.IAbstractPreviewApplication
- uid: Sdl.FileTypeSupport.Framework.IntegrationApi.ISingleFilePreviewController
  commentId: T:Sdl.FileTypeSupport.Framework.IntegrationApi.ISingleFilePreviewController
  parent: Sdl.FileTypeSupport.Framework.IntegrationApi
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.IntegrationApi.ISingleFilePreviewController.html
  name: ISingleFilePreviewController
  nameWithType: ISingleFilePreviewController
  fullName: Sdl.FileTypeSupport.Framework.IntegrationApi.ISingleFilePreviewController
