### YamlMime:ManagedReference
items:
- uid: Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder
  commentId: T:Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder
  id: IFileTypeSettingsConverterComponentBuilder
  parent: Sdl.FileTypeSupport.Framework.Core.IntegrationApi
  children:
  - Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter(System.String)
  langs:
  - csharp
  - vb
  name: IFileTypeSettingsConverterComponentBuilder
  nameWithType: IFileTypeSettingsConverterComponentBuilder
  fullName: Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder
  type: Interface
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.Core.IntegrationApi
  summary: Interface for implementing FileTypeSettingsConverterComponentBuilder
  example: []
  syntax:
    content: public interface IFileTypeSettingsConverterComponentBuilder
    content.vb: Public Interface IFileTypeSettingsConverterComponentBuilder
- uid: Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter(System.String)
  commentId: M:Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter(System.String)
  id: BuildFileTypeSettingsConverter(System.String)
  parent: Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder
  langs:
  - csharp
  - vb
  name: BuildFileTypeSettingsConverter(string)
  nameWithType: IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter(string)
  fullName: Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter(string)
  type: Method
  assemblies:
  - Sdl.FileTypeSupport.Framework.Core
  namespace: Sdl.FileTypeSupport.Framework.Core.IntegrationApi
  summary: Method for building FileTypeSettingsConverter component
  example: []
  syntax:
    content: IFileTypeSettingsConverter BuildFileTypeSettingsConverter(string name)
    parameters:
    - id: name
      type: System.String
      description: name of component
    return:
      type: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter
      description: IFileTypeSettingsConverter instance
    content.vb: Function BuildFileTypeSettingsConverter(name As String) As IFileTypeSettingsConverter
  overload: Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter*
  nameWithType.vb: IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter(String)
  fullName.vb: Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter(String)
  name.vb: BuildFileTypeSettingsConverter(String)
references:
- uid: Sdl.FileTypeSupport.Framework.Core.IntegrationApi
  commentId: N:Sdl.FileTypeSupport.Framework.Core.IntegrationApi
  isExternal: true
  href: Sdl.html
  name: Sdl.FileTypeSupport.Framework.Core.IntegrationApi
  nameWithType: Sdl.FileTypeSupport.Framework.Core.IntegrationApi
  fullName: Sdl.FileTypeSupport.Framework.Core.IntegrationApi
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core
    name: Core
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core.IntegrationApi
    name: IntegrationApi
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.IntegrationApi.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core
    name: Core
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core.IntegrationApi
    name: IntegrationApi
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.IntegrationApi.html
- uid: Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter*
  commentId: Overload:Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder.html#Sdl_FileTypeSupport_Framework_Core_IntegrationApi_IFileTypeSettingsConverterComponentBuilder_BuildFileTypeSettingsConverter_System_String_
  name: BuildFileTypeSettingsConverter
  nameWithType: IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter
  fullName: Sdl.FileTypeSupport.Framework.Core.IntegrationApi.IFileTypeSettingsConverterComponentBuilder.BuildFileTypeSettingsConverter
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter
  commentId: T:Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter
  parent: Sdl.FileTypeSupport.Framework.Core.Settings
  isExternal: true
  href: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter.html
  name: IFileTypeSettingsConverter
  nameWithType: IFileTypeSettingsConverter
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings.IFileTypeSettingsConverter
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.FileTypeSupport.Framework.Core.Settings
  commentId: N:Sdl.FileTypeSupport.Framework.Core.Settings
  isExternal: true
  href: Sdl.html
  name: Sdl.FileTypeSupport.Framework.Core.Settings
  nameWithType: Sdl.FileTypeSupport.Framework.Core.Settings
  fullName: Sdl.FileTypeSupport.Framework.Core.Settings
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core
    name: Core
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings
    name: Settings
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.Settings.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.FileTypeSupport
    name: FileTypeSupport
    isExternal: true
    href: Sdl.FileTypeSupport.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework
    name: Framework
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core
    name: Core
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.html
  - name: .
  - uid: Sdl.FileTypeSupport.Framework.Core.Settings
    name: Settings
    isExternal: true
    href: Sdl.FileTypeSupport.Framework.Core.Settings.html
