### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings
  commentId: T:Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings
  id: ProjectTranslationMemoryTaskSettings
  parent: Sdl.ProjectAutomation.Settings
  children:
  - Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.#ctor
  - Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.CreateServerBasedProjectTranslationMemories
  - Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.GetDefaultValue(System.String)
  - Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.ParentResourceGroupPath
  - Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.ServerConnectionUri
  - Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.TranslationMemoryContainerName
  langs:
  - csharp
  - vb
  name: ProjectTranslationMemoryTaskSettings
  nameWithType: ProjectTranslationMemoryTaskSettings
  fullName: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings
  type: Class
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nSettings group class for the Project TM automatic task settings.\n"
  syntax:
    content: 'public class ProjectTranslationMemoryTaskSettings : SettingsGroup'
    content.vb: >-
      Public Class ProjectTranslationMemoryTaskSettings
          Inherits SettingsGroup
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.#ctor
  commentId: M:Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.#ctor
  id: '#ctor'
  parent: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings
  langs:
  - csharp
  - vb
  name: ProjectTranslationMemoryTaskSettings()
  nameWithType: ProjectTranslationMemoryTaskSettings.ProjectTranslationMemoryTaskSettings()
  fullName: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.ProjectTranslationMemoryTaskSettings()
  type: Constructor
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nDefault constructor. You should never create this object manually. Use <xref href=\"Sdl.Core.Settings.ISettingsBundle.GetSettingsGroup(System.String)\" data-throw-if-not-resolved=\"false\"></xref> instead.\n"
  syntax:
    content: public ProjectTranslationMemoryTaskSettings()
    content.vb: Public Sub New
  overload: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.GetDefaultValue(System.String)
  commentId: M:Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.GetDefaultValue(System.String)
  id: GetDefaultValue(System.String)
  parent: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings
  langs:
  - csharp
  - vb
  name: GetDefaultValue(String)
  nameWithType: ProjectTranslationMemoryTaskSettings.GetDefaultValue(String)
  fullName: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.GetDefaultValue(System.String)
  type: Method
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nGets the default value.\n"
  syntax:
    content: protected override object GetDefaultValue(string settingId)
    parameters:
    - id: settingId
      type: System.String
      description: The setting id.
    return:
      type: System.Object
      description: The default value.
    content.vb: Protected Overrides Function GetDefaultValue(settingId As String) As Object
  overload: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.GetDefaultValue*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.CreateServerBasedProjectTranslationMemories
  commentId: P:Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.CreateServerBasedProjectTranslationMemories
  id: CreateServerBasedProjectTranslationMemories
  parent: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings
  langs:
  - csharp
  - vb
  name: CreateServerBasedProjectTranslationMemories
  nameWithType: ProjectTranslationMemoryTaskSettings.CreateServerBasedProjectTranslationMemories
  fullName: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.CreateServerBasedProjectTranslationMemories
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nDetermines whether to create server-based project translation memories.\n"
  syntax:
    content: public Setting<bool> CreateServerBasedProjectTranslationMemories { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.Setting{System.Boolean}
    content.vb: Public ReadOnly Property CreateServerBasedProjectTranslationMemories As Setting(Of Boolean)
  overload: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.CreateServerBasedProjectTranslationMemories*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.ServerConnectionUri
  commentId: P:Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.ServerConnectionUri
  id: ServerConnectionUri
  parent: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings
  langs:
  - csharp
  - vb
  name: ServerConnectionUri
  nameWithType: ProjectTranslationMemoryTaskSettings.ServerConnectionUri
  fullName: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.ServerConnectionUri
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nThe server URI of the TM Server on which to create project translation memories. Should be of the form &quot;http(s)://HOSTNAME:PORT&quot;.\n"
  syntax:
    content: public Setting<string> ServerConnectionUri { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.Setting{System.String}
    content.vb: Public ReadOnly Property ServerConnectionUri As Setting(Of String)
  overload: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.ServerConnectionUri*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.ParentResourceGroupPath
  commentId: P:Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.ParentResourceGroupPath
  id: ParentResourceGroupPath
  parent: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings
  langs:
  - csharp
  - vb
  name: ParentResourceGroupPath
  nameWithType: ProjectTranslationMemoryTaskSettings.ParentResourceGroupPath
  fullName: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.ParentResourceGroupPath
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nParentResourceGroupPath represents the parent source group path; location path.\n"
  syntax:
    content: public Setting<string> ParentResourceGroupPath { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.Setting{System.String}
    content.vb: Public ReadOnly Property ParentResourceGroupPath As Setting(Of String)
  overload: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.ParentResourceGroupPath*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.TranslationMemoryContainerName
  commentId: P:Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.TranslationMemoryContainerName
  id: TranslationMemoryContainerName
  parent: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings
  langs:
  - csharp
  - vb
  name: TranslationMemoryContainerName
  nameWithType: ProjectTranslationMemoryTaskSettings.TranslationMemoryContainerName
  fullName: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.TranslationMemoryContainerName
  type: Property
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\nTranslationMemoryContainerName represents the translation memory container name; container name.\n"
  syntax:
    content: public Setting<string> TranslationMemoryContainerName { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.Setting{System.String}
    content.vb: Public ReadOnly Property TranslationMemoryContainerName As Setting(Of String)
  overload: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.TranslationMemoryContainerName*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Sdl.ProjectAutomation.Settings
  commentId: N:Sdl.ProjectAutomation.Settings
  isExternal: true
  name: Sdl.ProjectAutomation.Settings
  nameWithType: Sdl.ProjectAutomation.Settings
  fullName: Sdl.ProjectAutomation.Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.#ctor*
  commentId: Overload:Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.#ctor
  isExternal: true
  name: ProjectTranslationMemoryTaskSettings
  nameWithType: ProjectTranslationMemoryTaskSettings.ProjectTranslationMemoryTaskSettings
  fullName: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.ProjectTranslationMemoryTaskSettings
- uid: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.GetDefaultValue*
  commentId: Overload:Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.GetDefaultValue
  isExternal: true
  name: GetDefaultValue
  nameWithType: ProjectTranslationMemoryTaskSettings.GetDefaultValue
  fullName: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.GetDefaultValue
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.CreateServerBasedProjectTranslationMemories*
  commentId: Overload:Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.CreateServerBasedProjectTranslationMemories
  isExternal: true
  name: CreateServerBasedProjectTranslationMemories
  nameWithType: ProjectTranslationMemoryTaskSettings.CreateServerBasedProjectTranslationMemories
  fullName: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.CreateServerBasedProjectTranslationMemories
- uid: Sdl.Core.Settings.Setting{System.Boolean}
  commentId: '!:Sdl.Core.Settings.Setting{System.Boolean}'
  definition: Sdl.Core.Settings.Setting`1
  name: Setting<Boolean>
  nameWithType: Setting<Boolean>
  fullName: Sdl.Core.Settings.Setting<System.Boolean>
  nameWithType.vb: Setting(Of Boolean)
  fullName.vb: Sdl.Core.Settings.Setting(Of System.Boolean)
  name.vb: Setting(Of Boolean)
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Core.Settings.Setting`1
  isExternal: true
  name: Setting<>
  nameWithType: Setting<>
  fullName: Sdl.Core.Settings.Setting<>
  nameWithType.vb: Setting(Of )
  fullName.vb: Sdl.Core.Settings.Setting(Of )
  name.vb: Setting(Of )
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.ServerConnectionUri*
  commentId: Overload:Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.ServerConnectionUri
  isExternal: true
  name: ServerConnectionUri
  nameWithType: ProjectTranslationMemoryTaskSettings.ServerConnectionUri
  fullName: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.ServerConnectionUri
- uid: Sdl.Core.Settings.Setting{System.String}
  commentId: '!:Sdl.Core.Settings.Setting{System.String}'
  definition: Sdl.Core.Settings.Setting`1
  name: Setting<String>
  nameWithType: Setting<String>
  fullName: Sdl.Core.Settings.Setting<System.String>
  nameWithType.vb: Setting(Of String)
  fullName.vb: Sdl.Core.Settings.Setting(Of System.String)
  name.vb: Setting(Of String)
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.ParentResourceGroupPath*
  commentId: Overload:Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.ParentResourceGroupPath
  isExternal: true
  name: ParentResourceGroupPath
  nameWithType: ProjectTranslationMemoryTaskSettings.ParentResourceGroupPath
  fullName: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.ParentResourceGroupPath
- uid: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.TranslationMemoryContainerName*
  commentId: Overload:Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.TranslationMemoryContainerName
  isExternal: true
  name: TranslationMemoryContainerName
  nameWithType: ProjectTranslationMemoryTaskSettings.TranslationMemoryContainerName
  fullName: Sdl.ProjectAutomation.Settings.ProjectTranslationMemoryTaskSettings.TranslationMemoryContainerName
