### YamlMime:ManagedReference
items:
- uid: Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction
  commentId: T:Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction
  id: NoTranslationMemoryMatchFoundAction
  parent: Sdl.ProjectAutomation.Settings
  children:
  - Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction.ApplyAutomatedTranslation
  - Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction.CopySourceToTarget
  - Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction.LeaveEmpty
  langs:
  - csharp
  - vb
  name: NoTranslationMemoryMatchFoundAction
  nameWithType: NoTranslationMemoryMatchFoundAction
  fullName: Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction
  type: Enum
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\n\n"
  syntax:
    content: public enum NoTranslationMemoryMatchFoundAction
    content.vb: Public Enum NoTranslationMemoryMatchFoundAction
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction.CopySourceToTarget
  commentId: F:Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction.CopySourceToTarget
  id: CopySourceToTarget
  parent: Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction
  langs:
  - csharp
  - vb
  name: CopySourceToTarget
  nameWithType: NoTranslationMemoryMatchFoundAction.CopySourceToTarget
  fullName: Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction.CopySourceToTarget
  type: Field
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\n\n"
  syntax:
    content: CopySourceToTarget = 0
    return:
      type: Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction.ApplyAutomatedTranslation
  commentId: F:Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction.ApplyAutomatedTranslation
  id: ApplyAutomatedTranslation
  parent: Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction
  langs:
  - csharp
  - vb
  name: ApplyAutomatedTranslation
  nameWithType: NoTranslationMemoryMatchFoundAction.ApplyAutomatedTranslation
  fullName: Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction.ApplyAutomatedTranslation
  type: Field
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\n\n"
  syntax:
    content: ApplyAutomatedTranslation = 1
    return:
      type: Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction.LeaveEmpty
  commentId: F:Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction.LeaveEmpty
  id: LeaveEmpty
  parent: Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction
  langs:
  - csharp
  - vb
  name: LeaveEmpty
  nameWithType: NoTranslationMemoryMatchFoundAction.LeaveEmpty
  fullName: Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction.LeaveEmpty
  type: Field
  source:
    path: Sdl.ProjectAutomation.Settings
    isExternal: true
  assemblies:
  - Sdl.ProjectAutomation.Settings
  namespace: Sdl.ProjectAutomation.Settings
  summary: "\n\n"
  syntax:
    content: LeaveEmpty = 2
    return:
      type: Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Sdl.ProjectAutomation.Settings
  commentId: N:Sdl.ProjectAutomation.Settings
  isExternal: true
  name: Sdl.ProjectAutomation.Settings
  nameWithType: Sdl.ProjectAutomation.Settings
  fullName: Sdl.ProjectAutomation.Settings
- uid: Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction
  commentId: T:Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction
  parent: Sdl.ProjectAutomation.Settings
  isExternal: true
  name: NoTranslationMemoryMatchFoundAction
  nameWithType: NoTranslationMemoryMatchFoundAction
  fullName: Sdl.ProjectAutomation.Settings.NoTranslationMemoryMatchFoundAction
