### YamlMime:ManagedReference
items:
- uid: Sdl.Verification.Api.ITermVerifierSettingsContext
  commentId: T:Sdl.Verification.Api.ITermVerifierSettingsContext
  id: ITermVerifierSettingsContext
  parent: Sdl.Verification.Api
  children:
  - Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbaseName
  - Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbasePicklistFields
  - Sdl.Verification.Api.ITermVerifierSettingsContext.HasTermbase
  langs:
  - csharp
  - vb
  name: ITermVerifierSettingsContext
  nameWithType: ITermVerifierSettingsContext
  fullName: Sdl.Verification.Api.ITermVerifierSettingsContext
  type: Interface
  source:
    path: Sdl.Verification.Api
    isExternal: true
  assemblies:
  - Sdl.Verification.Api
  namespace: Sdl.Verification.Api
  summary: "\nITermVerifierSettingsContext interface represents a term verifier settings context that provides \na term verifier settings page with the term access services that it needs.\n"
  syntax:
    content: public interface ITermVerifierSettingsContext
    content.vb: Public Interface ITermVerifierSettingsContext
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Sdl.Verification.Api.ITermVerifierSettingsContext.HasTermbase
  commentId: M:Sdl.Verification.Api.ITermVerifierSettingsContext.HasTermbase
  id: HasTermbase
  parent: Sdl.Verification.Api.ITermVerifierSettingsContext
  langs:
  - csharp
  - vb
  name: HasTermbase()
  nameWithType: ITermVerifierSettingsContext.HasTermbase()
  fullName: Sdl.Verification.Api.ITermVerifierSettingsContext.HasTermbase()
  type: Method
  source:
    path: Sdl.Verification.Api
    isExternal: true
  assemblies:
  - Sdl.Verification.Api
  namespace: Sdl.Verification.Api
  summary: "\nDetermines whether the context has a termbase.\n"
  syntax:
    content: bool HasTermbase()
    return:
      type: System.Boolean
      description: whether context has termbase
    content.vb: Function HasTermbase As Boolean
  overload: Sdl.Verification.Api.ITermVerifierSettingsContext.HasTermbase*
- uid: Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbaseName
  commentId: M:Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbaseName
  id: GetTermbaseName
  parent: Sdl.Verification.Api.ITermVerifierSettingsContext
  langs:
  - csharp
  - vb
  name: GetTermbaseName()
  nameWithType: ITermVerifierSettingsContext.GetTermbaseName()
  fullName: Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbaseName()
  type: Method
  source:
    path: Sdl.Verification.Api
    isExternal: true
  assemblies:
  - Sdl.Verification.Api
  namespace: Sdl.Verification.Api
  summary: "\nGets the termbase name.\n"
  syntax:
    content: string GetTermbaseName()
    return:
      type: System.String
      description: termbase name
    content.vb: Function GetTermbaseName As String
  overload: Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbaseName*
- uid: Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbasePicklistFields
  commentId: M:Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbasePicklistFields
  id: GetTermbasePicklistFields
  parent: Sdl.Verification.Api.ITermVerifierSettingsContext
  langs:
  - csharp
  - vb
  name: GetTermbasePicklistFields()
  nameWithType: ITermVerifierSettingsContext.GetTermbasePicklistFields()
  fullName: Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbasePicklistFields()
  type: Method
  source:
    path: Sdl.Verification.Api
    isExternal: true
  assemblies:
  - Sdl.Verification.Api
  namespace: Sdl.Verification.Api
  summary: "\nGets the termbase picklist fields.\n"
  syntax:
    content: IEnumerable<TermPicklistField> GetTermbasePicklistFields()
    return:
      type: System.Collections.Generic.IEnumerable{Sdl.Verification.Api.TermPicklistField}
      description: termbase picklist fields
    content.vb: Function GetTermbasePicklistFields As IEnumerable(Of TermPicklistField)
  overload: Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbasePicklistFields*
references:
- uid: Sdl.Verification.Api
  commentId: N:Sdl.Verification.Api
  isExternal: true
  name: Sdl.Verification.Api
  nameWithType: Sdl.Verification.Api
  fullName: Sdl.Verification.Api
- uid: Sdl.Verification.Api.ITermVerifierSettingsContext.HasTermbase*
  commentId: Overload:Sdl.Verification.Api.ITermVerifierSettingsContext.HasTermbase
  isExternal: true
  name: HasTermbase
  nameWithType: ITermVerifierSettingsContext.HasTermbase
  fullName: Sdl.Verification.Api.ITermVerifierSettingsContext.HasTermbase
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbaseName*
  commentId: Overload:Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbaseName
  isExternal: true
  name: GetTermbaseName
  nameWithType: ITermVerifierSettingsContext.GetTermbaseName
  fullName: Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbaseName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbasePicklistFields*
  commentId: Overload:Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbasePicklistFields
  isExternal: true
  name: GetTermbasePicklistFields
  nameWithType: ITermVerifierSettingsContext.GetTermbasePicklistFields
  fullName: Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbasePicklistFields
- uid: System.Collections.Generic.IEnumerable{Sdl.Verification.Api.TermPicklistField}
  commentId: T:System.Collections.Generic.IEnumerable{Sdl.Verification.Api.TermPicklistField}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  name: IEnumerable<TermPicklistField>
  nameWithType: IEnumerable<TermPicklistField>
  fullName: System.Collections.Generic.IEnumerable<Sdl.Verification.Api.TermPicklistField>
  nameWithType.vb: IEnumerable(Of TermPicklistField)
  fullName.vb: System.Collections.Generic.IEnumerable(Of Sdl.Verification.Api.TermPicklistField)
  name.vb: IEnumerable(Of TermPicklistField)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Sdl.Verification.Api.TermPicklistField
    name: TermPicklistField
    nameWithType: TermPicklistField
    fullName: Sdl.Verification.Api.TermPicklistField
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Sdl.Verification.Api.TermPicklistField
    name: TermPicklistField
    nameWithType: TermPicklistField
    fullName: Sdl.Verification.Api.TermPicklistField
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
