### YamlMime:ManagedReference
items:
- uid: Sdl.Core.Settings
  commentId: N:Sdl.Core.Settings
  id: Sdl.Core.Settings
  children:
  - Sdl.Core.Settings.AbstractSettingsGroupBase
  - Sdl.Core.Settings.AbstractSettingsPage
  - Sdl.Core.Settings.ISettingsBundle
  - Sdl.Core.Settings.ISettingsBundleAware
  - Sdl.Core.Settings.ISettingsGroup
  - Sdl.Core.Settings.ISettingsPage
  - Sdl.Core.Settings.Setting`1
  - Sdl.Core.Settings.SettingsChangedEventArgs
  - Sdl.Core.Settings.SettingsGroup
  - Sdl.Core.Settings.SettingsUtil
  langs:
  - csharp
  - vb
  name: Sdl.Core.Settings
  nameWithType: Sdl.Core.Settings
  fullName: Sdl.Core.Settings
  type: Namespace
  assemblies:
  - Sdl.Core.Settings
references:
- uid: Sdl.Core.Settings.AbstractSettingsGroupBase
  commentId: T:Sdl.Core.Settings.AbstractSettingsGroupBase
  parent: Sdl.Core.Settings
  isExternal: true
  name: AbstractSettingsGroupBase
  nameWithType: AbstractSettingsGroupBase
  fullName: Sdl.Core.Settings.AbstractSettingsGroupBase
- uid: Sdl.Core.Settings.AbstractSettingsPage
  commentId: T:Sdl.Core.Settings.AbstractSettingsPage
  isExternal: true
  name: AbstractSettingsPage
  nameWithType: AbstractSettingsPage
  fullName: Sdl.Core.Settings.AbstractSettingsPage
- uid: Sdl.Core.Settings.ISettingsBundle
  commentId: T:Sdl.Core.Settings.ISettingsBundle
  parent: Sdl.Core.Settings
  isExternal: true
  name: ISettingsBundle
  nameWithType: ISettingsBundle
  fullName: Sdl.Core.Settings.ISettingsBundle
- uid: Sdl.Core.Settings.ISettingsBundleAware
  commentId: T:Sdl.Core.Settings.ISettingsBundleAware
  parent: Sdl.Core.Settings
  isExternal: true
  name: ISettingsBundleAware
  nameWithType: ISettingsBundleAware
  fullName: Sdl.Core.Settings.ISettingsBundleAware
- uid: Sdl.Core.Settings.ISettingsGroup
  commentId: T:Sdl.Core.Settings.ISettingsGroup
  parent: Sdl.Core.Settings
  isExternal: true
  name: ISettingsGroup
  nameWithType: ISettingsGroup
  fullName: Sdl.Core.Settings.ISettingsGroup
- uid: Sdl.Core.Settings.ISettingsPage
  commentId: T:Sdl.Core.Settings.ISettingsPage
  parent: Sdl.Core.Settings
  isExternal: true
  name: ISettingsPage
  nameWithType: ISettingsPage
  fullName: Sdl.Core.Settings.ISettingsPage
- uid: Sdl.Core.Settings.Setting`1
  commentId: T:Sdl.Core.Settings.Setting`1
  parent: Sdl.Core.Settings
  isExternal: true
  name: Setting<T>
  nameWithType: Setting<T>
  fullName: Sdl.Core.Settings.Setting<T>
  nameWithType.vb: Setting(Of T)
  fullName.vb: Sdl.Core.Settings.Setting(Of T)
  name.vb: Setting(Of T)
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    nameWithType: Setting
    fullName: Sdl.Core.Settings.Setting
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.Core.Settings.SettingsChangedEventArgs
  commentId: T:Sdl.Core.Settings.SettingsChangedEventArgs
  parent: Sdl.Core.Settings
  isExternal: true
  name: SettingsChangedEventArgs
  nameWithType: SettingsChangedEventArgs
  fullName: Sdl.Core.Settings.SettingsChangedEventArgs
- uid: Sdl.Core.Settings.SettingsGroup
  commentId: T:Sdl.Core.Settings.SettingsGroup
  parent: Sdl.Core.Settings
  isExternal: true
  name: SettingsGroup
  nameWithType: SettingsGroup
  fullName: Sdl.Core.Settings.SettingsGroup
- uid: Sdl.Core.Settings.SettingsUtil
  commentId: T:Sdl.Core.Settings.SettingsUtil
  isExternal: true
  name: SettingsUtil
  nameWithType: SettingsUtil
  fullName: Sdl.Core.Settings.SettingsUtil
- uid: Sdl.Core.Settings
  commentId: N:Sdl.Core.Settings
  isExternal: true
  name: Sdl.Core.Settings
  nameWithType: Sdl.Core.Settings
  fullName: Sdl.Core.Settings
