### YamlMime:ManagedReference
items:
- uid: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings
  commentId: T:Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings
  id: TMXWriterSettings
  parent: Sdl.LanguagePlatform.IO.TMX
  children:
  - Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.#ctor
  - Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.#ctor(System.Text.Encoding)
  - Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.Encoding
  - Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.PlainText
  - Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.ReplaceInvalidCharacters
  - Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.ReplacementCharacter
  - Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.TargetFormat
  langs:
  - csharp
  - vb
  name: TMXWriterSettings
  nameWithType: TMXWriterSettings
  fullName: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings
  type: Class
  source:
    path: Sdl.LanguagePlatform.IO
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.IO
  namespace: Sdl.LanguagePlatform.IO.TMX
  syntax:
    content: public class TMXWriterSettings
    content.vb: Public Class TMXWriterSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.#ctor
  commentId: M:Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.#ctor
  id: '#ctor'
  parent: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings
  langs:
  - csharp
  - vb
  name: TMXWriterSettings()
  nameWithType: TMXWriterSettings.TMXWriterSettings()
  fullName: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.TMXWriterSettings()
  type: Constructor
  source:
    path: Sdl.LanguagePlatform.IO
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.IO
  namespace: Sdl.LanguagePlatform.IO.TMX
  syntax:
    content: public TMXWriterSettings()
    content.vb: Public Sub New
  overload: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.#ctor(System.Text.Encoding)
  commentId: M:Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.#ctor(System.Text.Encoding)
  id: '#ctor(System.Text.Encoding)'
  parent: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings
  langs:
  - csharp
  - vb
  name: TMXWriterSettings(Encoding)
  nameWithType: TMXWriterSettings.TMXWriterSettings(Encoding)
  fullName: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.TMXWriterSettings(System.Text.Encoding)
  type: Constructor
  source:
    path: Sdl.LanguagePlatform.IO
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.IO
  namespace: Sdl.LanguagePlatform.IO.TMX
  syntax:
    content: public TMXWriterSettings(Encoding encoding)
    parameters:
    - id: encoding
      type: System.Text.Encoding
    content.vb: Public Sub New(encoding As Encoding)
  overload: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.Encoding
  commentId: P:Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.Encoding
  id: Encoding
  parent: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings
  langs:
  - csharp
  - vb
  name: Encoding
  nameWithType: TMXWriterSettings.Encoding
  fullName: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.Encoding
  type: Property
  source:
    path: Sdl.LanguagePlatform.IO
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.IO
  namespace: Sdl.LanguagePlatform.IO.TMX
  syntax:
    content: public Encoding Encoding { get; }
    parameters: []
    return:
      type: System.Text.Encoding
    content.vb: Public ReadOnly Property Encoding As Encoding
  overload: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.Encoding*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.TargetFormat
  commentId: P:Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.TargetFormat
  id: TargetFormat
  parent: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings
  langs:
  - csharp
  - vb
  name: TargetFormat
  nameWithType: TMXWriterSettings.TargetFormat
  fullName: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.TargetFormat
  type: Property
  source:
    path: Sdl.LanguagePlatform.IO
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.IO
  namespace: Sdl.LanguagePlatform.IO.TMX
  syntax:
    content: public TranslationUnitFormat TargetFormat { get; set; }
    parameters: []
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.TranslationUnitFormat
    content.vb: Public Property TargetFormat As TranslationUnitFormat
  overload: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.TargetFormat*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.PlainText
  commentId: P:Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.PlainText
  id: PlainText
  parent: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings
  langs:
  - csharp
  - vb
  name: PlainText
  nameWithType: TMXWriterSettings.PlainText
  fullName: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.PlainText
  type: Property
  source:
    path: Sdl.LanguagePlatform.IO
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.IO
  namespace: Sdl.LanguagePlatform.IO.TMX
  syntax:
    content: public bool PlainText { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property PlainText As Boolean
  overload: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.PlainText*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.ReplaceInvalidCharacters
  commentId: P:Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.ReplaceInvalidCharacters
  id: ReplaceInvalidCharacters
  parent: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings
  langs:
  - csharp
  - vb
  name: ReplaceInvalidCharacters
  nameWithType: TMXWriterSettings.ReplaceInvalidCharacters
  fullName: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.ReplaceInvalidCharacters
  type: Property
  source:
    path: Sdl.LanguagePlatform.IO
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.IO
  namespace: Sdl.LanguagePlatform.IO.TMX
  summary: "\nGets or sets a flag whether to replace characters &lt; \\u0020 with &apos;*&apos;. Usually these are emitted as\nnumeric character reference entities. However, some XML parsers (such as Java&apos;s) throw errors on such\ncharacters.\n"
  syntax:
    content: public bool ReplaceInvalidCharacters { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property ReplaceInvalidCharacters As Boolean
  overload: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.ReplaceInvalidCharacters*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.ReplacementCharacter
  commentId: P:Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.ReplacementCharacter
  id: ReplacementCharacter
  parent: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings
  langs:
  - csharp
  - vb
  name: ReplacementCharacter
  nameWithType: TMXWriterSettings.ReplacementCharacter
  fullName: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.ReplacementCharacter
  type: Property
  source:
    path: Sdl.LanguagePlatform.IO
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.IO
  namespace: Sdl.LanguagePlatform.IO.TMX
  summary: "\nGets or sets the character to replace invalid characters with - if \\0, invalid characters will be deleted. Only \nrelevant if _ReplaceInvalidCharacters is true. Defaults to \\0. Obviously should not be set to an invalid XML character :)\n"
  syntax:
    content: public char ReplacementCharacter { get; set; }
    parameters: []
    return:
      type: System.Char
    content.vb: Public Property ReplacementCharacter As Char
  overload: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.ReplacementCharacter*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Sdl.LanguagePlatform.IO.TMX
  commentId: N:Sdl.LanguagePlatform.IO.TMX
  isExternal: true
  name: Sdl.LanguagePlatform.IO.TMX
  nameWithType: Sdl.LanguagePlatform.IO.TMX
  fullName: Sdl.LanguagePlatform.IO.TMX
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.#ctor*
  commentId: Overload:Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.#ctor
  isExternal: true
  name: TMXWriterSettings
  nameWithType: TMXWriterSettings.TMXWriterSettings
  fullName: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.TMXWriterSettings
- uid: System.Text.Encoding
  commentId: T:System.Text.Encoding
  parent: System.Text
  isExternal: true
  name: Encoding
  nameWithType: Encoding
  fullName: System.Text.Encoding
- uid: System.Text
  commentId: N:System.Text
  isExternal: true
  name: System.Text
  nameWithType: System.Text
  fullName: System.Text
- uid: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.Encoding*
  commentId: Overload:Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.Encoding
  isExternal: true
  name: Encoding
  nameWithType: TMXWriterSettings.Encoding
  fullName: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.Encoding
- uid: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.TargetFormat*
  commentId: Overload:Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.TargetFormat
  isExternal: true
  name: TargetFormat
  nameWithType: TMXWriterSettings.TargetFormat
  fullName: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.TargetFormat
- uid: Sdl.LanguagePlatform.TranslationMemory.TranslationUnitFormat
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.TranslationUnitFormat
  parent: Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  name: TranslationUnitFormat
  nameWithType: TranslationUnitFormat
  fullName: Sdl.LanguagePlatform.TranslationMemory.TranslationUnitFormat
- uid: Sdl.LanguagePlatform.TranslationMemory
  commentId: N:Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  name: Sdl.LanguagePlatform.TranslationMemory
  nameWithType: Sdl.LanguagePlatform.TranslationMemory
  fullName: Sdl.LanguagePlatform.TranslationMemory
- uid: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.PlainText*
  commentId: Overload:Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.PlainText
  isExternal: true
  name: PlainText
  nameWithType: TMXWriterSettings.PlainText
  fullName: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.PlainText
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.ReplaceInvalidCharacters*
  commentId: Overload:Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.ReplaceInvalidCharacters
  isExternal: true
  name: ReplaceInvalidCharacters
  nameWithType: TMXWriterSettings.ReplaceInvalidCharacters
  fullName: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.ReplaceInvalidCharacters
- uid: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.ReplacementCharacter*
  commentId: Overload:Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.ReplacementCharacter
  isExternal: true
  name: ReplacementCharacter
  nameWithType: TMXWriterSettings.ReplacementCharacter
  fullName: Sdl.LanguagePlatform.IO.TMX.TMXWriterSettings.ReplacementCharacter
- uid: System.Char
  commentId: T:System.Char
  parent: System
  isExternal: true
  name: Char
  nameWithType: Char
  fullName: System.Char
