### YamlMime:ManagedReference
items:
- uid: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings
  commentId: T:Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings
  id: TranslationModelBuilderSettings
  parent: Sdl.Core.FineGrainedAlignment
  children:
  - Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.#ctor(System.Int32)
  - Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.Default
  - Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.MinModelSampleSize
  langs:
  - csharp
  - vb
  name: TranslationModelBuilderSettings
  nameWithType: TranslationModelBuilderSettings
  fullName: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings
  type: Class
  source:
    path: Sdl.Core.FineGrainedAlignment
    isExternal: true
  assemblies:
  - Sdl.Core.FineGrainedAlignment
  namespace: Sdl.Core.FineGrainedAlignment
  syntax:
    content: public class TranslationModelBuilderSettings
    content.vb: Public Class TranslationModelBuilderSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.#ctor(System.Int32)
  commentId: M:Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.#ctor(System.Int32)
  id: '#ctor(System.Int32)'
  parent: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings
  langs:
  - csharp
  - vb
  name: TranslationModelBuilderSettings(Int32)
  nameWithType: TranslationModelBuilderSettings.TranslationModelBuilderSettings(Int32)
  fullName: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.TranslationModelBuilderSettings(System.Int32)
  type: Constructor
  source:
    path: Sdl.Core.FineGrainedAlignment
    isExternal: true
  assemblies:
  - Sdl.Core.FineGrainedAlignment
  namespace: Sdl.Core.FineGrainedAlignment
  syntax:
    content: public TranslationModelBuilderSettings(int minModelSampleSize)
    parameters:
    - id: minModelSampleSize
      type: System.Int32
    content.vb: Public Sub New(minModelSampleSize As Integer)
  overload: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.MinModelSampleSize
  commentId: P:Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.MinModelSampleSize
  id: MinModelSampleSize
  parent: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings
  langs:
  - csharp
  - vb
  name: MinModelSampleSize
  nameWithType: TranslationModelBuilderSettings.MinModelSampleSize
  fullName: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.MinModelSampleSize
  type: Property
  source:
    path: Sdl.Core.FineGrainedAlignment
    isExternal: true
  assemblies:
  - Sdl.Core.FineGrainedAlignment
  namespace: Sdl.Core.FineGrainedAlignment
  syntax:
    content: public int MinModelSampleSize { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public ReadOnly Property MinModelSampleSize As Integer
  overload: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.MinModelSampleSize*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.Default
  commentId: P:Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.Default
  id: Default
  parent: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings
  langs:
  - csharp
  - vb
  name: Default
  nameWithType: TranslationModelBuilderSettings.Default
  fullName: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.Default
  type: Property
  source:
    path: Sdl.Core.FineGrainedAlignment
    isExternal: true
  assemblies:
  - Sdl.Core.FineGrainedAlignment
  namespace: Sdl.Core.FineGrainedAlignment
  syntax:
    content: public static TranslationModelBuilderSettings Default { get; }
    parameters: []
    return:
      type: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings
    content.vb: Public Shared ReadOnly Property Default As TranslationModelBuilderSettings
  overload: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.Default*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
references:
- uid: Sdl.Core.FineGrainedAlignment
  commentId: N:Sdl.Core.FineGrainedAlignment
  isExternal: true
  name: Sdl.Core.FineGrainedAlignment
  nameWithType: Sdl.Core.FineGrainedAlignment
  fullName: Sdl.Core.FineGrainedAlignment
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.#ctor*
  commentId: Overload:Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.#ctor
  isExternal: true
  name: TranslationModelBuilderSettings
  nameWithType: TranslationModelBuilderSettings.TranslationModelBuilderSettings
  fullName: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.TranslationModelBuilderSettings
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.MinModelSampleSize*
  commentId: Overload:Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.MinModelSampleSize
  isExternal: true
  name: MinModelSampleSize
  nameWithType: TranslationModelBuilderSettings.MinModelSampleSize
  fullName: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.MinModelSampleSize
- uid: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.Default*
  commentId: Overload:Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.Default
  isExternal: true
  name: Default
  nameWithType: TranslationModelBuilderSettings.Default
  fullName: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.Default
- uid: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings
  commentId: T:Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings
  parent: Sdl.Core.FineGrainedAlignment
  isExternal: true
  name: TranslationModelBuilderSettings
  nameWithType: TranslationModelBuilderSettings
  fullName: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings
