### YamlMime:ManagedReference
items:
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  id: ImportSettings.NewFieldsOption
  parent: Sdl.LanguagePlatform.TranslationMemory
  children:
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.AddToSetup
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.Error
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.Ignore
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.SkipTranslationUnit
  langs:
  - csharp
  - vb
  name: ImportSettings.NewFieldsOption
  nameWithType: ImportSettings.NewFieldsOption
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  type: Enum
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: >-
    Specifies how the system should react if an import or an add operation would result in a change to the setup 

    (such as implicitly adding unknown fields or field values).
  example: []
  syntax:
    content: public enum ImportSettings.NewFieldsOption
    content.vb: Public Enum ImportSettings.NewFieldsOption
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.AddToSetup
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.AddToSetup
  id: AddToSetup
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  langs:
  - csharp
  - vb
  name: AddToSetup
  nameWithType: ImportSettings.NewFieldsOption.AddToSetup
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.AddToSetup
  type: Field
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: The translation unit is processed and unknown user-defined fields are automatically added to the setup.
  example: []
  syntax:
    content: AddToSetup = 0
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.Ignore
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.Ignore
  id: Ignore
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  langs:
  - csharp
  - vb
  name: Ignore
  nameWithType: ImportSettings.NewFieldsOption.Ignore
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.Ignore
  type: Field
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: The translation unit is processed and unknown user-defined fields are ignored (not added to the setup).
  example: []
  syntax:
    content: Ignore = 1
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.SkipTranslationUnit
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.SkipTranslationUnit
  id: SkipTranslationUnit
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  langs:
  - csharp
  - vb
  name: SkipTranslationUnit
  nameWithType: ImportSettings.NewFieldsOption.SkipTranslationUnit
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.SkipTranslationUnit
  type: Field
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: The translation units containing unknown user-defined fields are skipped.
  example: []
  syntax:
    content: SkipTranslationUnit = 2
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.Error
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.Error
  id: Error
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  langs:
  - csharp
  - vb
  name: Error
  nameWithType: ImportSettings.NewFieldsOption.Error
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.Error
  type: Field
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: If any translation unit contains an unknown user-defined field an error is thrown.
  example: []
  syntax:
    content: Error = 3
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
references:
- uid: Sdl.LanguagePlatform.TranslationMemory
  commentId: N:Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  href: Sdl.html
  name: Sdl.LanguagePlatform.TranslationMemory
  nameWithType: Sdl.LanguagePlatform.TranslationMemory
  fullName: Sdl.LanguagePlatform.TranslationMemory
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.LanguagePlatform
    name: LanguagePlatform
    isExternal: true
    href: Sdl.LanguagePlatform.html
  - name: .
  - uid: Sdl.LanguagePlatform.TranslationMemory
    name: TranslationMemory
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.LanguagePlatform
    name: LanguagePlatform
    isExternal: true
    href: Sdl.LanguagePlatform.html
  - name: .
  - uid: Sdl.LanguagePlatform.TranslationMemory
    name: TranslationMemory
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.html
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  parent: Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  href: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.html
  name: ImportSettings.NewFieldsOption
  nameWithType: ImportSettings.NewFieldsOption
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  spec.csharp:
  - uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings
    name: ImportSettings
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.html
  - name: .
  - uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
    name: NewFieldsOption
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.html
  spec.vb:
  - uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings
    name: ImportSettings
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.html
  - name: .
  - uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
    name: NewFieldsOption
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.html
