### YamlMime:ManagedReference
items:
- uid: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings
  commentId: T:Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings
  id: TranslationModelBuilderSettings
  parent: Sdl.Core.FineGrainedAlignment
  children:
  - Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.#ctor(System.Int32)
  - Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.Default
  - Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.MinModelSampleSize
  langs:
  - csharp
  - vb
  name: TranslationModelBuilderSettings
  nameWithType: TranslationModelBuilderSettings
  fullName: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings
  type: Class
  assemblies:
  - Sdl.Core.FineGrainedAlignment
  namespace: Sdl.Core.FineGrainedAlignment
  syntax:
    content: public class TranslationModelBuilderSettings
    content.vb: Public Class TranslationModelBuilderSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
- uid: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.#ctor(System.Int32)
  commentId: M:Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.#ctor(System.Int32)
  id: '#ctor(System.Int32)'
  parent: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings
  langs:
  - csharp
  - vb
  name: TranslationModelBuilderSettings(int)
  nameWithType: TranslationModelBuilderSettings.TranslationModelBuilderSettings(int)
  fullName: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.TranslationModelBuilderSettings(int)
  type: Constructor
  assemblies:
  - Sdl.Core.FineGrainedAlignment
  namespace: Sdl.Core.FineGrainedAlignment
  syntax:
    content: public TranslationModelBuilderSettings(int minModelSampleSize)
    parameters:
    - id: minModelSampleSize
      type: System.Int32
    content.vb: Public Sub New(minModelSampleSize As Integer)
  overload: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.#ctor*
  nameWithType.vb: TranslationModelBuilderSettings.New(Integer)
  fullName.vb: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.New(Integer)
  name.vb: New(Integer)
- uid: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.MinModelSampleSize
  commentId: P:Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.MinModelSampleSize
  id: MinModelSampleSize
  parent: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings
  langs:
  - csharp
  - vb
  name: MinModelSampleSize
  nameWithType: TranslationModelBuilderSettings.MinModelSampleSize
  fullName: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.MinModelSampleSize
  type: Property
  assemblies:
  - Sdl.Core.FineGrainedAlignment
  namespace: Sdl.Core.FineGrainedAlignment
  syntax:
    content: public int MinModelSampleSize { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public ReadOnly Property MinModelSampleSize As Integer
  overload: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.MinModelSampleSize*
- uid: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.Default
  commentId: P:Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.Default
  id: Default
  parent: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings
  langs:
  - csharp
  - vb
  name: Default
  nameWithType: TranslationModelBuilderSettings.Default
  fullName: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.Default
  type: Property
  assemblies:
  - Sdl.Core.FineGrainedAlignment
  namespace: Sdl.Core.FineGrainedAlignment
  syntax:
    content: public static TranslationModelBuilderSettings Default { get; }
    parameters: []
    return:
      type: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings
    content.vb: Public Shared ReadOnly Property [Default] As TranslationModelBuilderSettings
  overload: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.Default*
references:
- uid: Sdl.Core.FineGrainedAlignment
  commentId: N:Sdl.Core.FineGrainedAlignment
  isExternal: true
  href: Sdl.html
  name: Sdl.Core.FineGrainedAlignment
  nameWithType: Sdl.Core.FineGrainedAlignment
  fullName: Sdl.Core.FineGrainedAlignment
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Core
    name: Core
    isExternal: true
    href: Sdl.Core.html
  - name: .
  - uid: Sdl.Core.FineGrainedAlignment
    name: FineGrainedAlignment
    isExternal: true
    href: Sdl.Core.FineGrainedAlignment.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Core
    name: Core
    isExternal: true
    href: Sdl.Core.html
  - name: .
  - uid: Sdl.Core.FineGrainedAlignment
    name: FineGrainedAlignment
    isExternal: true
    href: Sdl.Core.FineGrainedAlignment.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.#ctor*
  commentId: Overload:Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.#ctor
  isExternal: true
  href: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.html#Sdl_Core_FineGrainedAlignment_TranslationModelBuilderSettings__ctor_System_Int32_
  name: TranslationModelBuilderSettings
  nameWithType: TranslationModelBuilderSettings.TranslationModelBuilderSettings
  fullName: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.TranslationModelBuilderSettings
  nameWithType.vb: TranslationModelBuilderSettings.New
  fullName.vb: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.New
  name.vb: New
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.MinModelSampleSize*
  commentId: Overload:Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.MinModelSampleSize
  isExternal: true
  href: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.html#Sdl_Core_FineGrainedAlignment_TranslationModelBuilderSettings_MinModelSampleSize
  name: MinModelSampleSize
  nameWithType: TranslationModelBuilderSettings.MinModelSampleSize
  fullName: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.MinModelSampleSize
- uid: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.Default*
  commentId: Overload:Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.Default
  isExternal: true
  href: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.html#Sdl_Core_FineGrainedAlignment_TranslationModelBuilderSettings_Default
  name: Default
  nameWithType: TranslationModelBuilderSettings.Default
  fullName: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.Default
- uid: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings
  commentId: T:Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings
  parent: Sdl.Core.FineGrainedAlignment
  isExternal: true
  href: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings.html
  name: TranslationModelBuilderSettings
  nameWithType: TranslationModelBuilderSettings
  fullName: Sdl.Core.FineGrainedAlignment.TranslationModelBuilderSettings
