### YamlMime:ManagedReference
items:
- uid: Sdl.LanguagePlatform.TranslationMemory.ExportSettings
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.ExportSettings
  id: ExportSettings
  parent: Sdl.LanguagePlatform.TranslationMemory
  children:
  - Sdl.LanguagePlatform.TranslationMemory.ExportSettings.#ctor
  - Sdl.LanguagePlatform.TranslationMemory.ExportSettings.EditScript
  - Sdl.LanguagePlatform.TranslationMemory.ExportSettings.Filter
  langs:
  - csharp
  - vb
  name: ExportSettings
  nameWithType: ExportSettings
  fullName: Sdl.LanguagePlatform.TranslationMemory.ExportSettings
  type: Class
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: Encapsulates settings and parameters for export.
  example: []
  syntax:
    content: >-
      [DataContract]

      public class ExportSettings
    content.vb: >-
      <DataContract>

      Public Class ExportSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  attributes:
  - type: System.Runtime.Serialization.DataContractAttribute
    ctor: System.Runtime.Serialization.DataContractAttribute.#ctor
    arguments: []
- uid: Sdl.LanguagePlatform.TranslationMemory.ExportSettings.#ctor
  commentId: M:Sdl.LanguagePlatform.TranslationMemory.ExportSettings.#ctor
  id: '#ctor'
  parent: Sdl.LanguagePlatform.TranslationMemory.ExportSettings
  langs:
  - csharp
  - vb
  name: ExportSettings()
  nameWithType: ExportSettings.ExportSettings()
  fullName: Sdl.LanguagePlatform.TranslationMemory.ExportSettings.ExportSettings()
  type: Constructor
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: public ExportSettings()
    content.vb: Public Sub New()
  overload: Sdl.LanguagePlatform.TranslationMemory.ExportSettings.#ctor*
  nameWithType.vb: ExportSettings.New()
  fullName.vb: Sdl.LanguagePlatform.TranslationMemory.ExportSettings.New()
  name.vb: New()
- uid: Sdl.LanguagePlatform.TranslationMemory.ExportSettings.Filter
  commentId: P:Sdl.LanguagePlatform.TranslationMemory.ExportSettings.Filter
  id: Filter
  parent: Sdl.LanguagePlatform.TranslationMemory.ExportSettings
  langs:
  - csharp
  - vb
  name: Filter
  nameWithType: ExportSettings.Filter
  fullName: Sdl.LanguagePlatform.TranslationMemory.ExportSettings.Filter
  type: Property
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: If a filter is set, only TUs which match the filter will be exported.
  example: []
  syntax:
    content: >-
      [DataMember]

      public FilterExpression Filter { get; set; }
    parameters: []
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.FilterExpression
    content.vb: >-
      <DataMember>

      Public Property Filter As FilterExpression
  overload: Sdl.LanguagePlatform.TranslationMemory.ExportSettings.Filter*
  attributes:
  - type: System.Runtime.Serialization.DataMemberAttribute
    ctor: System.Runtime.Serialization.DataMemberAttribute.#ctor
    arguments: []
- uid: Sdl.LanguagePlatform.TranslationMemory.ExportSettings.EditScript
  commentId: P:Sdl.LanguagePlatform.TranslationMemory.ExportSettings.EditScript
  id: EditScript
  parent: Sdl.LanguagePlatform.TranslationMemory.ExportSettings
  langs:
  - csharp
  - vb
  name: EditScript
  nameWithType: ExportSettings.EditScript
  fullName: Sdl.LanguagePlatform.TranslationMemory.ExportSettings.EditScript
  type: Property
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: >-
    If an edit script is set, it will be applied before the TU is exported, but after

    the filter conditions (if present) are evaluated.
  example: []
  syntax:
    content: >-
      [DataMember]

      public EditScript EditScript { get; set; }
    parameters: []
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.EditScripts.EditScript
    content.vb: >-
      <DataMember>

      Public Property EditScript As EditScript
  overload: Sdl.LanguagePlatform.TranslationMemory.ExportSettings.EditScript*
  attributes:
  - type: System.Runtime.Serialization.DataMemberAttribute
    ctor: System.Runtime.Serialization.DataMemberAttribute.#ctor
    arguments: []
references:
- uid: Sdl.LanguagePlatform.TranslationMemory
  commentId: N:Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  href: Sdl.html
  name: Sdl.LanguagePlatform.TranslationMemory
  nameWithType: Sdl.LanguagePlatform.TranslationMemory
  fullName: Sdl.LanguagePlatform.TranslationMemory
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.LanguagePlatform
    name: LanguagePlatform
    isExternal: true
    href: Sdl.LanguagePlatform.html
  - name: .
  - uid: Sdl.LanguagePlatform.TranslationMemory
    name: TranslationMemory
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.LanguagePlatform
    name: LanguagePlatform
    isExternal: true
    href: Sdl.LanguagePlatform.html
  - name: .
  - uid: Sdl.LanguagePlatform.TranslationMemory
    name: TranslationMemory
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.LanguagePlatform.TranslationMemory.ExportSettings.#ctor*
  commentId: Overload:Sdl.LanguagePlatform.TranslationMemory.ExportSettings.#ctor
  isExternal: true
  href: Sdl.LanguagePlatform.TranslationMemory.ExportSettings.html#Sdl_LanguagePlatform_TranslationMemory_ExportSettings__ctor
  name: ExportSettings
  nameWithType: ExportSettings.ExportSettings
  fullName: Sdl.LanguagePlatform.TranslationMemory.ExportSettings.ExportSettings
  nameWithType.vb: ExportSettings.New
  fullName.vb: Sdl.LanguagePlatform.TranslationMemory.ExportSettings.New
  name.vb: New
- uid: Sdl.LanguagePlatform.TranslationMemory.ExportSettings.Filter*
  commentId: Overload:Sdl.LanguagePlatform.TranslationMemory.ExportSettings.Filter
  isExternal: true
  href: Sdl.LanguagePlatform.TranslationMemory.ExportSettings.html#Sdl_LanguagePlatform_TranslationMemory_ExportSettings_Filter
  name: Filter
  nameWithType: ExportSettings.Filter
  fullName: Sdl.LanguagePlatform.TranslationMemory.ExportSettings.Filter
- uid: Sdl.LanguagePlatform.TranslationMemory.FilterExpression
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.FilterExpression
  parent: Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  href: Sdl.LanguagePlatform.TranslationMemory.FilterExpression.html
  name: FilterExpression
  nameWithType: FilterExpression
  fullName: Sdl.LanguagePlatform.TranslationMemory.FilterExpression
- uid: Sdl.LanguagePlatform.TranslationMemory.ExportSettings.EditScript*
  commentId: Overload:Sdl.LanguagePlatform.TranslationMemory.ExportSettings.EditScript
  isExternal: true
  href: Sdl.LanguagePlatform.TranslationMemory.ExportSettings.html#Sdl_LanguagePlatform_TranslationMemory_ExportSettings_EditScript
  name: EditScript
  nameWithType: ExportSettings.EditScript
  fullName: Sdl.LanguagePlatform.TranslationMemory.ExportSettings.EditScript
- uid: Sdl.LanguagePlatform.TranslationMemory.EditScripts.EditScript
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.EditScripts.EditScript
  parent: Sdl.LanguagePlatform.TranslationMemory.EditScripts
  isExternal: true
  href: Sdl.LanguagePlatform.TranslationMemory.EditScripts.EditScript.html
  name: EditScript
  nameWithType: EditScript
  fullName: Sdl.LanguagePlatform.TranslationMemory.EditScripts.EditScript
- uid: Sdl.LanguagePlatform.TranslationMemory.EditScripts
  commentId: N:Sdl.LanguagePlatform.TranslationMemory.EditScripts
  isExternal: true
  href: Sdl.html
  name: Sdl.LanguagePlatform.TranslationMemory.EditScripts
  nameWithType: Sdl.LanguagePlatform.TranslationMemory.EditScripts
  fullName: Sdl.LanguagePlatform.TranslationMemory.EditScripts
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.LanguagePlatform
    name: LanguagePlatform
    isExternal: true
    href: Sdl.LanguagePlatform.html
  - name: .
  - uid: Sdl.LanguagePlatform.TranslationMemory
    name: TranslationMemory
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.html
  - name: .
  - uid: Sdl.LanguagePlatform.TranslationMemory.EditScripts
    name: EditScripts
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.EditScripts.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.LanguagePlatform
    name: LanguagePlatform
    isExternal: true
    href: Sdl.LanguagePlatform.html
  - name: .
  - uid: Sdl.LanguagePlatform.TranslationMemory
    name: TranslationMemory
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.html
  - name: .
  - uid: Sdl.LanguagePlatform.TranslationMemory.EditScripts
    name: EditScripts
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.EditScripts.html
