### YamlMime:ManagedReference
items:
- uid: Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator
  id: ComposedExpression.Operator
  parent: Sdl.LanguagePlatform.TranslationMemory
  children:
  - Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator.And
  - Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator.Not
  - Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator.Or
  langs:
  - csharp
  - vb
  name: ComposedExpression.Operator
  nameWithType: ComposedExpression.Operator
  fullName: Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator
  type: Enum
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: public enum Operator
    content.vb: Public Enum Operator
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator.Not
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator.Not
  id: Not
  parent: Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator
  langs:
  - csharp
  - vb
  name: Not
  nameWithType: ComposedExpression.Operator.Not
  fullName: Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator.Not
  type: Field
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: Not = 1
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator.And
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator.And
  id: And
  parent: Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator
  langs:
  - csharp
  - vb
  name: And
  nameWithType: ComposedExpression.Operator.And
  fullName: Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator.And
  type: Field
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: And = 2
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator.Or
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator.Or
  id: Or
  parent: Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator
  langs:
  - csharp
  - vb
  name: Or
  nameWithType: ComposedExpression.Operator.Or
  fullName: Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator.Or
  type: Field
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: Or = 3
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Sdl.LanguagePlatform.TranslationMemory
  commentId: N:Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  name: Sdl.LanguagePlatform.TranslationMemory
  nameWithType: Sdl.LanguagePlatform.TranslationMemory
  fullName: Sdl.LanguagePlatform.TranslationMemory
- uid: Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator
  parent: Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  name: ComposedExpression.Operator
  nameWithType: ComposedExpression.Operator
  fullName: Sdl.LanguagePlatform.TranslationMemory.ComposedExpression.Operator
