### YamlMime:ManagedReference
items:
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  id: ImportSettings.TUUpdateMode
  parent: Sdl.LanguagePlatform.TranslationMemory
  children:
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.AddNew
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.KeepMostRecent
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.LeaveUnchanged
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.Overwrite
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.OverwriteCurrent
  langs:
  - csharp
  - vb
  name: ImportSettings.TUUpdateMode
  nameWithType: ImportSettings.TUUpdateMode
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  type: Enum
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: The mode to update TU when a TU with the same source segment already exists in the TM
  example: []
  syntax:
    content: public enum ImportSettings.TUUpdateMode
    content.vb: Public Enum ImportSettings.TUUpdateMode
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.AddNew
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.AddNew
  id: AddNew
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  langs:
  - csharp
  - vb
  name: AddNew
  nameWithType: ImportSettings.TUUpdateMode.AddNew
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.AddNew
  type: Field
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: Add a new TU and leave the original TU with the same source untouched.
  example: []
  syntax:
    content: AddNew = 0
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.Overwrite
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.Overwrite
  id: Overwrite
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  langs:
  - csharp
  - vb
  name: Overwrite
  nameWithType: ImportSettings.TUUpdateMode.Overwrite
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.Overwrite
  type: Field
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: Overwrite all the existing TUs where source segment matches with the new content.
  example: []
  syntax:
    content: Overwrite = 1
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.LeaveUnchanged
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.LeaveUnchanged
  id: LeaveUnchanged
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  langs:
  - csharp
  - vb
  name: LeaveUnchanged
  nameWithType: ImportSettings.TUUpdateMode.LeaveUnchanged
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.LeaveUnchanged
  type: Field
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: Do not change the existing TUs with same source segment and ignore the new TU.
  example: []
  syntax:
    content: LeaveUnchanged = 2
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.KeepMostRecent
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.KeepMostRecent
  id: KeepMostRecent
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  langs:
  - csharp
  - vb
  name: KeepMostRecent
  nameWithType: ImportSettings.TUUpdateMode.KeepMostRecent
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.KeepMostRecent
  type: Field
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: Delete all the existing TUs with matching source segments and leaves only the most recent TU.
  example: []
  syntax:
    content: KeepMostRecent = 3
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.OverwriteCurrent
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.OverwriteCurrent
  id: OverwriteCurrent
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  langs:
  - csharp
  - vb
  name: OverwriteCurrent
  nameWithType: ImportSettings.TUUpdateMode.OverwriteCurrent
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.OverwriteCurrent
  type: Field
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: Overwrites only the current TUs where the source segment matches and leaves other existing TUs unmodified.
  example: []
  syntax:
    content: OverwriteCurrent = 4
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
references:
- uid: Sdl.LanguagePlatform.TranslationMemory
  commentId: N:Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  href: Sdl.html
  name: Sdl.LanguagePlatform.TranslationMemory
  nameWithType: Sdl.LanguagePlatform.TranslationMemory
  fullName: Sdl.LanguagePlatform.TranslationMemory
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.LanguagePlatform
    name: LanguagePlatform
    isExternal: true
    href: Sdl.LanguagePlatform.html
  - name: .
  - uid: Sdl.LanguagePlatform.TranslationMemory
    name: TranslationMemory
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.LanguagePlatform
    name: LanguagePlatform
    isExternal: true
    href: Sdl.LanguagePlatform.html
  - name: .
  - uid: Sdl.LanguagePlatform.TranslationMemory
    name: TranslationMemory
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.html
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  parent: Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  href: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.html
  name: ImportSettings.TUUpdateMode
  nameWithType: ImportSettings.TUUpdateMode
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
  spec.csharp:
  - uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings
    name: ImportSettings
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.html
  - name: .
  - uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
    name: TUUpdateMode
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.html
  spec.vb:
  - uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings
    name: ImportSettings
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.html
  - name: .
  - uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode
    name: TUUpdateMode
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.TUUpdateMode.html
