### YamlMime:ManagedReference
items:
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  id: ImportSettings.NewFieldsOption
  parent: Sdl.LanguagePlatform.TranslationMemory
  children:
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.AddToSetup
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.Error
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.Ignore
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.SkipTranslationUnit
  langs:
  - csharp
  - vb
  name: ImportSettings.NewFieldsOption
  nameWithType: ImportSettings.NewFieldsOption
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  type: Enum
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: "\nSpecifies how the system should react if an import or an add operation would result in a change to the setup \n(such as implicitly adding unknown fields or field values).\n"
  syntax:
    content: public enum NewFieldsOption
    content.vb: Public Enum NewFieldsOption
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.AddToSetup
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.AddToSetup
  id: AddToSetup
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  langs:
  - csharp
  - vb
  name: AddToSetup
  nameWithType: ImportSettings.NewFieldsOption.AddToSetup
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.AddToSetup
  type: Field
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: "\nThe translation unit is processed and unknown user-defined fields are automatically added to the setup.\n"
  syntax:
    content: AddToSetup = 0
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.Ignore
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.Ignore
  id: Ignore
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  langs:
  - csharp
  - vb
  name: Ignore
  nameWithType: ImportSettings.NewFieldsOption.Ignore
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.Ignore
  type: Field
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: "\nThe translation unit is processed and unknown user-defined fields are ignored (not added to the setup).\n"
  syntax:
    content: Ignore = 1
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.SkipTranslationUnit
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.SkipTranslationUnit
  id: SkipTranslationUnit
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  langs:
  - csharp
  - vb
  name: SkipTranslationUnit
  nameWithType: ImportSettings.NewFieldsOption.SkipTranslationUnit
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.SkipTranslationUnit
  type: Field
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: "\nThe translation units containing unknown user-defined fields are skipped.\n"
  syntax:
    content: SkipTranslationUnit = 2
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.Error
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.Error
  id: Error
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  langs:
  - csharp
  - vb
  name: Error
  nameWithType: ImportSettings.NewFieldsOption.Error
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption.Error
  type: Field
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: "\nIf any translation unit contains an unknown user-defined field an error is thrown.\n"
  syntax:
    content: Error = 3
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Sdl.LanguagePlatform.TranslationMemory
  commentId: N:Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  name: Sdl.LanguagePlatform.TranslationMemory
  nameWithType: Sdl.LanguagePlatform.TranslationMemory
  fullName: Sdl.LanguagePlatform.TranslationMemory
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
  parent: Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  name: ImportSettings.NewFieldsOption
  nameWithType: ImportSettings.NewFieldsOption
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.NewFieldsOption
