### YamlMime:ManagedReference
items:
- uid: Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings
  commentId: T:Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings
  id: BilingualPhraseComputer3.Settings
  parent: Sdl.Core.FineGrainedAlignment
  children:
  - Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings.#ctor
  - Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings.Incremental
  - Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings.MaximumPhraseLength
  - Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings.MinimumLikelihood
  langs:
  - csharp
  - vb
  name: BilingualPhraseComputer3.Settings
  nameWithType: BilingualPhraseComputer3.Settings
  fullName: Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings
  type: Class
  source:
    path: Sdl.Core.FineGrainedAlignment
    isExternal: true
  assemblies:
  - Sdl.Core.FineGrainedAlignment
  namespace: Sdl.Core.FineGrainedAlignment
  syntax:
    content: 'public class Settings : Object'
    content.vb: >-
      Public Class Settings
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings.MaximumPhraseLength
  commentId: F:Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings.MaximumPhraseLength
  id: MaximumPhraseLength
  parent: Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings
  langs:
  - csharp
  - vb
  name: MaximumPhraseLength
  nameWithType: BilingualPhraseComputer3.Settings.MaximumPhraseLength
  fullName: Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings.MaximumPhraseLength
  type: Field
  source:
    path: Sdl.Core.FineGrainedAlignment
    isExternal: true
  assemblies:
  - Sdl.Core.FineGrainedAlignment
  namespace: Sdl.Core.FineGrainedAlignment
  syntax:
    content: public int MaximumPhraseLength
    return:
      type: System.Int32
    content.vb: Public MaximumPhraseLength As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings.MinimumLikelihood
  commentId: F:Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings.MinimumLikelihood
  id: MinimumLikelihood
  parent: Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings
  langs:
  - csharp
  - vb
  name: MinimumLikelihood
  nameWithType: BilingualPhraseComputer3.Settings.MinimumLikelihood
  fullName: Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings.MinimumLikelihood
  type: Field
  source:
    path: Sdl.Core.FineGrainedAlignment
    isExternal: true
  assemblies:
  - Sdl.Core.FineGrainedAlignment
  namespace: Sdl.Core.FineGrainedAlignment
  syntax:
    content: public double MinimumLikelihood
    return:
      type: System.Double
    content.vb: Public MinimumLikelihood As Double
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings.Incremental
  commentId: F:Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings.Incremental
  id: Incremental
  parent: Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings
  langs:
  - csharp
  - vb
  name: Incremental
  nameWithType: BilingualPhraseComputer3.Settings.Incremental
  fullName: Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings.Incremental
  type: Field
  source:
    path: Sdl.Core.FineGrainedAlignment
    isExternal: true
  assemblies:
  - Sdl.Core.FineGrainedAlignment
  namespace: Sdl.Core.FineGrainedAlignment
  syntax:
    content: public bool Incremental
    return:
      type: System.Boolean
    content.vb: Public Incremental As Boolean
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings.#ctor
  commentId: M:Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings.#ctor
  id: '#ctor'
  parent: Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings
  langs:
  - csharp
  - vb
  name: Settings()
  nameWithType: BilingualPhraseComputer3.Settings.Settings()
  fullName: Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings.Settings()
  type: Constructor
  source:
    path: Sdl.Core.FineGrainedAlignment
    isExternal: true
  assemblies:
  - Sdl.Core.FineGrainedAlignment
  namespace: Sdl.Core.FineGrainedAlignment
  syntax:
    content: public Settings()
    content.vb: Public Sub New
  overload: Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Sdl.Core.FineGrainedAlignment
  commentId: N:Sdl.Core.FineGrainedAlignment
  isExternal: true
  name: Sdl.Core.FineGrainedAlignment
  nameWithType: Sdl.Core.FineGrainedAlignment
  fullName: Sdl.Core.FineGrainedAlignment
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Double
  commentId: T:System.Double
  parent: System
  isExternal: true
  name: Double
  nameWithType: Double
  fullName: System.Double
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings.#ctor*
  commentId: Overload:Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings.#ctor
  isExternal: true
  name: Settings
  nameWithType: BilingualPhraseComputer3.Settings.Settings
  fullName: Sdl.Core.FineGrainedAlignment.BilingualPhraseComputer3.Settings.Settings
