### YamlMime:ManagedReference
items:
- uid: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings
  id: FuzzyIndexTuningSettings
  parent: Sdl.LanguagePlatform.TranslationMemory
  children:
  - Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.#ctor
  - Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinScoreIncrease
  - Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthSourceCharIndex
  - Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthSourceWordIndex
  - Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthTargetCharIndex
  - Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthTargetWordIndex
  langs:
  - csharp
  - vb
  name: FuzzyIndexTuningSettings
  nameWithType: FuzzyIndexTuningSettings
  fullName: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings
  type: Class
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: public class FuzzyIndexTuningSettings
    content.vb: Public Class FuzzyIndexTuningSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.#ctor
  commentId: M:Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.#ctor
  id: '#ctor'
  parent: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings
  langs:
  - csharp
  - vb
  name: FuzzyIndexTuningSettings()
  nameWithType: FuzzyIndexTuningSettings.FuzzyIndexTuningSettings()
  fullName: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.FuzzyIndexTuningSettings()
  type: Constructor
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: public FuzzyIndexTuningSettings()
    content.vb: Public Sub New
  overload: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinScoreIncrease
  commentId: P:Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinScoreIncrease
  id: MinScoreIncrease
  parent: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings
  langs:
  - csharp
  - vb
  name: MinScoreIncrease
  nameWithType: FuzzyIndexTuningSettings.MinScoreIncrease
  fullName: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinScoreIncrease
  type: Property
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: public int MinScoreIncrease { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MinScoreIncrease As Integer
  overload: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinScoreIncrease*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthSourceWordIndex
  commentId: P:Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthSourceWordIndex
  id: MinSearchVectorLengthSourceWordIndex
  parent: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings
  langs:
  - csharp
  - vb
  name: MinSearchVectorLengthSourceWordIndex
  nameWithType: FuzzyIndexTuningSettings.MinSearchVectorLengthSourceWordIndex
  fullName: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthSourceWordIndex
  type: Property
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: public int MinSearchVectorLengthSourceWordIndex { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MinSearchVectorLengthSourceWordIndex As Integer
  overload: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthSourceWordIndex*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthTargetWordIndex
  commentId: P:Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthTargetWordIndex
  id: MinSearchVectorLengthTargetWordIndex
  parent: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings
  langs:
  - csharp
  - vb
  name: MinSearchVectorLengthTargetWordIndex
  nameWithType: FuzzyIndexTuningSettings.MinSearchVectorLengthTargetWordIndex
  fullName: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthTargetWordIndex
  type: Property
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: public int MinSearchVectorLengthTargetWordIndex { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MinSearchVectorLengthTargetWordIndex As Integer
  overload: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthTargetWordIndex*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthSourceCharIndex
  commentId: P:Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthSourceCharIndex
  id: MinSearchVectorLengthSourceCharIndex
  parent: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings
  langs:
  - csharp
  - vb
  name: MinSearchVectorLengthSourceCharIndex
  nameWithType: FuzzyIndexTuningSettings.MinSearchVectorLengthSourceCharIndex
  fullName: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthSourceCharIndex
  type: Property
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: public int MinSearchVectorLengthSourceCharIndex { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MinSearchVectorLengthSourceCharIndex As Integer
  overload: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthSourceCharIndex*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthTargetCharIndex
  commentId: P:Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthTargetCharIndex
  id: MinSearchVectorLengthTargetCharIndex
  parent: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings
  langs:
  - csharp
  - vb
  name: MinSearchVectorLengthTargetCharIndex
  nameWithType: FuzzyIndexTuningSettings.MinSearchVectorLengthTargetCharIndex
  fullName: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthTargetCharIndex
  type: Property
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  syntax:
    content: public int MinSearchVectorLengthTargetCharIndex { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MinSearchVectorLengthTargetCharIndex As Integer
  overload: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthTargetCharIndex*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Sdl.LanguagePlatform.TranslationMemory
  commentId: N:Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  name: Sdl.LanguagePlatform.TranslationMemory
  nameWithType: Sdl.LanguagePlatform.TranslationMemory
  fullName: Sdl.LanguagePlatform.TranslationMemory
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.#ctor*
  commentId: Overload:Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.#ctor
  isExternal: true
  name: FuzzyIndexTuningSettings
  nameWithType: FuzzyIndexTuningSettings.FuzzyIndexTuningSettings
  fullName: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.FuzzyIndexTuningSettings
- uid: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinScoreIncrease*
  commentId: Overload:Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinScoreIncrease
  isExternal: true
  name: MinScoreIncrease
  nameWithType: FuzzyIndexTuningSettings.MinScoreIncrease
  fullName: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinScoreIncrease
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthSourceWordIndex*
  commentId: Overload:Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthSourceWordIndex
  isExternal: true
  name: MinSearchVectorLengthSourceWordIndex
  nameWithType: FuzzyIndexTuningSettings.MinSearchVectorLengthSourceWordIndex
  fullName: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthSourceWordIndex
- uid: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthTargetWordIndex*
  commentId: Overload:Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthTargetWordIndex
  isExternal: true
  name: MinSearchVectorLengthTargetWordIndex
  nameWithType: FuzzyIndexTuningSettings.MinSearchVectorLengthTargetWordIndex
  fullName: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthTargetWordIndex
- uid: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthSourceCharIndex*
  commentId: Overload:Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthSourceCharIndex
  isExternal: true
  name: MinSearchVectorLengthSourceCharIndex
  nameWithType: FuzzyIndexTuningSettings.MinSearchVectorLengthSourceCharIndex
  fullName: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthSourceCharIndex
- uid: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthTargetCharIndex*
  commentId: Overload:Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthTargetCharIndex
  isExternal: true
  name: MinSearchVectorLengthTargetCharIndex
  nameWithType: FuzzyIndexTuningSettings.MinSearchVectorLengthTargetCharIndex
  fullName: Sdl.LanguagePlatform.TranslationMemory.FuzzyIndexTuningSettings.MinSearchVectorLengthTargetCharIndex
