### YamlMime:ManagedReference
items:
- uid: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings
  id: TuLimitsValidatorSettings
  parent: Sdl.LanguagePlatform.TranslationMemory
  children:
  - Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.#ctor(System.Nullable{System.Int32},System.Nullable{System.Int32})
  - Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.SegmentLengthLimit
  - Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TagNestingLimit
  langs:
  - csharp
  - vb
  name: TuLimitsValidatorSettings
  nameWithType: TuLimitsValidatorSettings
  fullName: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings
  type: Class
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: Settings object for a TU limits validator
  example: []
  syntax:
    content: public class TuLimitsValidatorSettings
    content.vb: Public Class TuLimitsValidatorSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
- uid: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.#ctor(System.Nullable{System.Int32},System.Nullable{System.Int32})
  commentId: M:Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.#ctor(System.Nullable{System.Int32},System.Nullable{System.Int32})
  id: '#ctor(System.Nullable{System.Int32},System.Nullable{System.Int32})'
  parent: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings
  langs:
  - csharp
  - vb
  name: TuLimitsValidatorSettings(int?, int?)
  nameWithType: TuLimitsValidatorSettings.TuLimitsValidatorSettings(int?, int?)
  fullName: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TuLimitsValidatorSettings(int?, int?)
  type: Constructor
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: Initializes a new instance.
  example: []
  syntax:
    content: public TuLimitsValidatorSettings(int? segmentLengthLimit = null, int? tagNestingLimit = null)
    parameters:
    - id: segmentLengthLimit
      type: System.Nullable{System.Int32}
      description: Maximum length of a TU segment to be considered valid
    - id: tagNestingLimit
      type: System.Nullable{System.Int32}
      description: Maximum nesting level of a TU segment to be considered valid
    content.vb: Public Sub New(segmentLengthLimit As Integer? = Nothing, tagNestingLimit As Integer? = Nothing)
  overload: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.#ctor*
  nameWithType.vb: TuLimitsValidatorSettings.New(Integer?, Integer?)
  fullName.vb: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.New(Integer?, Integer?)
  name.vb: New(Integer?, Integer?)
- uid: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.SegmentLengthLimit
  commentId: P:Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.SegmentLengthLimit
  id: SegmentLengthLimit
  parent: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings
  langs:
  - csharp
  - vb
  name: SegmentLengthLimit
  nameWithType: TuLimitsValidatorSettings.SegmentLengthLimit
  fullName: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.SegmentLengthLimit
  type: Property
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: Gets a value specifying the maximum length of a TU segment to be considered valid
  example: []
  syntax:
    content: public int? SegmentLengthLimit { get; }
    parameters: []
    return:
      type: System.Nullable{System.Int32}
    content.vb: Public ReadOnly Property SegmentLengthLimit As Integer?
  overload: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.SegmentLengthLimit*
- uid: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TagNestingLimit
  commentId: P:Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TagNestingLimit
  id: TagNestingLimit
  parent: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings
  langs:
  - csharp
  - vb
  name: TagNestingLimit
  nameWithType: TuLimitsValidatorSettings.TagNestingLimit
  fullName: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TagNestingLimit
  type: Property
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: Gets a value specifying the maximum nesting level of a TU segment to be considered valid
  example: []
  syntax:
    content: public int? TagNestingLimit { get; }
    parameters: []
    return:
      type: System.Nullable{System.Int32}
    content.vb: Public ReadOnly Property TagNestingLimit As Integer?
  overload: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TagNestingLimit*
references:
- uid: Sdl.LanguagePlatform.TranslationMemory
  commentId: N:Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  href: Sdl.html
  name: Sdl.LanguagePlatform.TranslationMemory
  nameWithType: Sdl.LanguagePlatform.TranslationMemory
  fullName: Sdl.LanguagePlatform.TranslationMemory
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.LanguagePlatform
    name: LanguagePlatform
    isExternal: true
    href: Sdl.LanguagePlatform.html
  - name: .
  - uid: Sdl.LanguagePlatform.TranslationMemory
    name: TranslationMemory
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.LanguagePlatform
    name: LanguagePlatform
    isExternal: true
    href: Sdl.LanguagePlatform.html
  - name: .
  - uid: Sdl.LanguagePlatform.TranslationMemory
    name: TranslationMemory
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.#ctor*
  commentId: Overload:Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.#ctor
  isExternal: true
  href: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.html#Sdl_LanguagePlatform_TranslationMemory_TuLimitsValidatorSettings__ctor_System_Nullable_System_Int32__System_Nullable_System_Int32__
  name: TuLimitsValidatorSettings
  nameWithType: TuLimitsValidatorSettings.TuLimitsValidatorSettings
  fullName: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TuLimitsValidatorSettings
  nameWithType.vb: TuLimitsValidatorSettings.New
  fullName.vb: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.New
  name.vb: New
- uid: System.Nullable{System.Int32}
  commentId: T:System.Nullable{System.Int32}
  parent: System
  definition: System.Nullable`1
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int?
  nameWithType: int?
  fullName: int?
  nameWithType.vb: Integer?
  fullName.vb: Integer?
  name.vb: Integer?
  spec.csharp:
  - uid: System.Int32
    name: int
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: '?'
  spec.vb:
  - uid: System.Int32
    name: Integer
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: '?'
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.SegmentLengthLimit*
  commentId: Overload:Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.SegmentLengthLimit
  isExternal: true
  href: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.html#Sdl_LanguagePlatform_TranslationMemory_TuLimitsValidatorSettings_SegmentLengthLimit
  name: SegmentLengthLimit
  nameWithType: TuLimitsValidatorSettings.SegmentLengthLimit
  fullName: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.SegmentLengthLimit
- uid: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TagNestingLimit*
  commentId: Overload:Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TagNestingLimit
  isExternal: true
  href: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.html#Sdl_LanguagePlatform_TranslationMemory_TuLimitsValidatorSettings_TagNestingLimit
  name: TagNestingLimit
  nameWithType: TuLimitsValidatorSettings.TagNestingLimit
  fullName: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TagNestingLimit
