### YamlMime:ManagedReference
items:
- uid: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings
  id: TuLimitsValidatorSettings
  parent: Sdl.LanguagePlatform.TranslationMemory
  children:
  - Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.#ctor(System.Nullable{System.Int32},System.Nullable{System.Int32})
  - Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.SegmentLengthLimit
  - Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TagNestingLimit
  langs:
  - csharp
  - vb
  name: TuLimitsValidatorSettings
  nameWithType: TuLimitsValidatorSettings
  fullName: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings
  type: Class
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: "\nSettings object for a TU limits validator\n"
  syntax:
    content: public class TuLimitsValidatorSettings
    content.vb: Public Class TuLimitsValidatorSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.#ctor(System.Nullable{System.Int32},System.Nullable{System.Int32})
  commentId: M:Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.#ctor(System.Nullable{System.Int32},System.Nullable{System.Int32})
  id: '#ctor(System.Nullable{System.Int32},System.Nullable{System.Int32})'
  parent: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings
  langs:
  - csharp
  - vb
  name: TuLimitsValidatorSettings(Nullable<Int32>, Nullable<Int32>)
  nameWithType: TuLimitsValidatorSettings.TuLimitsValidatorSettings(Nullable<Int32>, Nullable<Int32>)
  fullName: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TuLimitsValidatorSettings(System.Nullable<System.Int32>, System.Nullable<System.Int32>)
  type: Constructor
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: "\nInitializes a new instance.\n"
  syntax:
    content: public TuLimitsValidatorSettings(int? segmentLengthLimit = null, int? tagNestingLimit = null)
    parameters:
    - id: segmentLengthLimit
      type: System.Nullable{System.Int32}
      description: Maximum length of a TU segment to be considered valid
    - id: tagNestingLimit
      type: System.Nullable{System.Int32}
      description: Maximum nesting level of a TU segment to be considered valid
    content.vb: Public Sub New(segmentLengthLimit As Integer? = Nothing, tagNestingLimit As Integer? = Nothing)
  overload: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.#ctor*
  nameWithType.vb: TuLimitsValidatorSettings.TuLimitsValidatorSettings(Nullable(Of Int32), Nullable(Of Int32))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TuLimitsValidatorSettings(System.Nullable(Of System.Int32), System.Nullable(Of System.Int32))
  name.vb: TuLimitsValidatorSettings(Nullable(Of Int32), Nullable(Of Int32))
- uid: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.SegmentLengthLimit
  commentId: P:Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.SegmentLengthLimit
  id: SegmentLengthLimit
  parent: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings
  langs:
  - csharp
  - vb
  name: SegmentLengthLimit
  nameWithType: TuLimitsValidatorSettings.SegmentLengthLimit
  fullName: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.SegmentLengthLimit
  type: Property
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: "\nGets a value specifying the maximum length of a TU segment to be considered valid\n"
  syntax:
    content: public int? SegmentLengthLimit { get; }
    parameters: []
    return:
      type: System.Nullable{System.Int32}
    content.vb: Public ReadOnly Property SegmentLengthLimit As Integer?
  overload: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.SegmentLengthLimit*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TagNestingLimit
  commentId: P:Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TagNestingLimit
  id: TagNestingLimit
  parent: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings
  langs:
  - csharp
  - vb
  name: TagNestingLimit
  nameWithType: TuLimitsValidatorSettings.TagNestingLimit
  fullName: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TagNestingLimit
  type: Property
  source:
    path: Sdl.LanguagePlatform.TranslationMemory
    isExternal: true
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: "\nGets a value specifying the maximum nesting level of a TU segment to be considered valid\n"
  syntax:
    content: public int? TagNestingLimit { get; }
    parameters: []
    return:
      type: System.Nullable{System.Int32}
    content.vb: Public ReadOnly Property TagNestingLimit As Integer?
  overload: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TagNestingLimit*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Sdl.LanguagePlatform.TranslationMemory
  commentId: N:Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  name: Sdl.LanguagePlatform.TranslationMemory
  nameWithType: Sdl.LanguagePlatform.TranslationMemory
  fullName: Sdl.LanguagePlatform.TranslationMemory
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.#ctor*
  commentId: Overload:Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.#ctor
  isExternal: true
  name: TuLimitsValidatorSettings
  nameWithType: TuLimitsValidatorSettings.TuLimitsValidatorSettings
  fullName: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TuLimitsValidatorSettings
- uid: System.Nullable{System.Int32}
  commentId: T:System.Nullable{System.Int32}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Int32>
  nameWithType: Nullable<Int32>
  fullName: System.Nullable<System.Int32>
  nameWithType.vb: Nullable(Of Int32)
  fullName.vb: System.Nullable(Of System.Int32)
  name.vb: Nullable(Of Int32)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<>
  nameWithType: Nullable<>
  fullName: System.Nullable<>
  nameWithType.vb: Nullable(Of )
  fullName.vb: System.Nullable(Of )
  name.vb: Nullable(Of )
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.SegmentLengthLimit*
  commentId: Overload:Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.SegmentLengthLimit
  isExternal: true
  name: SegmentLengthLimit
  nameWithType: TuLimitsValidatorSettings.SegmentLengthLimit
  fullName: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.SegmentLengthLimit
- uid: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TagNestingLimit*
  commentId: Overload:Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TagNestingLimit
  isExternal: true
  name: TagNestingLimit
  nameWithType: TuLimitsValidatorSettings.TagNestingLimit
  fullName: Sdl.LanguagePlatform.TranslationMemory.TuLimitsValidatorSettings.TagNestingLimit
