### YamlMime:ManagedReference
items:
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
  id: ImportSettings.FieldUpdateMode
  parent: Sdl.LanguagePlatform.TranslationMemory
  children:
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.LeaveUnchanged
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.Merge
  - Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.Overwrite
  langs:
  - csharp
  - vb
  name: ImportSettings.FieldUpdateMode
  nameWithType: ImportSettings.FieldUpdateMode
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
  type: Enum
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: Specifies how existing custom field data should be updated.
  example: []
  syntax:
    content: public enum ImportSettings.FieldUpdateMode
    content.vb: Public Enum ImportSettings.FieldUpdateMode
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.Merge
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.Merge
  id: Merge
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
  langs:
  - csharp
  - vb
  name: Merge
  nameWithType: ImportSettings.FieldUpdateMode.Merge
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.Merge
  type: Field
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: Field values of the imported TU are merged with that of the existing TU. This is the default.
  example: []
  syntax:
    content: Merge = 0
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.Overwrite
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.Overwrite
  id: Overwrite
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
  langs:
  - csharp
  - vb
  name: Overwrite
  nameWithType: ImportSettings.FieldUpdateMode.Overwrite
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.Overwrite
  type: Field
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: Field values of the existing TU are overwritten with that of the imported TU.
  example: []
  syntax:
    content: Overwrite = 1
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.LeaveUnchanged
  commentId: F:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.LeaveUnchanged
  id: LeaveUnchanged
  parent: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
  langs:
  - csharp
  - vb
  name: LeaveUnchanged
  nameWithType: ImportSettings.FieldUpdateMode.LeaveUnchanged
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.LeaveUnchanged
  type: Field
  assemblies:
  - Sdl.LanguagePlatform.TranslationMemory
  namespace: Sdl.LanguagePlatform.TranslationMemory
  summary: >-
    Field values of the existing TU are not changed, the field values of the imported TU 

    are discarded.
  example: []
  syntax:
    content: LeaveUnchanged = 2
    return:
      type: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
references:
- uid: Sdl.LanguagePlatform.TranslationMemory
  commentId: N:Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  href: Sdl.html
  name: Sdl.LanguagePlatform.TranslationMemory
  nameWithType: Sdl.LanguagePlatform.TranslationMemory
  fullName: Sdl.LanguagePlatform.TranslationMemory
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.LanguagePlatform
    name: LanguagePlatform
    isExternal: true
    href: Sdl.LanguagePlatform.html
  - name: .
  - uid: Sdl.LanguagePlatform.TranslationMemory
    name: TranslationMemory
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.LanguagePlatform
    name: LanguagePlatform
    isExternal: true
    href: Sdl.LanguagePlatform.html
  - name: .
  - uid: Sdl.LanguagePlatform.TranslationMemory
    name: TranslationMemory
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.html
- uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
  commentId: T:Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
  parent: Sdl.LanguagePlatform.TranslationMemory
  isExternal: true
  href: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.html
  name: ImportSettings.FieldUpdateMode
  nameWithType: ImportSettings.FieldUpdateMode
  fullName: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
  spec.csharp:
  - uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings
    name: ImportSettings
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.html
  - name: .
  - uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
    name: FieldUpdateMode
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.html
  spec.vb:
  - uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings
    name: ImportSettings
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.html
  - name: .
  - uid: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode
    name: FieldUpdateMode
    isExternal: true
    href: Sdl.LanguagePlatform.TranslationMemory.ImportSettings.FieldUpdateMode.html
