### YamlMime:ManagedReference
items:
- uid: Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings
  commentId: T:Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings
  id: TranslationMemoryMaintenanceSettingsStrings
  parent: Sdl.TranslationStudio.Api.TranslationMemoryManager
  children:
  - Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.LastBatchEditScript
  - Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.MaintenanceShowFieldValuesColumn_Setting
  - Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.MaintenanceTagDisplayMode_Setting
  - Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.NumberOfFieldValuesToDisplay_Setting
  - Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.NumberOfTranslationUnitsToDisplay_Setting
  - Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.ShowWhitespaceCharacters_Setting
  langs:
  - csharp
  - vb
  name: TranslationMemoryMaintenanceSettingsStrings
  nameWithType: TranslationMemoryMaintenanceSettingsStrings
  fullName: Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings
  type: Class
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.TranslationMemoryManager
  summary: "\nString constants representing the settings in ITranslationMemoryMaintenanceSettings.\n\n"
  syntax:
    content: public static class TranslationMemoryMaintenanceSettingsStrings
    content.vb: Public Module TranslationMemoryMaintenanceSettingsStrings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.MaintenanceTagDisplayMode_Setting
  commentId: F:Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.MaintenanceTagDisplayMode_Setting
  id: MaintenanceTagDisplayMode_Setting
  parent: Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings
  langs:
  - csharp
  - vb
  name: MaintenanceTagDisplayMode_Setting
  nameWithType: TranslationMemoryMaintenanceSettingsStrings.MaintenanceTagDisplayMode_Setting
  fullName: Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.MaintenanceTagDisplayMode_Setting
  type: Field
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.TranslationMemoryManager
  syntax:
    content: public const string MaintenanceTagDisplayMode_Setting = "MaintenanceTagDisplayMode"
    return:
      type: System.String
    content.vb: Public Const MaintenanceTagDisplayMode_Setting As String = "MaintenanceTagDisplayMode"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.MaintenanceShowFieldValuesColumn_Setting
  commentId: F:Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.MaintenanceShowFieldValuesColumn_Setting
  id: MaintenanceShowFieldValuesColumn_Setting
  parent: Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings
  langs:
  - csharp
  - vb
  name: MaintenanceShowFieldValuesColumn_Setting
  nameWithType: TranslationMemoryMaintenanceSettingsStrings.MaintenanceShowFieldValuesColumn_Setting
  fullName: Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.MaintenanceShowFieldValuesColumn_Setting
  type: Field
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.TranslationMemoryManager
  syntax:
    content: public const string MaintenanceShowFieldValuesColumn_Setting = "MaintenanceShowFieldValuesColumn"
    return:
      type: System.String
    content.vb: Public Const MaintenanceShowFieldValuesColumn_Setting As String = "MaintenanceShowFieldValuesColumn"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.NumberOfTranslationUnitsToDisplay_Setting
  commentId: F:Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.NumberOfTranslationUnitsToDisplay_Setting
  id: NumberOfTranslationUnitsToDisplay_Setting
  parent: Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings
  langs:
  - csharp
  - vb
  name: NumberOfTranslationUnitsToDisplay_Setting
  nameWithType: TranslationMemoryMaintenanceSettingsStrings.NumberOfTranslationUnitsToDisplay_Setting
  fullName: Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.NumberOfTranslationUnitsToDisplay_Setting
  type: Field
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.TranslationMemoryManager
  syntax:
    content: public const string NumberOfTranslationUnitsToDisplay_Setting = "NumberOfTranslationUnitsToDisplay"
    return:
      type: System.String
    content.vb: Public Const NumberOfTranslationUnitsToDisplay_Setting As String = "NumberOfTranslationUnitsToDisplay"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.NumberOfFieldValuesToDisplay_Setting
  commentId: F:Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.NumberOfFieldValuesToDisplay_Setting
  id: NumberOfFieldValuesToDisplay_Setting
  parent: Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings
  langs:
  - csharp
  - vb
  name: NumberOfFieldValuesToDisplay_Setting
  nameWithType: TranslationMemoryMaintenanceSettingsStrings.NumberOfFieldValuesToDisplay_Setting
  fullName: Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.NumberOfFieldValuesToDisplay_Setting
  type: Field
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.TranslationMemoryManager
  syntax:
    content: public const string NumberOfFieldValuesToDisplay_Setting = "NumberOfFieldValuesToDisplay"
    return:
      type: System.String
    content.vb: Public Const NumberOfFieldValuesToDisplay_Setting As String = "NumberOfFieldValuesToDisplay"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.ShowWhitespaceCharacters_Setting
  commentId: F:Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.ShowWhitespaceCharacters_Setting
  id: ShowWhitespaceCharacters_Setting
  parent: Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings
  langs:
  - csharp
  - vb
  name: ShowWhitespaceCharacters_Setting
  nameWithType: TranslationMemoryMaintenanceSettingsStrings.ShowWhitespaceCharacters_Setting
  fullName: Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.ShowWhitespaceCharacters_Setting
  type: Field
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.TranslationMemoryManager
  syntax:
    content: public const string ShowWhitespaceCharacters_Setting = "ShowWhitespaceCharacters_Setting"
    return:
      type: System.String
    content.vb: Public Const ShowWhitespaceCharacters_Setting As String = "ShowWhitespaceCharacters_Setting"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.LastBatchEditScript
  commentId: F:Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.LastBatchEditScript
  id: LastBatchEditScript
  parent: Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings
  langs:
  - csharp
  - vb
  name: LastBatchEditScript
  nameWithType: TranslationMemoryMaintenanceSettingsStrings.LastBatchEditScript
  fullName: Sdl.TranslationStudio.Api.TranslationMemoryManager.TranslationMemoryMaintenanceSettingsStrings.LastBatchEditScript
  type: Field
  source:
    path: Sdl.TranslationStudio.Api
    isExternal: true
  assemblies:
  - Sdl.TranslationStudio.Api
  namespace: Sdl.TranslationStudio.Api.TranslationMemoryManager
  syntax:
    content: public const string LastBatchEditScript = "LastBatchEditScript"
    return:
      type: System.String
    content.vb: Public Const LastBatchEditScript As String = "LastBatchEditScript"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Sdl.TranslationStudio.Api.TranslationMemoryManager
  commentId: N:Sdl.TranslationStudio.Api.TranslationMemoryManager
  isExternal: true
  name: Sdl.TranslationStudio.Api.TranslationMemoryManager
  nameWithType: Sdl.TranslationStudio.Api.TranslationMemoryManager
  fullName: Sdl.TranslationStudio.Api.TranslationMemoryManager
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
