### YamlMime:ManagedReference
items:
- uid: Sdl.Verification.Api.ITermVerifierSettingsContext
  commentId: T:Sdl.Verification.Api.ITermVerifierSettingsContext
  id: ITermVerifierSettingsContext
  parent: Sdl.Verification.Api
  children:
  - Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbaseName
  - Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbasePicklistFields
  - Sdl.Verification.Api.ITermVerifierSettingsContext.HasTermbase
  langs:
  - csharp
  - vb
  name: ITermVerifierSettingsContext
  nameWithType: ITermVerifierSettingsContext
  fullName: Sdl.Verification.Api.ITermVerifierSettingsContext
  type: Interface
  assemblies:
  - Sdl.Verification.Api
  namespace: Sdl.Verification.Api
  summary: >-
    ITermVerifierSettingsContext interface represents a term verifier settings context that provides 

    a term verifier settings page with the term access services that it needs.
  example: []
  syntax:
    content: >-
      [Obsolete("This API is deprecated and will be removed in a future version.")]

      public interface ITermVerifierSettingsContext
    content.vb: >-
      <Obsolete("This API is deprecated and will be removed in a future version.")>

      Public Interface ITermVerifierSettingsContext
  attributes:
  - type: System.ObsoleteAttribute
    ctor: System.ObsoleteAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: This API is deprecated and will be removed in a future version.
- uid: Sdl.Verification.Api.ITermVerifierSettingsContext.HasTermbase
  commentId: M:Sdl.Verification.Api.ITermVerifierSettingsContext.HasTermbase
  id: HasTermbase
  parent: Sdl.Verification.Api.ITermVerifierSettingsContext
  langs:
  - csharp
  - vb
  name: HasTermbase()
  nameWithType: ITermVerifierSettingsContext.HasTermbase()
  fullName: Sdl.Verification.Api.ITermVerifierSettingsContext.HasTermbase()
  type: Method
  assemblies:
  - Sdl.Verification.Api
  namespace: Sdl.Verification.Api
  summary: Determines whether the context has a termbase.
  example: []
  syntax:
    content: bool HasTermbase()
    return:
      type: System.Boolean
      description: whether context has termbase
    content.vb: Function HasTermbase() As Boolean
  overload: Sdl.Verification.Api.ITermVerifierSettingsContext.HasTermbase*
- uid: Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbaseName
  commentId: M:Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbaseName
  id: GetTermbaseName
  parent: Sdl.Verification.Api.ITermVerifierSettingsContext
  langs:
  - csharp
  - vb
  name: GetTermbaseName()
  nameWithType: ITermVerifierSettingsContext.GetTermbaseName()
  fullName: Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbaseName()
  type: Method
  assemblies:
  - Sdl.Verification.Api
  namespace: Sdl.Verification.Api
  summary: Gets the termbase name.
  example: []
  syntax:
    content: string GetTermbaseName()
    return:
      type: System.String
      description: termbase name
    content.vb: Function GetTermbaseName() As String
  overload: Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbaseName*
- uid: Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbasePicklistFields
  commentId: M:Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbasePicklistFields
  id: GetTermbasePicklistFields
  parent: Sdl.Verification.Api.ITermVerifierSettingsContext
  langs:
  - csharp
  - vb
  name: GetTermbasePicklistFields()
  nameWithType: ITermVerifierSettingsContext.GetTermbasePicklistFields()
  fullName: Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbasePicklistFields()
  type: Method
  assemblies:
  - Sdl.Verification.Api
  namespace: Sdl.Verification.Api
  summary: Gets the termbase picklist fields.
  example: []
  syntax:
    content: IEnumerable<TermPicklistField> GetTermbasePicklistFields()
    return:
      type: System.Collections.Generic.IEnumerable{Sdl.Verification.Api.TermPicklistField}
      description: termbase picklist fields
    content.vb: Function GetTermbasePicklistFields() As IEnumerable(Of TermPicklistField)
  overload: Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbasePicklistFields*
references:
- uid: Sdl.Verification.Api
  commentId: N:Sdl.Verification.Api
  isExternal: true
  href: Sdl.html
  name: Sdl.Verification.Api
  nameWithType: Sdl.Verification.Api
  fullName: Sdl.Verification.Api
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Verification
    name: Verification
    isExternal: true
    href: Sdl.Verification.html
  - name: .
  - uid: Sdl.Verification.Api
    name: Api
    isExternal: true
    href: Sdl.Verification.Api.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Verification
    name: Verification
    isExternal: true
    href: Sdl.Verification.html
  - name: .
  - uid: Sdl.Verification.Api
    name: Api
    isExternal: true
    href: Sdl.Verification.Api.html
- uid: Sdl.Verification.Api.ITermVerifierSettingsContext.HasTermbase*
  commentId: Overload:Sdl.Verification.Api.ITermVerifierSettingsContext.HasTermbase
  isExternal: true
  href: Sdl.Verification.Api.ITermVerifierSettingsContext.html#Sdl_Verification_Api_ITermVerifierSettingsContext_HasTermbase
  name: HasTermbase
  nameWithType: ITermVerifierSettingsContext.HasTermbase
  fullName: Sdl.Verification.Api.ITermVerifierSettingsContext.HasTermbase
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbaseName*
  commentId: Overload:Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbaseName
  isExternal: true
  href: Sdl.Verification.Api.ITermVerifierSettingsContext.html#Sdl_Verification_Api_ITermVerifierSettingsContext_GetTermbaseName
  name: GetTermbaseName
  nameWithType: ITermVerifierSettingsContext.GetTermbaseName
  fullName: Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbaseName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbasePicklistFields*
  commentId: Overload:Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbasePicklistFields
  isExternal: true
  href: Sdl.Verification.Api.ITermVerifierSettingsContext.html#Sdl_Verification_Api_ITermVerifierSettingsContext_GetTermbasePicklistFields
  name: GetTermbasePicklistFields
  nameWithType: ITermVerifierSettingsContext.GetTermbasePicklistFields
  fullName: Sdl.Verification.Api.ITermVerifierSettingsContext.GetTermbasePicklistFields
- uid: System.Collections.Generic.IEnumerable{Sdl.Verification.Api.TermPicklistField}
  commentId: T:System.Collections.Generic.IEnumerable{Sdl.Verification.Api.TermPicklistField}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<TermPicklistField>
  nameWithType: IEnumerable<TermPicklistField>
  fullName: System.Collections.Generic.IEnumerable<Sdl.Verification.Api.TermPicklistField>
  nameWithType.vb: IEnumerable(Of TermPicklistField)
  fullName.vb: System.Collections.Generic.IEnumerable(Of Sdl.Verification.Api.TermPicklistField)
  name.vb: IEnumerable(Of TermPicklistField)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - uid: Sdl.Verification.Api.TermPicklistField
    name: TermPicklistField
    isExternal: true
    href: Sdl.Verification.Api.TermPicklistField.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - uid: Sdl.Verification.Api.TermPicklistField
    name: TermPicklistField
    isExternal: true
    href: Sdl.Verification.Api.TermPicklistField.html
  - name: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
