### YamlMime:ManagedReference
items:
- uid: Sdl.Verification.Api.ITermVerifierSettingsContextAware
  commentId: T:Sdl.Verification.Api.ITermVerifierSettingsContextAware
  id: ITermVerifierSettingsContextAware
  parent: Sdl.Verification.Api
  children:
  - Sdl.Verification.Api.ITermVerifierSettingsContextAware.TermVerifierSettingsContext
  langs:
  - csharp
  - vb
  name: ITermVerifierSettingsContextAware
  nameWithType: ITermVerifierSettingsContextAware
  fullName: Sdl.Verification.Api.ITermVerifierSettingsContextAware
  type: Interface
  assemblies:
  - Sdl.Verification.Api
  namespace: Sdl.Verification.Api
  summary: >-
    ITermVerifierSettingsContextAware interface represents a term verifier settings context aware object

    so such objects can be given the term verifier settings context; e.g. a term verifier settings page.
  example: []
  syntax:
    content: public interface ITermVerifierSettingsContextAware
    content.vb: Public Interface ITermVerifierSettingsContextAware
- uid: Sdl.Verification.Api.ITermVerifierSettingsContextAware.TermVerifierSettingsContext
  commentId: P:Sdl.Verification.Api.ITermVerifierSettingsContextAware.TermVerifierSettingsContext
  id: TermVerifierSettingsContext
  parent: Sdl.Verification.Api.ITermVerifierSettingsContextAware
  langs:
  - csharp
  - vb
  name: TermVerifierSettingsContext
  nameWithType: ITermVerifierSettingsContextAware.TermVerifierSettingsContext
  fullName: Sdl.Verification.Api.ITermVerifierSettingsContextAware.TermVerifierSettingsContext
  type: Property
  assemblies:
  - Sdl.Verification.Api
  namespace: Sdl.Verification.Api
  summary: TermVerifierSettingsContext property represents the term verifier settings context.
  example: []
  syntax:
    content: ITermVerifierSettingsContext TermVerifierSettingsContext { get; set; }
    parameters: []
    return:
      type: Sdl.Verification.Api.ITermVerifierSettingsContext
    content.vb: Property TermVerifierSettingsContext As ITermVerifierSettingsContext
  overload: Sdl.Verification.Api.ITermVerifierSettingsContextAware.TermVerifierSettingsContext*
references:
- uid: Sdl.Verification.Api
  commentId: N:Sdl.Verification.Api
  isExternal: true
  href: Sdl.html
  name: Sdl.Verification.Api
  nameWithType: Sdl.Verification.Api
  fullName: Sdl.Verification.Api
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Verification
    name: Verification
    isExternal: true
    href: Sdl.Verification.html
  - name: .
  - uid: Sdl.Verification.Api
    name: Api
    isExternal: true
    href: Sdl.Verification.Api.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Verification
    name: Verification
    isExternal: true
    href: Sdl.Verification.html
  - name: .
  - uid: Sdl.Verification.Api
    name: Api
    isExternal: true
    href: Sdl.Verification.Api.html
- uid: Sdl.Verification.Api.ITermVerifierSettingsContextAware.TermVerifierSettingsContext*
  commentId: Overload:Sdl.Verification.Api.ITermVerifierSettingsContextAware.TermVerifierSettingsContext
  isExternal: true
  href: Sdl.Verification.Api.ITermVerifierSettingsContextAware.html#Sdl_Verification_Api_ITermVerifierSettingsContextAware_TermVerifierSettingsContext
  name: TermVerifierSettingsContext
  nameWithType: ITermVerifierSettingsContextAware.TermVerifierSettingsContext
  fullName: Sdl.Verification.Api.ITermVerifierSettingsContextAware.TermVerifierSettingsContext
- uid: Sdl.Verification.Api.ITermVerifierSettingsContext
  commentId: T:Sdl.Verification.Api.ITermVerifierSettingsContext
  parent: Sdl.Verification.Api
  isExternal: true
  href: Sdl.Verification.Api.ITermVerifierSettingsContext.html
  name: ITermVerifierSettingsContext
  nameWithType: ITermVerifierSettingsContext
  fullName: Sdl.Verification.Api.ITermVerifierSettingsContext
