### YamlMime:ManagedReference
items:
- uid: Sdl.Core.Globalization.LanguageDisplaySettings
  commentId: T:Sdl.Core.Globalization.LanguageDisplaySettings
  id: LanguageDisplaySettings
  parent: Sdl.Core.Globalization
  children:
  - Sdl.Core.Globalization.LanguageDisplaySettings.Format
  - Sdl.Core.Globalization.LanguageDisplaySettings.IncludeCountry
  - Sdl.Core.Globalization.LanguageDisplaySettings.SettingsChanged
  - Sdl.Core.Globalization.LanguageDisplaySettings.UseFlags
  langs:
  - csharp
  - vb
  name: LanguageDisplaySettings
  nameWithType: LanguageDisplaySettings
  fullName: Sdl.Core.Globalization.LanguageDisplaySettings
  type: Class
  assemblies:
  - Sdl.Core.Globalization.Async
  namespace: Sdl.Core.Globalization
  syntax:
    content: public sealed class LanguageDisplaySettings
    content.vb: Public NotInheritable Class LanguageDisplaySettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
- uid: Sdl.Core.Globalization.LanguageDisplaySettings.Format
  commentId: P:Sdl.Core.Globalization.LanguageDisplaySettings.Format
  id: Format
  parent: Sdl.Core.Globalization.LanguageDisplaySettings
  langs:
  - csharp
  - vb
  name: Format
  nameWithType: LanguageDisplaySettings.Format
  fullName: Sdl.Core.Globalization.LanguageDisplaySettings.Format
  type: Property
  assemblies:
  - Sdl.Core.Globalization.Async
  namespace: Sdl.Core.Globalization
  syntax:
    content: public LanguageFormat Format { get; set; }
    parameters: []
    return:
      type: Sdl.Core.Globalization.LanguageFormat
    content.vb: Public Property Format As LanguageFormat
  overload: Sdl.Core.Globalization.LanguageDisplaySettings.Format*
- uid: Sdl.Core.Globalization.LanguageDisplaySettings.IncludeCountry
  commentId: P:Sdl.Core.Globalization.LanguageDisplaySettings.IncludeCountry
  id: IncludeCountry
  parent: Sdl.Core.Globalization.LanguageDisplaySettings
  langs:
  - csharp
  - vb
  name: IncludeCountry
  nameWithType: LanguageDisplaySettings.IncludeCountry
  fullName: Sdl.Core.Globalization.LanguageDisplaySettings.IncludeCountry
  type: Property
  assemblies:
  - Sdl.Core.Globalization.Async
  namespace: Sdl.Core.Globalization
  syntax:
    content: public bool IncludeCountry { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IncludeCountry As Boolean
  overload: Sdl.Core.Globalization.LanguageDisplaySettings.IncludeCountry*
- uid: Sdl.Core.Globalization.LanguageDisplaySettings.UseFlags
  commentId: P:Sdl.Core.Globalization.LanguageDisplaySettings.UseFlags
  id: UseFlags
  parent: Sdl.Core.Globalization.LanguageDisplaySettings
  langs:
  - csharp
  - vb
  name: UseFlags
  nameWithType: LanguageDisplaySettings.UseFlags
  fullName: Sdl.Core.Globalization.LanguageDisplaySettings.UseFlags
  type: Property
  assemblies:
  - Sdl.Core.Globalization.Async
  namespace: Sdl.Core.Globalization
  syntax:
    content: public bool UseFlags { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property UseFlags As Boolean
  overload: Sdl.Core.Globalization.LanguageDisplaySettings.UseFlags*
- uid: Sdl.Core.Globalization.LanguageDisplaySettings.SettingsChanged
  commentId: E:Sdl.Core.Globalization.LanguageDisplaySettings.SettingsChanged
  id: SettingsChanged
  parent: Sdl.Core.Globalization.LanguageDisplaySettings
  langs:
  - csharp
  - vb
  name: SettingsChanged
  nameWithType: LanguageDisplaySettings.SettingsChanged
  fullName: Sdl.Core.Globalization.LanguageDisplaySettings.SettingsChanged
  type: Event
  assemblies:
  - Sdl.Core.Globalization.Async
  namespace: Sdl.Core.Globalization
  syntax:
    content: public event EventHandler SettingsChanged
    return:
      type: System.EventHandler
    content.vb: Public Event SettingsChanged As EventHandler
references:
- uid: Sdl.Core.Globalization
  commentId: N:Sdl.Core.Globalization
  isExternal: true
  href: Sdl.html
  name: Sdl.Core.Globalization
  nameWithType: Sdl.Core.Globalization
  fullName: Sdl.Core.Globalization
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Core
    name: Core
    isExternal: true
    href: Sdl.Core.html
  - name: .
  - uid: Sdl.Core.Globalization
    name: Globalization
    isExternal: true
    href: Sdl.Core.Globalization.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Core
    name: Core
    isExternal: true
    href: Sdl.Core.html
  - name: .
  - uid: Sdl.Core.Globalization
    name: Globalization
    isExternal: true
    href: Sdl.Core.Globalization.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.Core.Globalization.LanguageDisplaySettings.Format*
  commentId: Overload:Sdl.Core.Globalization.LanguageDisplaySettings.Format
  isExternal: true
  href: Sdl.Core.Globalization.LanguageDisplaySettings.html#Sdl_Core_Globalization_LanguageDisplaySettings_Format
  name: Format
  nameWithType: LanguageDisplaySettings.Format
  fullName: Sdl.Core.Globalization.LanguageDisplaySettings.Format
- uid: Sdl.Core.Globalization.LanguageFormat
  commentId: T:Sdl.Core.Globalization.LanguageFormat
  parent: Sdl.Core.Globalization
  isExternal: true
  href: Sdl.Core.Globalization.LanguageFormat.html
  name: LanguageFormat
  nameWithType: LanguageFormat
  fullName: Sdl.Core.Globalization.LanguageFormat
- uid: Sdl.Core.Globalization.LanguageDisplaySettings.IncludeCountry*
  commentId: Overload:Sdl.Core.Globalization.LanguageDisplaySettings.IncludeCountry
  isExternal: true
  href: Sdl.Core.Globalization.LanguageDisplaySettings.html#Sdl_Core_Globalization_LanguageDisplaySettings_IncludeCountry
  name: IncludeCountry
  nameWithType: LanguageDisplaySettings.IncludeCountry
  fullName: Sdl.Core.Globalization.LanguageDisplaySettings.IncludeCountry
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Sdl.Core.Globalization.LanguageDisplaySettings.UseFlags*
  commentId: Overload:Sdl.Core.Globalization.LanguageDisplaySettings.UseFlags
  isExternal: true
  href: Sdl.Core.Globalization.LanguageDisplaySettings.html#Sdl_Core_Globalization_LanguageDisplaySettings_UseFlags
  name: UseFlags
  nameWithType: LanguageDisplaySettings.UseFlags
  fullName: Sdl.Core.Globalization.LanguageDisplaySettings.UseFlags
- uid: System.EventHandler
  commentId: T:System.EventHandler
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.eventhandler
  name: EventHandler
  nameWithType: EventHandler
  fullName: System.EventHandler
