### YamlMime:ManagedReference
items:
- uid: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware
  commentId: T:Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware
  id: AbstractSettingsBundleAware
  parent: Sdl.Core.Settings.Implementation
  children:
  - Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.#ctor
  - Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.SetSettingsBundle(Sdl.Core.Settings.ISettingsBundle)
  - Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.SettingsBundle
  langs:
  - csharp
  - vb
  name: AbstractSettingsBundleAware
  nameWithType: AbstractSettingsBundleAware
  fullName: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware
  type: Class
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings.Implementation
  syntax:
    content: 'public abstract class AbstractSettingsBundleAware : ISettingsBundleAware'
    content.vb: Public MustInherit Class AbstractSettingsBundleAware Implements ISettingsBundleAware
  inheritance:
  - System.Object
  implements:
  - Sdl.Core.Settings.ISettingsBundleAware
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
- uid: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.SetSettingsBundle(Sdl.Core.Settings.ISettingsBundle)
  commentId: M:Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.SetSettingsBundle(Sdl.Core.Settings.ISettingsBundle)
  id: SetSettingsBundle(Sdl.Core.Settings.ISettingsBundle)
  parent: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware
  langs:
  - csharp
  - vb
  name: SetSettingsBundle(ISettingsBundle)
  nameWithType: AbstractSettingsBundleAware.SetSettingsBundle(ISettingsBundle)
  fullName: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.SetSettingsBundle(Sdl.Core.Settings.ISettingsBundle)
  type: Method
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings.Implementation
  example: []
  syntax:
    content: public virtual void SetSettingsBundle(ISettingsBundle settingsBundle)
    parameters:
    - id: settingsBundle
      type: Sdl.Core.Settings.ISettingsBundle
    content.vb: Public Overridable Sub SetSettingsBundle(settingsBundle As ISettingsBundle)
  overload: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.SetSettingsBundle*
  implements:
  - Sdl.Core.Settings.ISettingsBundleAware.SetSettingsBundle(Sdl.Core.Settings.ISettingsBundle)
- uid: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.#ctor
  commentId: M:Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.#ctor
  id: '#ctor'
  parent: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware
  langs:
  - csharp
  - vb
  name: AbstractSettingsBundleAware()
  nameWithType: AbstractSettingsBundleAware.AbstractSettingsBundleAware()
  fullName: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.AbstractSettingsBundleAware()
  type: Constructor
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings.Implementation
  syntax:
    content: protected AbstractSettingsBundleAware()
    content.vb: Protected Sub New()
  overload: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.#ctor*
  nameWithType.vb: AbstractSettingsBundleAware.New()
  fullName.vb: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.New()
  name.vb: New()
- uid: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.SettingsBundle
  commentId: P:Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.SettingsBundle
  id: SettingsBundle
  parent: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware
  langs:
  - csharp
  - vb
  name: SettingsBundle
  nameWithType: AbstractSettingsBundleAware.SettingsBundle
  fullName: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.SettingsBundle
  type: Property
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings.Implementation
  syntax:
    content: public ISettingsBundle SettingsBundle { get; set; }
    parameters: []
    return:
      type: Sdl.Core.Settings.ISettingsBundle
    content.vb: Public Property SettingsBundle As ISettingsBundle
  overload: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.SettingsBundle*
references:
- uid: Sdl.Core.Settings.Implementation
  commentId: N:Sdl.Core.Settings.Implementation
  isExternal: true
  href: Sdl.html
  name: Sdl.Core.Settings.Implementation
  nameWithType: Sdl.Core.Settings.Implementation
  fullName: Sdl.Core.Settings.Implementation
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Core
    name: Core
    isExternal: true
    href: Sdl.Core.html
  - name: .
  - uid: Sdl.Core.Settings
    name: Settings
    isExternal: true
    href: Sdl.Core.Settings.html
  - name: .
  - uid: Sdl.Core.Settings.Implementation
    name: Implementation
    isExternal: true
    href: Sdl.Core.Settings.Implementation.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Core
    name: Core
    isExternal: true
    href: Sdl.Core.html
  - name: .
  - uid: Sdl.Core.Settings
    name: Settings
    isExternal: true
    href: Sdl.Core.Settings.html
  - name: .
  - uid: Sdl.Core.Settings.Implementation
    name: Implementation
    isExternal: true
    href: Sdl.Core.Settings.Implementation.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Sdl.Core.Settings.ISettingsBundleAware
  commentId: T:Sdl.Core.Settings.ISettingsBundleAware
  parent: Sdl.Core.Settings
  isExternal: true
  href: Sdl.Core.Settings.ISettingsBundleAware.html
  name: ISettingsBundleAware
  nameWithType: ISettingsBundleAware
  fullName: Sdl.Core.Settings.ISettingsBundleAware
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.Core.Settings
  commentId: N:Sdl.Core.Settings
  isExternal: true
  href: Sdl.html
  name: Sdl.Core.Settings
  nameWithType: Sdl.Core.Settings
  fullName: Sdl.Core.Settings
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Core
    name: Core
    isExternal: true
    href: Sdl.Core.html
  - name: .
  - uid: Sdl.Core.Settings
    name: Settings
    isExternal: true
    href: Sdl.Core.Settings.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Core
    name: Core
    isExternal: true
    href: Sdl.Core.html
  - name: .
  - uid: Sdl.Core.Settings
    name: Settings
    isExternal: true
    href: Sdl.Core.Settings.html
- uid: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.SetSettingsBundle*
  commentId: Overload:Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.SetSettingsBundle
  isExternal: true
  href: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.html#Sdl_Core_Settings_Implementation_AbstractSettingsBundleAware_SetSettingsBundle_Sdl_Core_Settings_ISettingsBundle_
  name: SetSettingsBundle
  nameWithType: AbstractSettingsBundleAware.SetSettingsBundle
  fullName: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.SetSettingsBundle
- uid: Sdl.Core.Settings.ISettingsBundleAware.SetSettingsBundle(Sdl.Core.Settings.ISettingsBundle)
  commentId: M:Sdl.Core.Settings.ISettingsBundleAware.SetSettingsBundle(Sdl.Core.Settings.ISettingsBundle)
  parent: Sdl.Core.Settings.ISettingsBundleAware
  isExternal: true
  href: Sdl.Core.Settings.ISettingsBundleAware.html#Sdl_Core_Settings_ISettingsBundleAware_SetSettingsBundle_Sdl_Core_Settings_ISettingsBundle_
  name: SetSettingsBundle(ISettingsBundle)
  nameWithType: ISettingsBundleAware.SetSettingsBundle(ISettingsBundle)
  fullName: Sdl.Core.Settings.ISettingsBundleAware.SetSettingsBundle(Sdl.Core.Settings.ISettingsBundle)
  spec.csharp:
  - uid: Sdl.Core.Settings.ISettingsBundleAware.SetSettingsBundle(Sdl.Core.Settings.ISettingsBundle)
    name: SetSettingsBundle
    isExternal: true
    href: Sdl.Core.Settings.ISettingsBundleAware.html#Sdl_Core_Settings_ISettingsBundleAware_SetSettingsBundle_Sdl_Core_Settings_ISettingsBundle_
  - name: (
  - uid: Sdl.Core.Settings.ISettingsBundle
    name: ISettingsBundle
    isExternal: true
    href: Sdl.Core.Settings.ISettingsBundle.html
  - name: )
  spec.vb:
  - uid: Sdl.Core.Settings.ISettingsBundleAware.SetSettingsBundle(Sdl.Core.Settings.ISettingsBundle)
    name: SetSettingsBundle
    isExternal: true
    href: Sdl.Core.Settings.ISettingsBundleAware.html#Sdl_Core_Settings_ISettingsBundleAware_SetSettingsBundle_Sdl_Core_Settings_ISettingsBundle_
  - name: (
  - uid: Sdl.Core.Settings.ISettingsBundle
    name: ISettingsBundle
    isExternal: true
    href: Sdl.Core.Settings.ISettingsBundle.html
  - name: )
- uid: Sdl.Core.Settings.ISettingsBundle
  commentId: T:Sdl.Core.Settings.ISettingsBundle
  parent: Sdl.Core.Settings
  isExternal: true
  href: Sdl.Core.Settings.ISettingsBundle.html
  name: ISettingsBundle
  nameWithType: ISettingsBundle
  fullName: Sdl.Core.Settings.ISettingsBundle
- uid: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.#ctor*
  commentId: Overload:Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.#ctor
  isExternal: true
  href: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.html#Sdl_Core_Settings_Implementation_AbstractSettingsBundleAware__ctor
  name: AbstractSettingsBundleAware
  nameWithType: AbstractSettingsBundleAware.AbstractSettingsBundleAware
  fullName: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.AbstractSettingsBundleAware
  nameWithType.vb: AbstractSettingsBundleAware.New
  fullName.vb: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.New
  name.vb: New
- uid: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.SettingsBundle*
  commentId: Overload:Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.SettingsBundle
  isExternal: true
  href: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.html#Sdl_Core_Settings_Implementation_AbstractSettingsBundleAware_SettingsBundle
  name: SettingsBundle
  nameWithType: AbstractSettingsBundleAware.SettingsBundle
  fullName: Sdl.Core.Settings.Implementation.AbstractSettingsBundleAware.SettingsBundle
