### YamlMime:ManagedReference
items:
- uid: Sdl.Core.PluginFramework.Configuration
  commentId: N:Sdl.Core.PluginFramework.Configuration
  id: Sdl.Core.PluginFramework.Configuration
  children:
  - Sdl.Core.PluginFramework.Configuration.ConfigManager
  - Sdl.Core.PluginFramework.Configuration.IFrameworkConfiguration
  langs:
  - csharp
  - vb
  name: Sdl.Core.PluginFramework.Configuration
  nameWithType: Sdl.Core.PluginFramework.Configuration
  fullName: Sdl.Core.PluginFramework.Configuration
  type: Namespace
  assemblies:
  - Sdl.Core.PluginFramework
references:
- uid: Sdl.Core.PluginFramework.Configuration.ConfigManager
  commentId: T:Sdl.Core.PluginFramework.Configuration.ConfigManager
  isExternal: true
  href: Sdl.Core.PluginFramework.Configuration.ConfigManager.html
  name: ConfigManager
  nameWithType: ConfigManager
  fullName: Sdl.Core.PluginFramework.Configuration.ConfigManager
- uid: Sdl.Core.PluginFramework.Configuration.IFrameworkConfiguration
  commentId: T:Sdl.Core.PluginFramework.Configuration.IFrameworkConfiguration
  parent: Sdl.Core.PluginFramework.Configuration
  isExternal: true
  href: Sdl.Core.PluginFramework.Configuration.IFrameworkConfiguration.html
  name: IFrameworkConfiguration
  nameWithType: IFrameworkConfiguration
  fullName: Sdl.Core.PluginFramework.Configuration.IFrameworkConfiguration
- uid: Sdl.Core.PluginFramework.Configuration
  commentId: N:Sdl.Core.PluginFramework.Configuration
  isExternal: true
  href: Sdl.html
  name: Sdl.Core.PluginFramework.Configuration
  nameWithType: Sdl.Core.PluginFramework.Configuration
  fullName: Sdl.Core.PluginFramework.Configuration
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Core
    name: Core
    isExternal: true
    href: Sdl.Core.html
  - name: .
  - uid: Sdl.Core.PluginFramework
    name: PluginFramework
    isExternal: true
    href: Sdl.Core.PluginFramework.html
  - name: .
  - uid: Sdl.Core.PluginFramework.Configuration
    name: Configuration
    isExternal: true
    href: Sdl.Core.PluginFramework.Configuration.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Core
    name: Core
    isExternal: true
    href: Sdl.Core.html
  - name: .
  - uid: Sdl.Core.PluginFramework
    name: PluginFramework
    isExternal: true
    href: Sdl.Core.PluginFramework.html
  - name: .
  - uid: Sdl.Core.PluginFramework.Configuration
    name: Configuration
    isExternal: true
    href: Sdl.Core.PluginFramework.Configuration.html
