### YamlMime:ManagedReference
items:
- uid: Sdl.Core.Settings.SettingsChangedEventArgs
  commentId: T:Sdl.Core.Settings.SettingsChangedEventArgs
  id: SettingsChangedEventArgs
  parent: Sdl.Core.Settings
  children:
  - Sdl.Core.Settings.SettingsChangedEventArgs.#ctor(Sdl.Core.Settings.ISettingsGroup,System.Collections.Generic.IList{System.String})
  - Sdl.Core.Settings.SettingsChangedEventArgs.SettingIds
  - Sdl.Core.Settings.SettingsChangedEventArgs.SettingsGroup
  langs:
  - csharp
  - vb
  name: SettingsChangedEventArgs
  nameWithType: SettingsChangedEventArgs
  fullName: Sdl.Core.Settings.SettingsChangedEventArgs
  type: Class
  source:
    path: Sdl.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings
  syntax:
    content: 'public class SettingsChangedEventArgs : EventArgs'
    content.vb: >-
      Public Class SettingsChangedEventArgs

          Inherits EventArgs
  inheritance:
  - System.Object
  - System.EventArgs
  inheritedMembers:
  - System.EventArgs.Empty
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Sdl.Core.Settings.SettingsChangedEventArgs.#ctor(Sdl.Core.Settings.ISettingsGroup,System.Collections.Generic.IList{System.String})
  commentId: M:Sdl.Core.Settings.SettingsChangedEventArgs.#ctor(Sdl.Core.Settings.ISettingsGroup,System.Collections.Generic.IList{System.String})
  id: '#ctor(Sdl.Core.Settings.ISettingsGroup,System.Collections.Generic.IList{System.String})'
  parent: Sdl.Core.Settings.SettingsChangedEventArgs
  langs:
  - csharp
  - vb
  name: SettingsChangedEventArgs(ISettingsGroup, IList<String>)
  nameWithType: SettingsChangedEventArgs.SettingsChangedEventArgs(ISettingsGroup, IList<String>)
  fullName: Sdl.Core.Settings.SettingsChangedEventArgs.SettingsChangedEventArgs(Sdl.Core.Settings.ISettingsGroup, System.Collections.Generic.IList<System.String>)
  type: Constructor
  source:
    path: Sdl.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings
  syntax:
    content: public SettingsChangedEventArgs(ISettingsGroup settingsGroup, IList<string> settingIds)
    parameters:
    - id: settingsGroup
      type: Sdl.Core.Settings.ISettingsGroup
    - id: settingIds
      type: System.Collections.Generic.IList{System.String}
    content.vb: Public Sub New(settingsGroup As ISettingsGroup, settingIds As IList(Of String))
  overload: Sdl.Core.Settings.SettingsChangedEventArgs.#ctor*
  nameWithType.vb: SettingsChangedEventArgs.SettingsChangedEventArgs(ISettingsGroup, IList(Of String))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Sdl.Core.Settings.SettingsChangedEventArgs.SettingsChangedEventArgs(Sdl.Core.Settings.ISettingsGroup, System.Collections.Generic.IList(Of System.String))
  name.vb: SettingsChangedEventArgs(ISettingsGroup, IList(Of String))
- uid: Sdl.Core.Settings.SettingsChangedEventArgs.SettingsGroup
  commentId: P:Sdl.Core.Settings.SettingsChangedEventArgs.SettingsGroup
  id: SettingsGroup
  parent: Sdl.Core.Settings.SettingsChangedEventArgs
  langs:
  - csharp
  - vb
  name: SettingsGroup
  nameWithType: SettingsChangedEventArgs.SettingsGroup
  fullName: Sdl.Core.Settings.SettingsChangedEventArgs.SettingsGroup
  type: Property
  source:
    path: Sdl.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings
  syntax:
    content: public ISettingsGroup SettingsGroup { get; }
    parameters: []
    return:
      type: Sdl.Core.Settings.ISettingsGroup
    content.vb: Public ReadOnly Property SettingsGroup As ISettingsGroup
  overload: Sdl.Core.Settings.SettingsChangedEventArgs.SettingsGroup*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Sdl.Core.Settings.SettingsChangedEventArgs.SettingIds
  commentId: P:Sdl.Core.Settings.SettingsChangedEventArgs.SettingIds
  id: SettingIds
  parent: Sdl.Core.Settings.SettingsChangedEventArgs
  langs:
  - csharp
  - vb
  name: SettingIds
  nameWithType: SettingsChangedEventArgs.SettingIds
  fullName: Sdl.Core.Settings.SettingsChangedEventArgs.SettingIds
  type: Property
  source:
    path: Sdl.Core.Settings
    isExternal: true
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings
  syntax:
    content: public IList<string> SettingIds { get; }
    parameters: []
    return:
      type: System.Collections.Generic.IList{System.String}
    content.vb: Public ReadOnly Property SettingIds As IList(Of String)
  overload: Sdl.Core.Settings.SettingsChangedEventArgs.SettingIds*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Sdl.Core.Settings
  commentId: N:Sdl.Core.Settings
  isExternal: true
  name: Sdl.Core.Settings
  nameWithType: Sdl.Core.Settings
  fullName: Sdl.Core.Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.EventArgs
  commentId: T:System.EventArgs
  parent: System
  isExternal: true
  name: EventArgs
  nameWithType: EventArgs
  fullName: System.EventArgs
- uid: System.EventArgs.Empty
  commentId: F:System.EventArgs.Empty
  parent: System.EventArgs
  isExternal: true
  name: Empty
  nameWithType: EventArgs.Empty
  fullName: System.EventArgs.Empty
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.Core.Settings.SettingsChangedEventArgs.#ctor*
  commentId: Overload:Sdl.Core.Settings.SettingsChangedEventArgs.#ctor
  isExternal: true
  name: SettingsChangedEventArgs
  nameWithType: SettingsChangedEventArgs.SettingsChangedEventArgs
  fullName: Sdl.Core.Settings.SettingsChangedEventArgs.SettingsChangedEventArgs
- uid: Sdl.Core.Settings.ISettingsGroup
  commentId: T:Sdl.Core.Settings.ISettingsGroup
  parent: Sdl.Core.Settings
  isExternal: true
  name: ISettingsGroup
  nameWithType: ISettingsGroup
  fullName: Sdl.Core.Settings.ISettingsGroup
- uid: System.Collections.Generic.IList{System.String}
  commentId: T:System.Collections.Generic.IList{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<String>
  nameWithType: IList<String>
  fullName: System.Collections.Generic.IList<System.String>
  nameWithType.vb: IList(Of String)
  fullName.vb: System.Collections.Generic.IList(Of System.String)
  name.vb: IList(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  commentId: T:System.Collections.Generic.IList`1
  isExternal: true
  name: IList<T>
  nameWithType: IList<T>
  fullName: System.Collections.Generic.IList<T>
  nameWithType.vb: IList(Of T)
  fullName.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: Sdl.Core.Settings.SettingsChangedEventArgs.SettingsGroup*
  commentId: Overload:Sdl.Core.Settings.SettingsChangedEventArgs.SettingsGroup
  isExternal: true
  name: SettingsGroup
  nameWithType: SettingsChangedEventArgs.SettingsGroup
  fullName: Sdl.Core.Settings.SettingsChangedEventArgs.SettingsGroup
- uid: Sdl.Core.Settings.SettingsChangedEventArgs.SettingIds*
  commentId: Overload:Sdl.Core.Settings.SettingsChangedEventArgs.SettingIds
  isExternal: true
  name: SettingIds
  nameWithType: SettingsChangedEventArgs.SettingIds
  fullName: Sdl.Core.Settings.SettingsChangedEventArgs.SettingIds
