### YamlMime:ManagedReference
items:
- uid: Sdl.Core.Settings.Setting`1
  commentId: T:Sdl.Core.Settings.Setting`1
  id: Setting`1
  parent: Sdl.Core.Settings
  children:
  - Sdl.Core.Settings.Setting`1.#ctor
  - Sdl.Core.Settings.Setting`1.Id
  - Sdl.Core.Settings.Setting`1.Inherited
  - Sdl.Core.Settings.Setting`1.Reset
  - Sdl.Core.Settings.Setting`1.Value
  - Sdl.Core.Settings.Setting`1._inherited
  - Sdl.Core.Settings.Setting`1.op_Implicit(Sdl.Core.Settings.Setting{`0})~`0
  langs:
  - csharp
  - vb
  name: Setting<T>
  nameWithType: Setting<T>
  fullName: Sdl.Core.Settings.Setting<T>
  type: Class
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings
  syntax:
    content: public abstract class Setting<T>
    typeParameters:
    - id: T
    content.vb: Public MustInherit Class Setting(Of T)
  inheritance:
  - System.Object
  derivedClasses:
  - Sdl.Core.Settings.Implementation.Json.JsonSettingImpl`1
  - Sdl.Core.Settings.Implementation.Xml.XmlSettingImpl`1
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  nameWithType.vb: Setting(Of T)
  fullName.vb: Sdl.Core.Settings.Setting(Of T)
  name.vb: Setting(Of T)
- uid: Sdl.Core.Settings.Setting`1._inherited
  commentId: F:Sdl.Core.Settings.Setting`1._inherited
  id: _inherited
  parent: Sdl.Core.Settings.Setting`1
  langs:
  - csharp
  - vb
  name: _inherited
  nameWithType: Setting<T>._inherited
  fullName: Sdl.Core.Settings.Setting<T>._inherited
  type: Field
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings
  syntax:
    content: protected bool _inherited
    return:
      type: System.Boolean
    content.vb: Protected _inherited As Boolean
  nameWithType.vb: Setting(Of T)._inherited
  fullName.vb: Sdl.Core.Settings.Setting(Of T)._inherited
- uid: Sdl.Core.Settings.Setting`1.op_Implicit(Sdl.Core.Settings.Setting{`0})~`0
  commentId: M:Sdl.Core.Settings.Setting`1.op_Implicit(Sdl.Core.Settings.Setting{`0})~`0
  id: op_Implicit(Sdl.Core.Settings.Setting{`0})~`0
  parent: Sdl.Core.Settings.Setting`1
  langs:
  - csharp
  - vb
  name: implicit operator T(Setting<T>)
  nameWithType: Setting<T>.implicit operator T(Setting<T>)
  fullName: Sdl.Core.Settings.Setting<T>.implicit operator T(Sdl.Core.Settings.Setting<T>)
  type: Operator
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings
  syntax:
    content: public static implicit operator T(Setting<T> setting)
    parameters:
    - id: setting
      type: Sdl.Core.Settings.Setting`1
    return:
      type: '{T}'
    content.vb: Public Shared Widening Operator CType(setting As Setting(Of T)) As T
  overload: Sdl.Core.Settings.Setting`1.op_Implicit*
  nameWithType.vb: Setting(Of T).CType(Setting(Of T))
  fullName.vb: Sdl.Core.Settings.Setting(Of T).CType(Sdl.Core.Settings.Setting(Of T))
  name.vb: CType(Setting(Of T))
- uid: Sdl.Core.Settings.Setting`1.Reset
  commentId: M:Sdl.Core.Settings.Setting`1.Reset
  id: Reset
  parent: Sdl.Core.Settings.Setting`1
  langs:
  - csharp
  - vb
  name: Reset()
  nameWithType: Setting<T>.Reset()
  fullName: Sdl.Core.Settings.Setting<T>.Reset()
  type: Method
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings
  syntax:
    content: public abstract void Reset()
    content.vb: Public MustOverride Sub Reset()
  overload: Sdl.Core.Settings.Setting`1.Reset*
  nameWithType.vb: Setting(Of T).Reset()
  fullName.vb: Sdl.Core.Settings.Setting(Of T).Reset()
- uid: Sdl.Core.Settings.Setting`1.#ctor
  commentId: M:Sdl.Core.Settings.Setting`1.#ctor
  id: '#ctor'
  parent: Sdl.Core.Settings.Setting`1
  langs:
  - csharp
  - vb
  name: Setting()
  nameWithType: Setting<T>.Setting()
  fullName: Sdl.Core.Settings.Setting<T>.Setting()
  type: Constructor
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings
  syntax:
    content: protected Setting()
    content.vb: Protected Sub New()
  overload: Sdl.Core.Settings.Setting`1.#ctor*
  nameWithType.vb: Setting(Of T).New()
  fullName.vb: Sdl.Core.Settings.Setting(Of T).New()
  name.vb: New()
- uid: Sdl.Core.Settings.Setting`1.Id
  commentId: P:Sdl.Core.Settings.Setting`1.Id
  id: Id
  parent: Sdl.Core.Settings.Setting`1
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: Setting<T>.Id
  fullName: Sdl.Core.Settings.Setting<T>.Id
  type: Property
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings
  syntax:
    content: public abstract string Id { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public MustOverride ReadOnly Property Id As String
  overload: Sdl.Core.Settings.Setting`1.Id*
  nameWithType.vb: Setting(Of T).Id
  fullName.vb: Sdl.Core.Settings.Setting(Of T).Id
- uid: Sdl.Core.Settings.Setting`1.Inherited
  commentId: P:Sdl.Core.Settings.Setting`1.Inherited
  id: Inherited
  parent: Sdl.Core.Settings.Setting`1
  langs:
  - csharp
  - vb
  name: Inherited
  nameWithType: Setting<T>.Inherited
  fullName: Sdl.Core.Settings.Setting<T>.Inherited
  type: Property
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings
  syntax:
    content: public virtual bool Inherited { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Overridable ReadOnly Property Inherited As Boolean
  overload: Sdl.Core.Settings.Setting`1.Inherited*
  nameWithType.vb: Setting(Of T).Inherited
  fullName.vb: Sdl.Core.Settings.Setting(Of T).Inherited
- uid: Sdl.Core.Settings.Setting`1.Value
  commentId: P:Sdl.Core.Settings.Setting`1.Value
  id: Value
  parent: Sdl.Core.Settings.Setting`1
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: Setting<T>.Value
  fullName: Sdl.Core.Settings.Setting<T>.Value
  type: Property
  assemblies:
  - Sdl.Core.Settings
  namespace: Sdl.Core.Settings
  syntax:
    content: public abstract T Value { get; set; }
    parameters: []
    return:
      type: '{T}'
    content.vb: Public MustOverride Property Value As T
  overload: Sdl.Core.Settings.Setting`1.Value*
  nameWithType.vb: Setting(Of T).Value
  fullName.vb: Sdl.Core.Settings.Setting(Of T).Value
references:
- uid: Sdl.Core.Settings
  commentId: N:Sdl.Core.Settings
  isExternal: true
  href: Sdl.html
  name: Sdl.Core.Settings
  nameWithType: Sdl.Core.Settings
  fullName: Sdl.Core.Settings
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Core
    name: Core
    isExternal: true
    href: Sdl.Core.html
  - name: .
  - uid: Sdl.Core.Settings
    name: Settings
    isExternal: true
    href: Sdl.Core.Settings.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Core
    name: Core
    isExternal: true
    href: Sdl.Core.html
  - name: .
  - uid: Sdl.Core.Settings
    name: Settings
    isExternal: true
    href: Sdl.Core.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Sdl.Core.Settings.Setting`1.op_Implicit*
  commentId: Overload:Sdl.Core.Settings.Setting`1.op_Implicit
  name: implicit operator
  nameWithType: Setting<T>.implicit operator
  fullName: Sdl.Core.Settings.Setting<T>.implicit operator
  nameWithType.vb: Setting(Of T).CType
  fullName.vb: Sdl.Core.Settings.Setting(Of T).CType
  name.vb: CType
  spec.csharp:
  - name: implicit
  - name: " "
  - name: operator
- uid: Sdl.Core.Settings.Setting`1
  commentId: T:Sdl.Core.Settings.Setting`1
  parent: Sdl.Core.Settings
  isExternal: true
  href: Sdl.Core.Settings.Setting-1.html
  name: Setting<T>
  nameWithType: Setting<T>
  fullName: Sdl.Core.Settings.Setting<T>
  nameWithType.vb: Setting(Of T)
  fullName.vb: Sdl.Core.Settings.Setting(Of T)
  name.vb: Setting(Of T)
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    isExternal: true
    href: Sdl.Core.Settings.Setting-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    isExternal: true
    href: Sdl.Core.Settings.Setting-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: Sdl.Core.Settings.Setting`1.Reset*
  commentId: Overload:Sdl.Core.Settings.Setting`1.Reset
  isExternal: true
  href: Sdl.Core.Settings.Setting-1.html#Sdl_Core_Settings_Setting_1_Reset
  name: Reset
  nameWithType: Setting<T>.Reset
  fullName: Sdl.Core.Settings.Setting<T>.Reset
  nameWithType.vb: Setting(Of T).Reset
  fullName.vb: Sdl.Core.Settings.Setting(Of T).Reset
- uid: Sdl.Core.Settings.Setting`1.#ctor*
  commentId: Overload:Sdl.Core.Settings.Setting`1.#ctor
  isExternal: true
  href: Sdl.Core.Settings.Setting-1.html#Sdl_Core_Settings_Setting_1__ctor
  name: Setting
  nameWithType: Setting<T>.Setting
  fullName: Sdl.Core.Settings.Setting<T>.Setting
  nameWithType.vb: Setting(Of T).New
  fullName.vb: Sdl.Core.Settings.Setting(Of T).New
  name.vb: New
- uid: Sdl.Core.Settings.Setting`1.Id*
  commentId: Overload:Sdl.Core.Settings.Setting`1.Id
  isExternal: true
  href: Sdl.Core.Settings.Setting-1.html#Sdl_Core_Settings_Setting_1_Id
  name: Id
  nameWithType: Setting<T>.Id
  fullName: Sdl.Core.Settings.Setting<T>.Id
  nameWithType.vb: Setting(Of T).Id
  fullName.vb: Sdl.Core.Settings.Setting(Of T).Id
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Sdl.Core.Settings.Setting`1.Inherited*
  commentId: Overload:Sdl.Core.Settings.Setting`1.Inherited
  isExternal: true
  href: Sdl.Core.Settings.Setting-1.html#Sdl_Core_Settings_Setting_1_Inherited
  name: Inherited
  nameWithType: Setting<T>.Inherited
  fullName: Sdl.Core.Settings.Setting<T>.Inherited
  nameWithType.vb: Setting(Of T).Inherited
  fullName.vb: Sdl.Core.Settings.Setting(Of T).Inherited
- uid: Sdl.Core.Settings.Setting`1.Value*
  commentId: Overload:Sdl.Core.Settings.Setting`1.Value
  isExternal: true
  href: Sdl.Core.Settings.Setting-1.html#Sdl_Core_Settings_Setting_1_Value
  name: Value
  nameWithType: Setting<T>.Value
  fullName: Sdl.Core.Settings.Setting<T>.Value
  nameWithType.vb: Setting(Of T).Value
  fullName.vb: Sdl.Core.Settings.Setting(Of T).Value
