### YamlMime:ManagedReference
items:
- uid: Sdl.Core.Settings
  commentId: N:Sdl.Core.Settings
  id: Sdl.Core.Settings
  children:
  - Sdl.Core.Settings.AbstractSettingsGroupBase
  - Sdl.Core.Settings.AbstractSettingsPage
  - Sdl.Core.Settings.ISettingsBundle
  - Sdl.Core.Settings.ISettingsBundleAware
  - Sdl.Core.Settings.ISettingsGroup
  - Sdl.Core.Settings.ISettingsPage
  - Sdl.Core.Settings.Setting`1
  - Sdl.Core.Settings.SettingsChangedEventArgs
  - Sdl.Core.Settings.SettingsGroup
  - Sdl.Core.Settings.SettingsUtil
  langs:
  - csharp
  - vb
  name: Sdl.Core.Settings
  nameWithType: Sdl.Core.Settings
  fullName: Sdl.Core.Settings
  type: Namespace
  assemblies:
  - Sdl.Core.Settings
references:
- uid: Sdl.Core.Settings.AbstractSettingsGroupBase
  commentId: T:Sdl.Core.Settings.AbstractSettingsGroupBase
  parent: Sdl.Core.Settings
  isExternal: true
  href: Sdl.Core.Settings.AbstractSettingsGroupBase.html
  name: AbstractSettingsGroupBase
  nameWithType: AbstractSettingsGroupBase
  fullName: Sdl.Core.Settings.AbstractSettingsGroupBase
- uid: Sdl.Core.Settings.AbstractSettingsPage
  commentId: T:Sdl.Core.Settings.AbstractSettingsPage
  isExternal: true
  href: Sdl.Core.Settings.AbstractSettingsPage.html
  name: AbstractSettingsPage
  nameWithType: AbstractSettingsPage
  fullName: Sdl.Core.Settings.AbstractSettingsPage
- uid: Sdl.Core.Settings.ISettingsBundle
  commentId: T:Sdl.Core.Settings.ISettingsBundle
  parent: Sdl.Core.Settings
  isExternal: true
  href: Sdl.Core.Settings.ISettingsBundle.html
  name: ISettingsBundle
  nameWithType: ISettingsBundle
  fullName: Sdl.Core.Settings.ISettingsBundle
- uid: Sdl.Core.Settings.ISettingsBundleAware
  commentId: T:Sdl.Core.Settings.ISettingsBundleAware
  parent: Sdl.Core.Settings
  isExternal: true
  href: Sdl.Core.Settings.ISettingsBundleAware.html
  name: ISettingsBundleAware
  nameWithType: ISettingsBundleAware
  fullName: Sdl.Core.Settings.ISettingsBundleAware
- uid: Sdl.Core.Settings.ISettingsGroup
  commentId: T:Sdl.Core.Settings.ISettingsGroup
  parent: Sdl.Core.Settings
  isExternal: true
  href: Sdl.Core.Settings.ISettingsGroup.html
  name: ISettingsGroup
  nameWithType: ISettingsGroup
  fullName: Sdl.Core.Settings.ISettingsGroup
- uid: Sdl.Core.Settings.ISettingsPage
  commentId: T:Sdl.Core.Settings.ISettingsPage
  parent: Sdl.Core.Settings
  isExternal: true
  href: Sdl.Core.Settings.ISettingsPage.html
  name: ISettingsPage
  nameWithType: ISettingsPage
  fullName: Sdl.Core.Settings.ISettingsPage
- uid: Sdl.Core.Settings.Setting`1
  commentId: T:Sdl.Core.Settings.Setting`1
  parent: Sdl.Core.Settings
  isExternal: true
  href: Sdl.Core.Settings.Setting-1.html
  name: Setting<T>
  nameWithType: Setting<T>
  fullName: Sdl.Core.Settings.Setting<T>
  nameWithType.vb: Setting(Of T)
  fullName.vb: Sdl.Core.Settings.Setting(Of T)
  name.vb: Setting(Of T)
  spec.csharp:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    isExternal: true
    href: Sdl.Core.Settings.Setting-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Sdl.Core.Settings.Setting`1
    name: Setting
    isExternal: true
    href: Sdl.Core.Settings.Setting-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Sdl.Core.Settings.SettingsChangedEventArgs
  commentId: T:Sdl.Core.Settings.SettingsChangedEventArgs
  parent: Sdl.Core.Settings
  isExternal: true
  href: Sdl.Core.Settings.SettingsChangedEventArgs.html
  name: SettingsChangedEventArgs
  nameWithType: SettingsChangedEventArgs
  fullName: Sdl.Core.Settings.SettingsChangedEventArgs
- uid: Sdl.Core.Settings.SettingsGroup
  commentId: T:Sdl.Core.Settings.SettingsGroup
  parent: Sdl.Core.Settings
  isExternal: true
  href: Sdl.Core.Settings.SettingsGroup.html
  name: SettingsGroup
  nameWithType: SettingsGroup
  fullName: Sdl.Core.Settings.SettingsGroup
- uid: Sdl.Core.Settings.SettingsUtil
  commentId: T:Sdl.Core.Settings.SettingsUtil
  isExternal: true
  href: Sdl.Core.Settings.SettingsUtil.html
  name: SettingsUtil
  nameWithType: SettingsUtil
  fullName: Sdl.Core.Settings.SettingsUtil
- uid: Sdl.Core.Settings
  commentId: N:Sdl.Core.Settings
  isExternal: true
  href: Sdl.html
  name: Sdl.Core.Settings
  nameWithType: Sdl.Core.Settings
  fullName: Sdl.Core.Settings
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Core
    name: Core
    isExternal: true
    href: Sdl.Core.html
  - name: .
  - uid: Sdl.Core.Settings
    name: Settings
    isExternal: true
    href: Sdl.Core.Settings.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.Core
    name: Core
    isExternal: true
    href: Sdl.Core.html
  - name: .
  - uid: Sdl.Core.Settings
    name: Settings
    isExternal: true
    href: Sdl.Core.Settings.html
